// components/completingSentencesData.ts
//
// Completing Sentences, one piece per family of structures the board sets:
// time, condition and wish, cause-purpose-result, contrast and comparison,
// paired and fixed structures, and relative and noun clauses. Each piece
// gives the rules in order and works each rule through examples, the part the
// question gives on one line and the finished sentence on the next. A piece of
// exceptional cases collects the traps, and board-style sets are solved item
// by item with the reason for each answer.

import type { Block, Piece } from "./englishData";

const h = (text: string): Block => ({ type: "heading", text });
const rule = (text: string, formula?: string): Block => ({
  type: "rule",
  text,
  formula,
});
const note = (text: string): Block => ({ type: "note", label: "Note", text });
// One example: each argument is a [label, sentence] pair.
const ex = (...lines: [string, string][]): Block => ({
  type: "example",
  lines: lines.map(([label, text]) => ({ label, text })),
});
// The usual pair: the part as set, then the whole sentence completed.
const q = (given: string, answer: string): Block =>
  ex(["Given", given], ["Answer", answer]);
// A common slip set against the correct sentence.
const wr = (wrong: string, right: string): Block =>
  ex(["Wrong", wrong], ["Right", right]);
const para = (text: string): Block => ({ type: "para", text });

const PROMPT = "Complete the following sentences.";

export const completingSentences: Piece[] = [
  /* ───────────────────────── Introduction ───────────────────────── */
  {
    id: "completing-sentences-introduction",
    title: "Introduction",
    body: [
      para("In the SSC English Second Paper five incomplete sentences, (a) to (e), are given, and each carries one mark. Sometimes the beginning of a sentence is given, sometimes the end, and sometimes a part in the middle is left out. You have to supply the missing part — usually a clause, sometimes a phrase — so that the whole sentence is grammatically correct and makes clear sense. Every given part contains a clue word or a structure (if, unless, though, so … that, too, it is high time, as if, no sooner had and so on) that decides what the missing part must look like. Find that clue first, and the answer almost writes itself."),
      h("How to answer"),
      para("1. Read the given part carefully and underline the clue word: a conjunction, a fixed phrase, a comparative, a modal or 'to'."),
      para("2. Decide what kind of piece is missing: a full clause with its own subject and verb, a phrase, an infinitive (to + V1) or a gerund (V-ing)."),
      para("3. Fix the tense. The tense of the given part usually decides the tense of your part: a past main clause takes a past subordinate clause, and so on."),
      para("4. Make the verb agree with its subject in number and person."),
      para("5. Keep the meaning sensible and simple. A short, safe completion that is fully correct earns the mark; a long, clever one that slips on one word loses it."),
      para("6. Write the whole sentence in the answer script, not only the missing part, and end it with the right punctuation mark."),
      h("The two kinds of set"),
      para("The board sets this question in two ways. In the first, the five sentences have nothing to do with each other, and each one tests a single structure — 'Had I the wings of a bird', 'It is high time', 'No sooner had', 'The more you read' (Rajshahi Board 2025). In the second, all five sentences are about one topic — health, time, truthfulness, trees, smoking — and together they read like a short paragraph (Dhaka Board 2025). In a topic set each completion must be correct and must also keep to the topic."),
      ex(["Separate", "(a) Had I the wings of a bird, ——— (b) It is high time ——— (c) The more you read, ———"], ["On a topic", "(a) There is a proverb that ——— (b) Unless you have good health, ——— (c) A healthy poor man is happier than ———"]),
      h("Where the gap can be"),
      q("At the end: No sooner had we reached the school ———", "No sooner had we reached the school than the bell rang."),
      q("At the beginning: ———, I walked on foot.", "As I could not find a rickshaw, I walked on foot."),
      q("At the beginning: ——— if he told me.", "I would help him if he told me."),
      q("At the beginning: ——— before you come.", "I shall have finished my work before you come."),
      note("When the gap is at the beginning, read the given end first: 'if he told me' is a second conditional, so the missing main clause needs would + V1; 'before you come' is future, so the missing clause is future or future perfect."),
      h("What the examiner checks"),
      ex(["Structure", "The clue word has been followed by the pattern it demands."], ["Tense", "The tenses of the two parts agree with each other."], ["Agreement", "Each verb agrees with its own subject."], ["Sense", "The sentence says something meaningful and logical."], ["Mechanics", "Spelling, capital letters and the full stop or question mark are right."]),
      h("The kinds of structure the board sets"),
      ex(["Time", "when · while · since · before · after · until · as soon as · no sooner … than · hardly … when · by the time"], ["Condition", "if · unless · had I … · were I … · provided · in case · otherwise"], ["Unreal & wish", "I wish · as if · as though · it is high time · would rather · had better"], ["Cause", "because · as · since · now that · because of · owing to"], ["Purpose", "so that · in order that · in order to · lest … should"], ["Result", "so … that · such … that · too … to · enough to"], ["Contrast", "though · although · in spite of · despite · however · whatever · no matter"], ["Comparison", "as … as · not so … as · than · the more … the more · prefer … to · would rather … than"], ["Pairs", "not only … but also · either … or · neither … nor · both … and · whether … or"], ["Fixed phrases", "would you mind · look forward to · it is no use · cannot help · used to · with a view to"], ["Clauses", "who · which · that · what · whether · where · the reason why · it is … that"]),
      h("Sequence of tense in brief"),
      rule("If the main clause is in the present or future tense, the subordinate clause may take any tense the sense needs.", "present / future main clause → any tense"),
      q("He says that ———", "He says that he was ill yesterday."),
      q("I shall tell you what ———", "I shall tell you what I saw at the fair."),
      rule("If the main clause is in the past tense, the subordinate clause is also in a past tense.", "past main clause → past subordinate clause"),
      q("He said that ———", "He said that he would help me."),
      q("I knew that ———", "I knew that he had finished the work."),
      note("A universal truth, a habitual fact or a comparison after 'than' / 'as' keeps its own tense even after a past main clause — see the piece on exceptional cases."),
      h("Common mistakes"),
      note("Do not leave the sentence half done. 'If I were a king,' is not an answer; 'If I were a king, I would help the poor.' is."),
      note("Do not repeat the conjunction. 'Though he is poor, but he is honest' has two joiners for one pair of clauses — use 'yet' or nothing: 'Though he is poor, he is honest.'"),
      note("Do not change the given part. Copy it exactly and add only what is missing."),
    ],
  },

  /* ─────────────────────────── Time ─────────────────────────── */
  {
    id: "completing-sentences-time",
    title: "Time Clauses",
    body: [
      para("A clause beginning with a time word tells when the action of the main clause happens. The time word decides the tense of both clauses, and the two actions must follow each other in a sensible order."),

      h("When"),
      rule("'When' + Present Indefinite takes a future (or imperative) main clause. Never put 'will' in the 'when' clause.", "When + S + V1 (s / es), S + shall / will + V1"),
      q("When he comes, ———", "When he comes, I shall give him the letter."),
      q("I shall go out when ———", "I shall go out when the rain stops."),
      rule("'When' + Past Indefinite takes a past main clause. If the main action finished before the 'when' action, use the Past Perfect.", "When + S + V2, S + V2 / had + V3"),
      q("When I was a child, ———", "When I was a child, I lived in a village."),
      q("When we reached the station, ———", "When we reached the station, the train had already left."),
      q("When the doctor came, ———", "When the doctor came, the patient had died."),

      h("While"),
      rule("'While' shows a longer action in progress; it takes the Continuous tense, and the short action that broke into it takes the Indefinite.", "While + S + was / were + V-ing, S + V2"),
      q("While I was reading, ———", "While I was reading, the light went out."),
      q("While he was crossing the road, ———", "While he was crossing the road, he was knocked down by a bus."),
      q("——— while I was sleeping.", "A thief entered my room while I was sleeping."),
      q("He disturbed me while ———", "He disturbed me while I was working."),
      q("Yesterday Mita had an accident while ———", "Yesterday Mita had an accident while she was crossing the road."),
      rule("'While' may also be followed by V-ing alone, when the subject of both parts is the same person.", "While + V-ing, S + V (same subject)"),
      q("While rowing the boat, ———", "While rowing the boat, we sang songs."),
      note("Two long actions going on together both take the Continuous: 'While I was reading, my brother was watching TV.'"),

      h("Since"),
      rule("'Since' of time points back to a moment in the past. The 'since' clause takes the Past Indefinite, and the main clause takes the Present Perfect — or 'It is / It has been + a length of time'.", "S + have / has + V3 + since + S + V2 · It is / has been + time + since + S + V2"),
      q("It is five years since ———", "It is five years since I last saw him."),
      q("Many years have passed since ———", "Many years have passed since we left our village."),
      q("Five years have passed since ———", "Five years have passed since we met last."),
      q("It is a long time since ———", "It is a long time since we met each other."),
      q("He has been ill since ———", "He has been ill since he came back from Cox's Bazar."),
      q("Since I came to Dhaka, ———", "Since I came to Dhaka, I have been living in this house."),
      rule("With a past main clause the pattern moves one step back: 'It was … since' + Past Perfect.", "It was + time + since + S + had + V3"),
      q("It was two years since ———", "It was two years since I had visited my grandparents."),
      q("It was many years since ———", "It was many years since I had seen him last."),

      h("Before and After"),
      rule("Of two past actions, the earlier one takes the Past Perfect and the later one the Past Indefinite. 'Before' marks the later action, 'after' the earlier one.", "S + had + V3 + before + S + V2 · After + S + had + V3, S + V2"),
      q("The train had left before ———", "The train had left before we reached the station."),
      q("Before the doctor came, ———", "Before the doctor came, the patient had died."),
      q("After he had finished his work, ———", "After he had finished his work, he went to bed."),
      q("——— after the sun had set.", "We returned home after the sun had set."),
      q("They went to college after ———", "They went to college after they had finished their breakfast."),
      rule("With a future sense, 'before' and 'after' take the Present Indefinite (or Present Perfect), and the main clause is future or imperative.", "Before / After + S + V1 / has + V3, S + will + V1"),
      q("Think well before ———", "Think well before you speak."),
      q("I shall go out after ———", "I shall go out after I have finished my homework."),

      h("Until and Till"),
      rule("'Until' / 'till' means 'up to the time when'. It already carries a negative idea, so its own clause is never negative. A future sense takes the Present Indefinite in the 'until' clause.", "S + will + V1 + until / till + S + V1 (s / es)"),
      q("Wait here until ———", "Wait here until I come back."),
      q("I shall wait for him till ———", "I shall wait for him till he returns."),
      q("He did not leave the field until ———", "He did not leave the field until the match was over."),
      q("Do not go out until ———", "Do not go out until the rain stops."),

      h("As soon as, No sooner … than, Hardly … when"),
      rule("'As soon as' joins two actions that follow each other at once. Both are usually in the same tense.", "As soon as + S + V2, S + V2"),
      q("As soon as the thief saw the police, ———", "As soon as the thief saw the police, he ran away."),
      q("As soon as I reach home, ———", "As soon as I reach home, I shall ring you up."),
      rule("'No sooner had' takes V3 and is always followed by 'than' + Past Indefinite.", "No sooner had + S + V3 + than + S + V2"),
      q("No sooner had he reached the station ———", "No sooner had he reached the station than the train left."),
      q("No sooner had the teacher entered the class ———", "No sooner had the teacher entered the class than the students stood up."),
      q("No sooner had we heard the news ———", "No sooner had we heard the news than we rushed to the spot."),
      rule("'Hardly had' / 'Scarcely had' take V3 and are followed by 'when' or 'before' + Past Indefinite.", "Hardly / Scarcely had + S + V3 + when / before + S + V2"),
      q("Hardly had we reached the stadium ———", "Hardly had we reached the stadium when it started raining."),
      q("Scarcely had I gone to bed ———", "Scarcely had I gone to bed when the phone rang."),
      q("Scarcely had they reached the railway station ———", "Scarcely had they reached the railway station when the train left."),
      q("Hardly had the bell rung ———", "Hardly had the bell rung when the class started."),
      q("Hardly had the leader finished his speech ———", "Hardly had the leader finished his speech when the people burst into applause."),

      h("By the time, As long as, Once, Whenever"),
      rule("'By the time' + Past Indefinite takes a Past Perfect main clause; 'by the time' + Present Indefinite takes a Future Perfect main clause.", "By the time + S + V2, S + had + V3 · By the time + S + V1, S + will have + V3"),
      q("By the time the fire brigade arrived, ———", "By the time the fire brigade arrived, the whole market had burnt down."),
      q("By the time you come back, ———", "By the time you come back, I shall have finished my lunch."),
      rule("'As long as' / 'so long as' means 'during the whole time that'.", "As long as + S + V1, S + will + V1"),
      q("As long as I live, ———", "As long as I live, I shall remember your kindness."),
      rule("'Once' as a conjunction means 'as soon as' or 'after'; 'whenever' means 'every time that'.", "Once + S + V1 / has + V3, … · Whenever + S + V1, S + V1"),
      q("Once you have made a promise, ———", "Once you have made a promise, you must keep it."),
      q("Whenever he comes to Dhaka, ———", "Whenever he comes to Dhaka, he visits us."),
    ],
  },

  /* ─────────────────── Condition, wish and the unreal ─────────────────── */
  {
    id: "completing-sentences-condition",
    title: "Conditions & Wishes",
    body: [
      para("A conditional sentence has two parts: the 'if' clause, which states the condition, and the main clause, which states the result. Which of the three types it is depends on the tense of the given part, and the other part must match it exactly."),

      h("The three conditionals"),
      rule("First conditional — a real, possible condition in the present or future. 'If' + Present Indefinite, main clause with shall / will / can / may + V1, or an imperative.", "If + S + V1 (s / es), S + shall / will / can / may + V1"),
      q("If you work hard, ———", "If you work hard, you will succeed in life."),
      q("If it rains tomorrow, ———", "If it rains tomorrow, we shall not go on the picnic."),
      q("If you see him, ———", "If you see him, tell him to meet me."),
      q("——— if you do not hurry.", "You will miss the bus if you do not hurry."),
      rule("Second conditional — an imaginary or unlikely condition in the present. 'If' + Past Indefinite ('were' for every person), main clause with would / could / might + V1.", "If + S + V2 / were, S + would / could / might + V1"),
      q("If I were a bird, ———", "If I were a bird, I would fly in the blue sky."),
      q("If I had enough money, ———", "If I had enough money, I would build a school for poor children."),
      q("If I were the Prime Minister, ———", "If I were the Prime Minister, I would remove illiteracy from the country."),
      q("He would help you if ———", "He would help you if he were here."),
      q("If I knew his phone number, ———", "If I knew his phone number, I would call him."),
      q("Our country would be developed if ———", "Our country would be developed if all the people were educated."),
      q("——— if he told me.", "I would help him if he told me."),
      rule("Third conditional — an imaginary condition in the past, the opposite of what really happened. 'If' + had + V3, main clause with would / could / might + have + V3.", "If + S + had + V3, S + would / could / might + have + V3"),
      q("If he had worked hard, ———", "If he had worked hard, he would have passed the examination."),
      q("If you had come yesterday, ———", "If you had come yesterday, you would have met my uncle."),
      q("I could have caught the train if ———", "I could have caught the train if I had started a little earlier."),
      q("If I had known his mobile number, ———", "If I had known his mobile number, I would have called him."),
      q("If he had been seen by me, ———", "If he had been seen by me, I would have called him."),
      q("——— I would have recognised you.", "If you had not worn a mask, I would have recognised you."),
      note("The general truth or 'zero' conditional uses the Present Indefinite in both parts: 'If you heat ice, it melts.' 'If it rains, the roads become muddy.'"),

      h("Conditionals without 'if'"),
      rule("'If' may be dropped and the auxiliary placed before the subject. 'Had I' is a third conditional, 'Were I' a second, 'Should you' a first.", "Had + S + V3, S + would have + V3 · Were + S …, S + would + V1 · Should + S + V1, …"),
      q("Had I been a bird, ———", "Had I been a bird, I would have flown to my mother."),
      q("Had I known his address, ———", "Had I known his address, I would have written to him."),
      q("Had he been a little careful, ———", "Had he been a little careful, he could have avoided the accident."),
      q("Had I been a billionaire, ———", "Had I been a billionaire, I would have helped the poor."),
      rule("Careful: 'Had I' + a noun, with no V3 after it, uses 'had' in the sense of 'possess'. It means 'If I had …' and is a second conditional, so the main clause takes would + V1.", "Had + S + noun (= If + S + had + noun), S + would + V1"),
      q("Had I the wings of a bird, ———", "Had I the wings of a bird, I would fly in the sky."),
      q("Had I enough money, ———", "Had I enough money, I would buy a computer."),
      q("Were I a king, ———", "Were I a king, I would help the poor."),
      q("Should you need any help, ———", "Should you need any help, please let me know."),
      rule("'But for' and 'Were it not for' / 'Had it not been for' mean 'if it were not for' / 'if it had not been for'. They take a noun, and the main clause is unreal.", "But for + noun, S + would (have) + V1 / V3"),
      q("But for your help, ———", "But for your help, I would have failed."),
      q("Were it not for the sun, ———", "Were it not for the sun, nothing could live on the earth."),

      h("Unless, Provided, In case, Otherwise"),
      rule("'Unless' means 'if … not'. It is already negative, so the 'unless' clause is never made negative. The main clause usually is.", "Unless + S + V1 (s / es), S + will + V1"),
      q("Unless you work hard, ———", "Unless you work hard, you will fail."),
      q("Unless you start now, ———", "Unless you start now, you will not reach the station in time."),
      q("——— unless you read regularly.", "You cannot improve your English unless you read regularly."),
      q("Unless you study attentively, ———", "Unless you study attentively, you will fail in the examination."),
      q("You will not prosper unless ———", "You will not prosper unless you work hard."),
      q("One cannot command the respect of others unless ———", "One cannot command the respect of others unless one is honest."),
      rule("'Provided (that)' / 'providing', 'on condition that' and 'as long as' mean 'only if'. 'In case' means 'because it may happen'.", "S + will + V1 + provided + S + V1 · … in case + S + V1"),
      q("I shall lend you the book provided ———", "I shall lend you the book provided you return it within a week."),
      q("Take an umbrella in case ———", "Take an umbrella in case it rains."),
      q("Work hard provided that ———", "Work hard provided that you want to succeed in life."),
      q("He could help you provided that ———", "He could help you provided that you work hard."),
      rule("An imperative followed by 'and' gives a promise; followed by 'or' / 'otherwise' it gives a warning.", "Imperative + and + S + will + V1 · Imperative + or / otherwise + S + will + V1"),
      q("Work hard, and ———", "Work hard, and you will shine in life."),
      q("Walk fast, otherwise ———", "Walk fast, otherwise you will miss the train."),
      q("Hurry up or ———", "Hurry up or you will be late for school."),

      h("I wish, Would that, If only"),
      rule("A wish about the present takes the Past Indefinite ('were' for every person) or 'could' + V1.", "S + wish + S + V2 / were / could + V1"),
      q("I wish ———", "I wish I were a millionaire."),
      q("I wish I could ———", "I wish I could fly like a bird."),
      q("He wishes he ———", "He wishes he knew the answer."),
      q("I wish I were ———", "I wish I were a child again."),
      rule("A wish about the past — a regret — takes the Past Perfect.", "S + wish + S + had + V3"),
      q("I wish I had ———", "I wish I had listened to my teacher's advice."),
      q("She wishes she ———", "She wishes she had not wasted her time."),
      rule("'Would that' and 'If only' express a strong wish and follow the same tenses.", "Would that / If only + S + V2 / were / had + V3"),
      q("Would that ———", "Would that I were young again!"),
      q("If only ———", "If only I had taken his advice!"),

      h("As if, As though"),
      rule("'As if' / 'as though' compare with something unreal. For the present use the Past Indefinite ('were' for every person); for the past use the Past Perfect.", "S + V + as if + S + V2 / were · S + V2 + as if + S + had + V3"),
      q("He talks as if ———", "He talks as if he were a leader."),
      q("He behaves as though ———", "He behaves as though he knew everything."),
      q("She looked as if ———", "She looked as if she had seen a ghost."),
      q("He spent money as if ———", "He spent money as if he had been a millionaire."),
      q("Hasib behaves as if ———", "Hasib behaves as if he knew everything."),
      q("We love and help one another as if ———", "We love and help one another as if we were members of the same family."),
      q("Nowadays people lie as if ———", "Nowadays people lie as if it were the easiest thing in the world."),
      q("Shila seemed upset. She talked as if ———", "Shila seemed upset. She talked as if she had lost everything."),

      h("It is time, Would rather, Had better"),
      rule("'It is time' / 'It is high time' / 'It is about time' + subject take the Past Indefinite, though the meaning is present: the action is already due.", "It is (high) time + S + V2"),
      q("It is high time ———", "It is high time we took steps to stop environmental pollution."),
      q("It is time we ———", "It is time we left for the station."),
      q("It is high time we changed ———", "It is high time we changed our bad habits."),
      q("It is high time the students ———", "It is high time the students started practising English regularly."),
      rule("Without a subject, 'It is time' takes an infinitive.", "It is time + (for + object) + to + V1"),
      q("It is time to ———", "It is time to go to bed."),
      q("It is time for us ———", "It is time for us to start."),
      rule("'Would rather' + V1 shows preference, often with 'than' + V1. With another subject after it, the verb is V2.", "S + would rather + V1 + than + V1 · S + would rather + S + V2"),
      q("I would rather die ———", "I would rather die than beg."),
      q("I would rather you ———", "I would rather you stayed with us tonight."),
      rule("'Had better' gives advice. It takes V1 without 'to'.", "S + had better + (not) + V1"),
      q("You had better ———", "You had better consult a doctor at once."),
      q("You had better not ———", "You had better not go out in this storm."),
    ],
  },

  /* ─────────────────── Cause, purpose and result ─────────────────── */
  {
    id: "completing-sentences-cause-purpose-result",
    title: "Cause, Purpose & Result",
    body: [
      para("These clauses answer three questions about an action: why it happened (cause), what it was done for (purpose) and what came of it (result). Each clue word calls for a fixed pattern."),

      h("Cause: because, as, since, now that"),
      rule("'Because', 'as' and 'since' introduce the reason. 'As' and 'since' usually open the sentence; 'because' usually comes in the middle.", "S + V + because + S + V · As / Since + S + V, S + V"),
      q("He could not attend the class because ———", "He could not attend the class because he was ill."),
      q("As it was raining, ———", "As it was raining, we stayed at home."),
      q("Since you are tired, ———", "Since you are tired, you may take some rest."),
      q("——— because he was lazy.", "He failed in the examination because he was lazy."),
      q("Books are our best friends because ———", "Books are our best friends because they never leave us."),
      q("As he was meritorious, ———", "As he was meritorious, he achieved a brilliant result."),
      q("Since Bangladesh is a disaster-prone country, ———", "Since Bangladesh is a disaster-prone country, we should always be prepared for natural calamities."),
      rule("'Now that' means 'because now'. It gives a reason that has just come true.", "Now that + S + V, S + V"),
      q("Now that you are grown up, ———", "Now that you are grown up, you should take your own decisions."),
      rule("'Because of', 'owing to', 'due to' and 'on account of' are prepositions. They take a noun or a gerund, never a clause.", "because of / owing to + noun / gerund"),
      q("He could not come to school because of ———", "He could not come to school because of his illness."),
      q("Owing to heavy rain, ———", "Owing to heavy rain, the match was cancelled."),

      h("Purpose: so that, in order that, lest"),
      rule("'So that' / 'in order that' take can / may in the present and could / might in the past.", "S + V1 + so that + S + can / may + V1 · S + V2 + so that + S + could / might + V1"),
      q("We eat so that ———", "We eat so that we may live."),
      q("He works hard so that ———", "He works hard so that he can prosper in life."),
      q("He worked hard so that ———", "He worked hard so that he could get a scholarship."),
      q("I went to the station early in order that ———", "I went to the station early in order that I might not miss the train."),
      q("We work seriously in order that Bangladesh ———", "We work seriously in order that Bangladesh may prosper."),
      q("My father gave me five hundred taka so that ———", "My father gave me five hundred taka so that I could buy a shirt."),
      q("We must eat a balanced diet so that ———", "We must eat a balanced diet so that we can stay healthy."),
      rule("'In order to' and 'so as to' do the same job with an infinitive, when the subject is the same.", "S + V + in order to / so as to + V1"),
      q("He went to Dhaka in order to ———", "He went to Dhaka in order to see the Liberation War Museum."),
      q("She reads newspapers every day so as to ———", "She reads newspapers every day so as to improve her English."),
      q("In order to have good health, ———", "In order to have good health, you must follow the rules of health."),
      rule("'Lest' means 'for fear that' or 'so that … not'. It is already negative and always takes 'should' + V1, never 'not'.", "S + V + lest + S + should + V1"),
      q("Walk carefully lest ———", "Walk carefully lest you should fall."),
      q("He ran fast lest ———", "He ran fast lest he should miss the bus."),
      q("Read attentively lest ———", "Read attentively lest you should fail."),
      q("Take your umbrella lest ———", "Take your umbrella lest you should get wet in the rain."),
      q("Hurry up lest ———", "Hurry up lest you should miss the plane."),
      note("The 'lest' clause states the thing you are afraid of. 'Read attentively lest you should pass' is grammatical but senseless — nobody is afraid of passing."),
      rule("'With a view to' also shows purpose, but 'to' here is a preposition, so it takes a gerund.", "S + V + with a view to + V-ing"),
      q("He went to the library with a view to ———", "He went to the library with a view to collecting some books."),
      q("Conscious people should come forward with a view to ———", "Conscious people should come forward with a view to helping the illiterate."),
      q("People work with a view to ———", "People work with a view to earning money."),

      h("Result: so … that, such … that"),
      rule("'So' + adjective / adverb + 'that' shows a result. In a past sentence, 'can' becomes 'could'.", "S + V + so + adj / adv + that + S + can / could (not) + V1"),
      q("He is so weak that ———", "He is so weak that he cannot walk."),
      q("The tea was so hot that ———", "The tea was so hot that I could not drink it."),
      q("He ran so fast that ———", "He ran so fast that he won the race."),
      q("The problem is so difficult that ———", "The problem is so difficult that nobody can solve it."),
      q("The load is so heavy that ———", "The load is so heavy that he cannot carry it."),
      q("The wind was so strong that ———", "The wind was so strong that it blew away the roofs of some huts."),
      q("Time is so valuable that ———", "Time is so valuable that once it is lost, it is lost for ever."),
      q("Slum dwellers are so poor that ———", "Slum dwellers are so poor that they cannot make both ends meet."),
      rule("'Such' + (a / an) + adjective + noun + 'that' does the same with a noun.", "S + V + such (a / an) + adj + noun + that + S + V"),
      q("He is such a liar that ———", "He is such a liar that nobody believes him."),
      q("It was such a hot day that ———", "It was such a hot day that we could not go out."),
      q("They are such good friends that ———", "They are such good friends that they always help each other."),

      h("Result: too … to, enough to"),
      rule("'Too' + adjective + 'to' + V1 means 'so … that … cannot'. The negative is inside 'too', so never add 'not'.", "S + V + too + adj + (for + object) + to + V1"),
      q("He is too weak ———", "He is too weak to walk."),
      q("The box is too heavy for me ———", "The box is too heavy for me to lift."),
      q("The news is too good ———", "The news is too good to be true."),
      q("The poor man is too hungry ———", "The poor man is too hungry to talk."),
      q("This poem is too difficult for me ———", "This poem is too difficult for me to understand."),
      rule("Adjective + 'enough' + 'to' + V1 shows a positive result.", "S + V + adj + enough + to + V1"),
      q("He is old enough ———", "He is old enough to understand his duties."),
      q("She is intelligent enough ———", "She is intelligent enough to solve the problem."),
      q("He was strong enough ———", "He was strong enough to defeat the enemy."),

      h("Result: so, therefore"),
      rule("A result joined by 'so', 'therefore', 'hence' or 'consequently' is a full clause.", "S + V, so / therefore + S + V"),
      q("He was ill, so ———", "He was ill, so he could not attend the class."),
      q("It was raining heavily; therefore ———", "It was raining heavily; therefore the match was postponed."),
    ],
  },

  /* ─────────────────── Contrast and comparison ─────────────────── */
  {
    id: "completing-sentences-contrast-comparison",
    title: "Contrast & Comparison",
    body: [
      para("A contrast clause says something that is surprising in the light of the other clause; a comparison clause measures one thing against another. The missing part must give the opposite idea in a contrast and the same form of the adjective in a comparison."),

      h("Though, Although, Even though"),
      rule("'Though' / 'although' + clause, then the contrasting main clause. 'Yet' may begin the main clause, but never 'but'.", "Though / Although + S + V, (yet) + S + V"),
      q("Though he is poor, ———", "Though he is poor, he is honest."),
      q("Although he worked hard, ———", "Although he worked hard, he could not get a GPA 5."),
      q("Though the sun was shining, ———", "Though the sun was shining, it was very cold."),
      q("——— though he is rich.", "He is not happy though he is rich."),
      q("Though lost wealth can be regained by hard work, ———", "Though lost wealth can be regained by hard work, lost time can never be regained."),
      q("Though cricket is a costly game, ———", "Though cricket is a costly game, it is very popular in our country."),
      q("The people of Bangladesh are friendly though ———", "The people of Bangladesh are friendly though they are poor."),
      q("Although Bangladesh is a small country, ———", "Although Bangladesh is a small country, she has a huge population."),
      rule("'Even though' makes the contrast stronger; 'even if' contrasts with something that may or may not happen.", "Even if + S + V1, S + will + V1"),
      q("Even if it rains, ———", "Even if it rains, I shall go to the meeting."),
      q("Even though he was tired, ———", "Even though he was tired, he kept on working."),

      h("In spite of, Despite"),
      rule("'In spite of' and 'despite' are prepositions. They take a noun, a pronoun or a gerund, never a clause. 'In spite of the fact that' can take a clause.", "In spite of / Despite + noun / V-ing, S + V"),
      q("In spite of his illness, ———", "In spite of his illness, he attended the examination."),
      q("Despite being poor, ———", "Despite being poor, he never begged."),
      q("In spite of the fact that he was rich, ———", "In spite of the fact that he was rich, he lived a simple life."),

      h("However, Whatever, No matter"),
      rule("'However' + adjective / adverb, and 'whatever', 'whoever', 'wherever', 'whichever' mean 'no matter how / what / who / where'. The main clause says the result does not change.", "However + adj / adv + S + V, S + V · Whatever + S + V, S + V"),
      q("However hard you try, ———", "However hard you try, you cannot beat him in chess."),
      q("Whatever you do, ———", "Whatever you do, do it sincerely."),
      q("Wherever you go, ———", "Wherever you go, you will find Bangladeshi people."),
      q("No matter how rich he is, ———", "No matter how rich he is, he is not happy."),

      h("While, Whereas"),
      rule("'While' / 'whereas' can set two facts side by side in contrast.", "S + V, while / whereas + S + V"),
      q("Some people are rich, whereas ———", "Some people are rich, whereas others are very poor."),
      q("While I like tea, ———", "While I like tea, my brother likes coffee."),

      h("As … as, Not so … as"),
      rule("Equal comparison: 'as' + positive adjective + 'as'. In the negative, 'not so … as' or 'not as … as'.", "S + V + as + adj + as + noun / pronoun (+ V) · S + V + not so + adj + as …"),
      q("Rahim is as tall as ———", "Rahim is as tall as his elder brother."),
      q("Karim is not so clever as ———", "Karim is not so clever as his sister."),
      q("He did it as well as ———", "He did it as well as he could."),

      h("Than"),
      rule("A comparative adjective is followed by 'than'. After 'than' the pronoun is in the subjective case when a verb is understood.", "S + V + comparative + than + noun / pronoun (+ V)"),
      q("He is taller than ———", "He is taller than I am."),
      q("Prevention is better than ———", "Prevention is better than cure."),
      q("Health is more valuable than ———", "Health is more valuable than wealth."),
      q("A healthy poor man is happier than ———", "A healthy poor man is happier than a sick rich man."),
      rule("Comparative + 'than any other' + singular noun, or 'than all other' + plural noun, compares one thing with the rest of its group.", "S + V + comparative + than any other + singular noun"),
      q("Dhaka is bigger than any other ———", "Dhaka is bigger than any other city in Bangladesh."),
      q("Sabbir is more intelligent than all ———", "Sabbir is more intelligent than all other boys in the class."),
      rule("'One of the' + superlative + plural noun.", "S + V + one of the + superlative + plural noun"),
      q("Rabindranath Tagore is one of the ———", "Rabindranath Tagore is one of the greatest poets in the world."),

      h("The more … the more"),
      rule("A double comparative: 'the' + comparative in both halves. It shows that one thing grows with another.", "The + comparative + S + V, the + comparative + S + V"),
      q("The more you read, ———", "The more you read, the more you learn."),
      q("The higher you go, ———", "The higher you go, the colder it becomes."),
      q("The sooner you start, ———", "The sooner you start, the better it will be."),
      q("The more we get, ———", "The more we get, the more we want."),
      q("The sooner it can be controlled, ———", "The sooner it can be controlled, the better it will be."),

      h("Prefer … to, Rather than"),
      rule("'Prefer' + noun / gerund + 'to' + noun / gerund. Here 'to' is a preposition, so the second verb is also V-ing.", "S + prefer + noun / V-ing + to + noun / V-ing"),
      q("I prefer tea ———", "I prefer tea to coffee."),
      q("I prefer reading books ———", "I prefer reading books to watching television."),
      q("He prefers walking ———", "He prefers walking to cycling."),
      rule("'Prefer to' + V1 + 'rather than' + V1.", "S + prefer + to + V1 + rather than + V1"),
      q("I prefer to stay at home ———", "I prefer to stay at home rather than go out in this rain."),
    ],
  },

  /* ─────────────────── Paired and fixed structures ─────────────────── */
  {
    id: "completing-sentences-fixed-structures",
    title: "Pairs & Fixed Structures",
    body: [
      para("Some words always come in pairs, and some phrases always take one particular form of the verb after them. These are learned once and scored every time."),

      h("Correlative pairs"),
      rule("'Not only … but also' joins two words or phrases of the same kind. With two subjects, the verb agrees with the nearer one.", "not only + A + but also + B"),
      q("He is not only intelligent ———", "He is not only intelligent but also hard-working."),
      q("Not only the students ———", "Not only the students but also the teacher was present."),
      q("Corrupt persons are not only dishonest ———", "Corrupt persons are not only dishonest but also greedy."),
      rule("'Not only' at the beginning of a clause brings the auxiliary before the subject.", "Not only + aux + S + V1, but + S + also + V"),
      q("Not only did he help me, ———", "Not only did he help me, but he also gave me good advice."),
      rule("'Either … or' and 'neither … nor' join two alternatives. The verb agrees with the nearer subject.", "Either A or B + V (agrees with B) · Neither A nor B + V (agrees with B)"),
      q("Either you or your brother ———", "Either you or your brother has broken the glass."),
      q("Neither he nor his friends ———", "Neither he nor his friends were present at the meeting."),
      q("You can either stay here ———", "You can either stay here or go with them."),
      rule("'Both … and' joins two things together and takes a plural verb.", "Both A and B + plural verb"),
      q("Both Rahim and Karim ———", "Both Rahim and Karim are good players."),
      rule("'Whether … or (not)' means 'it makes no difference which'.", "Whether + S + V + or not, S + V"),
      q("Whether you like it or not, ———", "Whether you like it or not, you must do the work."),

      h("Verb + gerund (V-ing)"),
      rule("After 'would you mind', 'cannot help', 'it is no use', 'it is no good', 'it is worth', 'there is no', 'avoid', 'enjoy', 'finish', 'give up', 'keep (on)', 'mind' and 'practise', the verb is V-ing.", "would you mind / cannot help / it is no use … + V-ing"),
      q("Would you mind ———", "Would you mind opening the window?"),
      rule("'Do you mind if I' takes the present; 'Would you mind if I' takes the past, which sounds more polite.", "Do you mind if I + V1 · Would you mind if I + V2"),
      q("Do you mind if I ———", "Do you mind if I sit here?"),
      q("Would you mind if I ———", "Would you mind if I opened the window?"),
      q("I could not help ———", "I could not help laughing at his joke."),
      q("It is no use ———", "It is no use crying over spilt milk."),
      q("This book is worth ———", "This book is worth reading."),
      q("There is no ———", "There is no knowing what may happen tomorrow."),
      q("He has given up ———", "He has given up smoking."),

      h("'To' as a preposition + V-ing"),
      rule("In 'look forward to', 'be used to', 'be accustomed to', 'with a view to', 'object to', 'be devoted to', 'in addition to' and 'confess to', 'to' is a preposition. It takes V-ing, not V1.", "look forward to / be used to / with a view to … + V-ing"),
      q("I am looking forward to ———", "I am looking forward to meeting you soon."),
      q("I am used to ———", "I am used to getting up early."),
      q("He is accustomed to ———", "He is accustomed to walking in the morning."),
      q("She devoted her life to ———", "She devoted her life to serving the poor."),

      h("Used to, Would, Make, Let"),
      rule("'Used to' + V1 describes a past habit that no longer exists.", "S + used to + V1"),
      q("When I was a boy, I used to ———", "When I was a boy, I used to swim in the river."),
      rule("'Make', 'let', 'help', 'see', 'hear', 'watch' and 'feel' + object take V1 without 'to'. In the passive, 'make' takes 'to' back.", "make / let + object + V1 · be made + to + V1"),
      q("Let him ———", "Let him go home."),
      q("My father made me ———", "My father made me do the work."),
      q("He was made ———", "He was made to do the work."),
      q("I saw him ———", "I saw him cross the road."),

      h("It takes, It is … to"),
      rule("'It takes / took' + person + time + to + V1; 'spend' + time + V-ing.", "It takes + object + time + to + V1 · S + spend + time + V-ing"),
      q("It took me two hours ———", "It took me two hours to finish the work."),
      q("He spent the whole day ———", "He spent the whole day reading story books."),
      rule("'It is' + adjective + (for / of + object) + to + V1.", "It is + adj + (for + object) + to + V1"),
      q("It is difficult for me ———", "It is difficult for me to solve this problem."),
      q("It is very kind of you ———", "It is very kind of you to help me."),

      h("Other set phrases"),
      rule("'Let alone' comes after a negative idea and means 'and much less'.", "negative clause + let alone + noun / V1"),
      q("He cannot even walk, ———", "He cannot even walk, let alone run."),
      rule("'It goes without saying that' and 'There is no doubt that' take a full clause.", "It goes without saying that + S + V"),
      q("It goes without saying that ———", "It goes without saying that honesty is the best policy."),
      q("There is no doubt that ———", "There is no doubt that education is the backbone of a nation."),
      rule("'Without' + V-ing, and 'instead of' + V-ing.", "S + V + without / instead of + V-ing"),
      q("He left the room without ———", "He left the room without saying anything."),
      q("Instead of wasting your time, ———", "Instead of wasting your time, you should study."),
    ],
  },

  /* ─────────────────── Relative and noun clauses ─────────────────── */
  {
    id: "completing-sentences-clauses",
    title: "Relative & Noun Clauses",
    body: [
      para("Sometimes the given part ends with a relative pronoun (who, which, that, whose, where) or with a word that begins a noun clause (that, what, whether, how, why). The missing part is then a clause that describes a noun or does the work of a noun."),

      h("Relative clauses"),
      rule("'Who' for persons, 'which' for things and animals, 'that' for either, 'whose' for possession, 'whom' for the object. The verb of the relative clause agrees with the noun before the relative pronoun.", "noun + who / which / that + V …"),
      q("He is the man who ———", "He is the man who helped me in my danger."),
      q("This is the book which ———", "This is the book which I bought from the book fair."),
      q("The boy whose father is a doctor ———", "The boy whose father is a doctor is my best friend."),
      q("The girl whom you met yesterday ———", "The girl whom you met yesterday is my cousin."),
      q("Those who work hard ———", "Those who work hard shine in life."),
      q("He who is content ———", "He who is content is happy."),
      q("Those who waste time ———", "Those who waste time cannot shine in life."),
      q("A man who reads books regularly ———", "A man who reads books regularly can enrich his mind."),
      q("Smoking is a habit which ———", "Smoking is a habit which is harmful to our health."),
      q("There is hardly any person who ———", "There is hardly any person who does not love flowers."),
      q("There is nobody who ———", "There is nobody who does not know the value of time."),
      rule("'Where' after a place and 'when' after a time.", "place + where + S + V · time + when + S + V"),
      q("This is the house where ———", "This is the house where I was born."),
      q("A graveyard is a place where ———", "A graveyard is a place where the dead are buried."),
      q("Rajshahi is the place where ———", "Rajshahi is the place where the best mangoes grow."),
      q("1971 is the year when ———", "1971 is the year when Bangladesh became independent."),
      q("I still remember the day when ———", "I still remember the day when I first went to school."),
      rule("'The reason why' and 'the way how' (or just 'the way').", "This is the reason why + S + V"),
      q("This is the reason why ———", "This is the reason why he was absent from school."),

      h("Noun clauses"),
      rule("A 'that' clause after 'It is certain / true / clear / a pity', 'The fact is', 'I know', 'I believe'.", "It is + adj + that + S + V · The fact is that + S + V"),
      q("It is certain that ———", "It is certain that he will come."),
      q("It is a pity that ———", "It is a pity that he failed."),
      q("The fact is that ———", "The fact is that he is innocent."),
      q("I believe that ———", "I believe that he will do well in life."),
      q("——— that he is honest.", "Everybody knows that he is honest."),
      rule("'What' means 'the thing which'. A 'what' clause can be the subject or the object of the sentence.", "What + S + V + V … · S + V + what + S + V"),
      q("What you say ———", "What you say is not true."),
      q("I do not know what ———", "I do not know what he wants."),
      q("What I have told you ———", "What I have told you is true."),
      rule("'Whether' / 'if' (meaning whether) for a yes-no question, and 'who', 'where', 'when', 'why', 'how' for other questions, placed inside another sentence.", "S + V + whether / wh-word + S + V"),
      q("I do not know whether ———", "I do not know whether he will come."),
      q("Tell me where ———", "Tell me where you live."),
      q("Nobody knows how ———", "Nobody knows how the fire broke out."),
      q("I wonder why ———", "I wonder why he did not come."),
      q("He asked me whether ———", "He asked me whether I had ever been to London."),
      q("I am not sure whether ———", "I am not sure whether he will come or not."),
      q("Do you know where ———", "Do you know where he lives?"),
      q("He will show me how ———", "He will show me how the machine works."),
      q("But most of our students don't know how ———", "But most of our students don't know how to speak English fluently."),

      h("It is … that / who (emphasis)"),
      rule("'It is / was' + the word to be stressed + 'that' / 'who' + the rest of the sentence. The tense of the rest follows the sense.", "It is / was + stressed part + that / who + rest of the sentence"),
      q("It was Rahim who ———", "It was Rahim who broke the glass."),
      q("It is education that ———", "It is education that makes a man conscious of his rights."),
      q("It was in 1971 that ———", "It was in 1971 that Bangladesh became independent."),
      q("It is hard work that ———", "It is hard work that makes a man successful."),
      q("It is English which ———", "It is English which is used as an international language."),
    ],
  },

  /* ─────────────────────── Exceptional cases ─────────────────────── */
  {
    id: "completing-sentences-exceptional",
    title: "Exceptional & Tricky Cases",
    body: [
      para("These are the cases where the usual rule bends, or where students most often lose the mark. Each one is set out with the reason, and where it helps, the wrong sentence is put against the right one."),

      h("Tense that breaks the sequence"),
      rule("A universal truth, a scientific fact or a proverb stays in the Present Indefinite even after a past main clause.", "S + said / taught + that + universal truth (V1)"),
      q("Our teacher told us that the earth ———", "Our teacher told us that the earth moves round the sun."),
      q("My father said that honesty ———", "My father said that honesty is the best policy."),
      wr("The teacher said that water boiled at 100°C.", "The teacher said that water boils at 100°C."),
      rule("A habit or a fact still true now may also stay in the present after a past main clause.", "S + said + that + S + V1 (still true)"),
      q("He said that he ———", "He said that he goes for a walk every morning."),
      rule("After 'than' and 'as' in a comparison, each clause keeps its own tense.", "S + V2 + comparative + than + S + V1"),
      q("He loved you more than ———", "He loved you more than he loves me."),
      q("She is better now than ———", "She is better now than she was last year."),
      rule("In 'It is … since', the 'since' clause is Past Indefinite, not Present Perfect.", "It is + time + since + S + V2"),
      wr("It is ten years since my grandfather has died.", "It is ten years since my grandfather died."),

      h("No 'will' in a time or 'if' clause — with three exceptions"),
      rule("A clause of time or condition about the future takes the Present Indefinite, not 'will'.", "When / If / Until + S + V1, S + will + V1"),
      wr("I shall wait until he will come.", "I shall wait until he comes."),
      wr("If it will rain, we shall stay at home.", "If it rains, we shall stay at home."),
      rule("Exception 1: 'if … will' is correct in a polite request, where 'will' means 'be willing to'.", "If + you + will + V1, S + will + V1"),
      q("If you will wait for a moment, ———", "If you will wait for a moment, I shall call the headmaster."),
      rule("Exception 2: 'if' meaning 'whether' begins a noun clause, not a condition, so 'will' is allowed.", "S + do not know + if (= whether) + S + will + V1"),
      q("I do not know if ———", "I do not know if he will come tomorrow."),
      rule("Exception 3: 'when' meaning 'the time at which' in a question or noun clause may take 'will'.", "S + V + when + S + will + V1"),
      q("Tell me when ———", "Tell me when you will return."),
      wr("He could help you provided that you will work hard.", "He could help you provided that you work hard."),

      h("Words that already carry 'not'"),
      rule("'Unless' = 'if not'. Never make the 'unless' clause negative.", "Unless + S + V (affirmative)"),
      wr("Unless you do not work hard, you will fail.", "Unless you work hard, you will fail."),
      rule("'Lest' = 'so that … not'. It takes 'should', never 'not'.", "lest + S + should + V1"),
      wr("Walk carefully lest you should not fall.", "Walk carefully lest you should fall."),
      rule("'Too … to' = 'so … that … not'. Never add 'not'.", "too + adj + to + V1"),
      wr("He is too weak to not walk.", "He is too weak to walk."),
      rule("'Until' / 'till' = 'up to the time when'. Its own clause stays affirmative.", "until + S + V (affirmative)"),
      wr("Wait here until I do not come back.", "Wait here until I come back."),
      rule("'Hardly', 'scarcely', 'seldom', 'never' and 'rarely' are negative. Do not add another 'not'.", "S + hardly + V (no second negative)"),
      wr("I could not hardly believe my eyes.", "I could hardly believe my eyes."),

      h("'Were' for every person"),
      rule("In an unreal 'if' clause, after 'I wish', 'as if' / 'as though' and 'would that', 'were' is used even with I, he, she, it and singular nouns.", "If / wish / as if + I / he / she / it + were"),
      q("If he were here, ———", "If he were here, he would help us."),
      q("She talks as if she ———", "She talks as if she were the headmistress."),
      wr("I wish I was a doctor.", "I wish I were a doctor."),
      rule("But when 'as if' shows a real likelihood, the ordinary present is used.", "It looks / seems + as if + S + V1 (likely)"),
      q("It looks as if ———", "It looks as if it is going to rain."),

      h("Present meaning, past form"),
      rule("'It is high time', 'would rather' + another subject, 'I wish' and 'as if' take a past form although the meaning is present.", "It is high time / would rather + S + V2"),
      wr("It is high time we take care of our environment.", "It is high time we took care of our environment."),
      wr("I would rather you go now.", "I would rather you went now."),
      rule("'It is time' without a subject takes an infinitive instead; both are correct but they are built differently.", "It is time + to + V1 · It is time + S + V2"),
      ex(["Infinitive", "It is time to start our journey."], ["Past form", "It is time we started our journey."]),

      h("Inverted structures"),
      rule("A negative or restrictive word at the start of a sentence brings the auxiliary before the subject: no sooner, hardly, scarcely, never, seldom, not only, not until, only then.", "Negative word + aux + S + V"),
      q("Never have I ———", "Never have I seen such a beautiful sight."),
      q("Seldom does he ———", "Seldom does he come to school late."),
      q("Only then did I ———", "Only then did I realise my mistake."),
      rule("The partners are fixed: 'no sooner' takes 'than'; 'hardly' and 'scarcely' take 'when' or 'before'. They are never interchanged.", "No sooner … than · Hardly / Scarcely … when / before"),
      wr("No sooner had he arrived when it began to rain.", "No sooner had he arrived than it began to rain."),
      wr("Hardly had he arrived than it began to rain.", "Hardly had he arrived when it began to rain."),
      rule("'It was not until … that' means 'only when … then'. The 'that' clause is affirmative.", "It was not until + time / clause + that + S + V2"),
      q("It was not until he lost his health ———", "It was not until he lost his health that he realised its value."),
      q("It was not until midnight ———", "It was not until midnight that he came home."),
      rule("Conditionals without 'if' also invert: 'Had I', 'Were I', 'Should you', 'Were it not for'.", "Had + S + V3, … · Were + S …, … · Should + S + V1, …"),
      wr("Had I would know it, I would have come.", "Had I known it, I would have come."),
      rule("'Had I' + a noun (no V3) is the verb 'have' in the sense of 'possess', not the Past Perfect. It is a second conditional, so the main clause takes would + V1, not would have + V3.", "Had I + noun = If I had + noun → would + V1"),
      wr("Had I the wings of a dove, I would have flown in the sky.", "Had I the wings of a dove, I would fly in the sky."),
      ex(["Possess (2nd)", "Had I money, I would buy a car. = If I had money …"], ["Past Perf. (3rd)", "Had I had money, I would have bought a car. = If I had had money …"]),

      h("No inversion inside a noun clause"),
      rule("A question placed inside another sentence loses its question order and its question mark (unless the whole sentence is a question).", "S + V + wh-word + S + V"),
      wr("Tell me where do you live.", "Tell me where you live."),
      wr("I do not know what is his name.", "I do not know what his name is."),
      q("Can you tell me what time ———", "Can you tell me what time it is?"),

      h("One joiner for one pair"),
      rule("'Though / although' never takes 'but'; 'because' never takes 'so'; 'as soon as' never takes 'then'. One conjunction joins one pair of clauses.", "Though + S + V, (yet) S + V"),
      wr("Though he is rich, but he is not happy.", "Though he is rich, (yet) he is not happy."),
      wr("Because he was ill, so he could not come.", "Because he was ill, he could not come."),
      rule("'In spite of' / 'because of' take a noun or gerund; 'though' / 'because' take a clause.", "In spite of + noun / V-ing · Though + S + V"),
      wr("In spite of he was ill, he came to school.", "In spite of being ill, he came to school."),
      wr("He could not come because of he was ill.", "He could not come because of his illness."),

      h("'To' + V-ing"),
      rule("When 'to' is a preposition (look forward to, be used to, with a view to, object to, be accustomed to, prefer … to), the verb after it is V-ing, not V1.", "preposition 'to' + V-ing"),
      wr("I am looking forward to meet you.", "I am looking forward to meeting you."),
      wr("He went there with a view to see his friend.", "He went there with a view to seeing his friend."),
      rule("'Used to' + V1 (a past habit) and 'be used to' + V-ing (accustomed to) mean different things.", "S + used to + V1 · S + am / is / are used to + V-ing"),
      ex(["Past habit", "He used to smoke, but now he has given it up."], ["Accustomed", "He is used to working at night."]),

      h("Agreement traps"),
      rule("In 'one of those … who', the verb agrees with the plural noun, not with 'one'.", "one of those + plural noun + who + plural verb"),
      q("He is one of those students who ———", "He is one of those students who always come to school in time."),
      rule("In 'one of the' + superlative, the noun is plural but the main verb agrees with 'one'.", "One of the + superlative + plural noun + singular verb"),
      q("One of the best players of the team ———", "One of the best players of the team is absent today."),
      rule("With 'either … or', 'neither … nor' and 'not only … but also', the verb agrees with the nearer subject; with 'as well as' and 'along with', it agrees with the first.", "A as well as B + verb agreeing with A"),
      q("The captain as well as the players ———", "The captain as well as the players was praised."),
      q("Neither the teacher nor the students ———", "Neither the teacher nor the students were present."),

      h("Verbs that change with the voice"),
      rule("'Make', 'see', 'hear' take V1 without 'to' in the active, but 'to' + V1 in the passive.", "make + object + V1 → be made + to + V1"),
      q("The boy was made ———", "The boy was made to apologise."),
      q("He was seen ———", "He was seen to enter the house."),
      rule("'Had better' and 'would rather' take V1 without 'to'.", "had better / would rather + V1"),
      wr("You had better to see a doctor.", "You had better see a doctor."),

      h("Participle at the start"),
      rule("A sentence that opens with V-ing, 'Having' + V3 or V3 must go on with the person who did that action as its subject. Otherwise the participle 'dangles' and the sentence says something absurd.", "V-ing / Having + V3 …, + the doer as subject + V"),
      wr("Walking along the road, a snake bit him.", "Walking along the road, he was bitten by a snake."),
      wr("Getting the money, happiness left the cobbler.", "Getting the money, the cobbler lost his happiness."),

      h("Verbs that do not take a 'that' clause"),
      rule("'Want', 'like' and 'wish' (for a thing) take an infinitive, not a 'that' clause with 'will'. Use 'hope' or 'expect' if you need a clause.", "S + want + to + V1 · S + hope + that + S + will + V1"),
      wr("We want that we will see good days.", "We want to see good days."),
      q("We hope that ———", "We hope that we shall see good days."),

      h("After 'suggest', 'insist', 'propose'"),
      rule("After 'suggest', 'propose', 'recommend', 'demand', 'insist' and 'It is necessary / important that', the verb is V1 for every person, or 'should' + V1. It does not change with the tense of the main verb.", "S + suggest / insist + that + S + (should) + V1"),
      q("The doctor suggested that he ———", "The doctor suggested that he (should) take complete rest."),
      q("The doctors suggest that everyone ———", "The doctors suggest that everyone be aware of this disease."),
      q("She insisted that he ———", "She insisted that he stay for dinner."),

      h("Slips seen even in printed answer keys"),
      note("Guides and keys sold in the market sometimes carry the very mistakes the examiner cuts marks for. Each of these was printed as an answer; learn the right form instead."),
      wr("No sooner had he reached the school than the bell rung.", "No sooner had he reached the school than the bell rang."),
      wr("Hardly had the assembly began when I reached college.", "Hardly had the assembly begun when I reached college."),
      wr("Zinia is so tired that he cannot study.", "Zinia is so tired that she cannot study."),
      wr("Five years passed since I had met you.", "Five years have passed since I met you."),
      wr("He asked me whether I had ever seen to London.", "He asked me whether I had ever been to London."),
      wr("Walk fast lest you might miss the train.", "Walk fast lest you should miss the train."),
    ],
  },

  /* ─────────────────────────── Solved sets ─────────────────────────── */
  {
    id: "completing-sentences-proverbs-nonfinites",
    title: "Proverbs, Non-finites & Subjects",
    body: [
      para("A few items do not turn on a conjunction at all. The given part may be the first half of a well-known proverb, a participle or infinitive at the start of the sentence, or a clause that is itself the subject. These are easy marks once the pattern is known."),

      h("Proverbs and sayings"),
      rule("When the given part is the first half of a proverb, complete it with the proverb exactly as it is known. Proverbs are universal truths and stay in the Present Indefinite.", "first half of the proverb + its fixed second half"),
      q("United we stand, ———", "United we stand, divided we fall."),
      q("Where there is a will, ———", "Where there is a will, there is a way."),
      q("As you sow, ———", "As you sow, so you reap."),
      q("Only the wearer knows ———", "Only the wearer knows where the shoe pinches."),
      q("A stitch in time ———", "A stitch in time saves nine."),
      q("There goes a proverb that time and tide ———", "There goes a proverb that time and tide wait for none."),
      q("All that glitters ———", "All that glitters is not gold."),
      q("Blessings are not valued till ———", "Blessings are not valued till they are gone."),
      q("Look before ———", "Look before you leap."),
      q("A friend in need ———", "A friend in need is a friend indeed."),
      q("Man proposes, ———", "Man proposes, God disposes."),
      q("Slow and steady ———", "Slow and steady wins the race."),
      q("Empty vessels ———", "Empty vessels sound much."),
      q("There is a proverb that ———", "There is a proverb that health is wealth."),

      h("Present participle at the start"),
      rule("A sentence may open with V-ing when two actions are done by the same person, one after the other or at the same time. The missing main clause must begin with that person as its subject.", "V-ing + object, S (the doer) + V"),
      q("Finishing the work, ———", "Finishing the work, I went to bed."),
      q("Seeing the police, ———", "Seeing the police, the thief ran away."),
      q("Getting the huge amount of money, ———", "Getting the huge amount of money, the cobbler lost his peace of mind."),
      q("Being ill, ———", "Being ill, he could not attend the class."),
      rule("'Having' + V3 makes it clear that the first action was complete before the second began.", "Having + V3, S + V2"),
      q("Having finished my homework, ———", "Having finished my homework, I went out to play."),
      q("Having lost all his money, ———", "Having lost all his money, he returned home."),
      rule("When the subjects differ, the participle keeps its own subject in front of it — the absolute phrase.", "Noun + V-ing / having + V3, S + V"),
      q("The weather being fine, ———", "The weather being fine, we went out for a walk."),
      q("The sun having set, ———", "The sun having set, we returned home."),

      h("Infinitive, gerund and clause as subject"),
      rule("An infinitive (to + V1), a gerund (V-ing) or a whole clause (that / what / whether …) can be the subject of the sentence. The missing part is then the main verb and what follows it, and the verb is singular.", "To + V1 / V-ing / That-clause + singular verb …"),
      q("To walk in the morning ———", "To walk in the morning is good for health."),
      q("Walking in the morning ———", "Walking in the morning keeps the body fit."),
      q("To err ———", "To err is human."),
      q("That he is a good teacher ———", "That he is a good teacher is known to all."),
      q("What is done ———", "What is done cannot be undone."),
      q("Whether he will come or not ———", "Whether he will come or not is uncertain."),
      q("Controlling price hike ———", "Controlling price hike is really very difficult."),

      h("See, hear, find + object + V-ing or V1"),
      rule("After 'see', 'hear', 'watch', 'notice', 'feel' and 'find' + object, use V-ing for an action in progress and V1 (without 'to') for a complete action.", "S + see / hear + object + V-ing / V1"),
      q("I saw my mother ———", "I saw my mother cooking in the kitchen."),
      q("I heard him ———", "I heard him singing a song."),
      q("We saw the boy ———", "We saw the boy cross the road."),
      q("I found him ———", "I found him sleeping on the sofa."),

      h("When the beginning is missing"),
      rule("Read the given end first and let it decide the structure of the missing beginning: the tense, the conditional type, the subject.", "——— + given end"),
      q("———, I walked on foot.", "As I could not find a rickshaw, I walked on foot."),
      q("——— before you come.", "I shall have finished my work before you come."),
      q("——— so that he could buy a book.", "He saved money so that he could buy a book."),
      q("——— lest he should fall.", "The old man walked carefully lest he should fall."),
      q("——— you must be successful.", "If you make proper use of time, you must be successful."),
      q("——— than to beg.", "It is better to die than to beg."),
    ],
  },

  {
    id: "completing-sentences-set-1",
    title: "Practice Set 1",
    prompt: PROMPT,
    body: [
      para("(a) It is high time ——— (b) Had I been a bird, ——— (c) No sooner had the teacher entered the class ——— (d) He walked fast lest ——— (e) The man is too weak ——— (f) Though he is poor, ——— (g) I wish ——— (h) If you read attentively, ——— (i) He talks as if ——— (j) The more you practise, ———"),
      h("Answers"),
      ex(["(a)", "It is high time we took proper steps to stop environmental pollution."], ["Why", "'It is high time' + subject takes the Past Indefinite (V2)."]),
      ex(["(b)", "Had I been a bird, I would have flown across the sky."], ["Why", "'Had I been' is a third conditional without 'if': would have + V3."]),
      ex(["(c)", "No sooner had the teacher entered the class than the students stood up."], ["Why", "'No sooner had' + V3 is always followed by 'than' + V2."]),
      ex(["(d)", "He walked fast lest he should miss the train."], ["Why", "'Lest' takes 'should' + V1 and no 'not'."]),
      ex(["(e)", "The man is too weak to walk without help."], ["Why", "'Too' + adjective + 'to' + V1; 'too' is already negative."]),
      ex(["(f)", "Though he is poor, he is honest."], ["Why", "A contrasting main clause, with no 'but' after 'though'."]),
      ex(["(g)", "I wish I could go abroad for higher studies."], ["Why", "A present wish takes 'could' + V1 or a past form."]),
      ex(["(h)", "If you read attentively, you will do well in the examination."], ["Why", "'If' + Present Indefinite takes shall / will + V1 (first conditional)."]),
      ex(["(i)", "He talks as if he were the leader of the team."], ["Why", "'As if' with a present verb and an unreal idea takes 'were' for every person."]),
      ex(["(j)", "The more you practise, the better you will write."], ["Why", "'The' + comparative in both halves."]),
    ],
  },
  {
    id: "completing-sentences-set-2",
    title: "Practice Set 2",
    prompt: PROMPT,
    body: [
      para("(a) Would you mind ——— (b) It is ten years since ——— (c) Unless you work hard, ——— (d) I prefer reading books ——— (e) He is so honest that ——— (f) By the time we reached the station, ——— (g) Not only the students ——— (h) I would rather die ——— (i) What you say ——— (j) We eat so that ———"),
      h("Answers"),
      ex(["(a)", "Would you mind lending me your pen?"], ["Why", "'Would you mind' takes V-ing, and the sentence is a question."]),
      ex(["(b)", "It is ten years since my grandfather died."], ["Why", "'It is … since' takes the Past Indefinite in the 'since' clause."]),
      ex(["(c)", "Unless you work hard, you will not shine in life."], ["Why", "The 'unless' clause stays affirmative; the main clause is future."]),
      ex(["(d)", "I prefer reading books to watching television."], ["Why", "'Prefer' + V-ing + 'to' + V-ing; here 'to' is a preposition."]),
      ex(["(e)", "He is so honest that everybody believes him."], ["Why", "'So' + adjective + 'that' + a clause of result in the same tense."]),
      ex(["(f)", "By the time we reached the station, the train had left."], ["Why", "'By the time' + V2 takes a Past Perfect main clause."]),
      ex(["(g)", "Not only the students but also the teacher was present."], ["Why", "'Not only … but also' — the verb agrees with the nearer subject, 'the teacher'."]),
      ex(["(h)", "I would rather die than beg."], ["Why", "'Would rather' + V1 + 'than' + V1."]),
      ex(["(i)", "What you say is not true."], ["Why", "A 'what' clause as subject is singular and needs its own main verb."]),
      ex(["(j)", "We eat so that we may live."], ["Why", "'So that' in the present takes may / can + V1."]),
    ],
  },
  {
    id: "completing-sentences-set-3",
    title: "Practice Set 3",
    prompt: PROMPT,
    body: [
      para("(a) While I was crossing the road, ——— (b) The patient had died before ——— (c) If I were you, ——— (d) In spite of his illness, ——— (e) Since you are tired, ——— (f) It is no use ——— (g) This is the house where ——— (h) Either you or your brother ——— (i) He was made ——— (j) Scarcely had the thief seen the police ———"),
      h("Answers"),
      ex(["(a)", "While I was crossing the road, I saw an accident."], ["Why", "'While' + Past Continuous; the short action in the Past Indefinite."]),
      ex(["(b)", "The patient had died before the doctor came."], ["Why", "The earlier action is Past Perfect, the later one after 'before' is Past Indefinite."]),
      ex(["(c)", "If I were you, I would not make such a mistake."], ["Why", "Second conditional: 'were' + would + V1."]),
      ex(["(d)", "In spite of his illness, he attended the examination."], ["Why", "'In spite of' + noun, then a contrasting main clause."]),
      ex(["(e)", "Since you are tired, you may take some rest."], ["Why", "'Since' here gives the cause, followed by a sensible result."]),
      ex(["(f)", "It is no use crying over spilt milk."], ["Why", "'It is no use' takes V-ing."]),
      ex(["(g)", "This is the house where I was born."], ["Why", "'Where' after a place begins a relative clause; 'born' is always passive."]),
      ex(["(h)", "Either you or your brother has broken the glass."], ["Why", "The verb agrees with the nearer subject 'your brother', so 'has'."]),
      ex(["(i)", "He was made to do the work against his will."], ["Why", "'Make' in the passive takes 'to' + V1."]),
      ex(["(j)", "Scarcely had the thief seen the police when he ran away."], ["Why", "'Scarcely had' + V3 is followed by 'when' + V2, never 'than'."]),
    ],
  },
  {
    id: "completing-sentences-set-4",
    title: "Practice Set 4: Exceptional",
    prompt: PROMPT,
    body: [
      para("(a) I am looking forward to ——— (b) The teacher told us that honesty ——— (c) Hardly had we reached the stadium ——— (d) You had better ——— (e) It was not until he lost his health ——— (f) But for your help, ——— (g) He is one of those students who ——— (h) Tell me where ——— (i) If you will wait for a moment, ——— (j) It looks as if ———"),
      h("Answers"),
      ex(["(a)", "I am looking forward to meeting you at the book fair."], ["Why", "'To' in 'look forward to' is a preposition, so V-ing follows."]),
      ex(["(b)", "The teacher told us that honesty is the best policy."], ["Why", "A proverb is a universal truth and stays in the present after 'told'."]),
      ex(["(c)", "Hardly had we reached the stadium when it started raining."], ["Why", "'Hardly had' + V3 takes 'when' + V2."]),
      ex(["(d)", "You had better consult a doctor at once."], ["Why", "'Had better' takes V1 without 'to'."]),
      ex(["(e)", "It was not until he lost his health that he realised its value."], ["Why", "'It was not until …' is completed by an affirmative 'that' clause."]),
      ex(["(f)", "But for your help, I would have failed."], ["Why", "'But for' = 'if it had not been for', so the main clause is would have + V3."]),
      ex(["(g)", "He is one of those students who always come to school in time."], ["Why", "'Who' refers to the plural 'students', so the verb is plural: 'come'."]),
      ex(["(h)", "Tell me where you live."], ["Why", "A question inside a sentence keeps statement order: subject before verb."]),
      ex(["(i)", "If you will wait for a moment, I shall call the headmaster."], ["Why", "'If you will' is a polite request — the one case where 'will' follows 'if'."]),
      ex(["(j)", "It looks as if it is going to rain."], ["Why", "'As if' about a real likelihood takes the ordinary present, not 'were'."]),
    ],
  },
  /* ──────────────────────── Board questions ──────────────────────── */
  {
    id: "completing-sentences-board-2025",
    title: "Board Questions 2025",
    prompt: PROMPT,
    body: [
      para("The questions set by the education boards in the SSC examination of 2025, each solved with the reason for the answer. Some boards set five separate structures; others set five sentences on one topic."),
      h("Dhaka Board 2025 — Health"),
      para("(a) There is a proverb that ——— (b) Unless you have good health, ——— (c) A healthy poor man is happier than ——— (d) You may have a lot of wealth but ——— (e) In order to have good health, ———"),
      ex(["(a)", "There is a proverb that health is wealth."], ["Why", "The proverb itself completes the 'that' clause; a proverb stays in the present."]),
      ex(["(b)", "Unless you have good health, you cannot enjoy life."], ["Why", "'Unless' clause is affirmative; the main clause is negative in sense."]),
      ex(["(c)", "A healthy poor man is happier than a sick rich man."], ["Why", "'Happier than' compares two like things: a poor man with a rich man."]),
      ex(["(d)", "You may have a lot of wealth but you cannot be happy without health."], ["Why", "'But' introduces the contrasting idea, kept to the topic of health."]),
      ex(["(e)", "In order to have good health, you must follow the rules of health."], ["Why", "'In order to' gives the purpose; the main clause says what must be done."]),
      h("Rajshahi Board 2025"),
      para("(a) Had I the wings of a bird, ——— (b) If he had been seen by me, ——— (c) It is high time ——— (d) No sooner had we reached the school ——— (e) The more you read, ———"),
      ex(["(a)", "Had I the wings of a bird, I would fly in the sky."], ["Why", "'Had' here means 'possessed': If I had the wings … — a second conditional, so would + V1."]),
      ex(["(b)", "If he had been seen by me, I would have called him."], ["Why", "If + had + V3 (here passive) takes would have + V3."]),
      ex(["(c)", "It is high time we left the house."], ["Why", "'It is high time' + subject takes V2."]),
      ex(["(d)", "No sooner had we reached the school than the class started."], ["Why", "'No sooner had' + V3 … 'than' + V2."]),
      ex(["(e)", "The more you read, the more you learn."], ["Why", "'The' + comparative in both halves."]),
      h("Dinajpur Board 2025"),
      para("(a) That he is a good teacher ——— (b) He speaks as if ——— (c) He ran fast lest ——— (d) Only the wearer knows ——— (e) Had I been a billionaire, ———"),
      ex(["(a)", "That he is a good teacher is known to all."], ["Why", "The 'that' clause is the subject; it needs a singular main verb."]),
      ex(["(b)", "He speaks as if he knew everything."], ["Why", "'As if' after a present verb, for an unreal idea, takes V2."]),
      ex(["(c)", "He ran fast lest he should miss the train."], ["Why", "'Lest' + should + V1, no 'not'."]),
      ex(["(d)", "Only the wearer knows where the shoe pinches."], ["Why", "The proverb is completed exactly as it is known."]),
      ex(["(e)", "Had I been a billionaire, I would have helped the poor."], ["Why", "'Had I been' is If I had been — a third conditional: would have + V3."]),
      h("Sylhet Board 2025"),
      para("(a) Hardly had we heard the news ——— (b) Had I the wings of a bird, ——— (c) Walk fast lest ——— (d) He disturbed me while ——— (e) It is high time ———"),
      ex(["(a)", "Hardly had we heard the news when we rushed to the spot."], ["Why", "'Hardly had' + V3 takes 'when' + V2."]),
      ex(["(b)", "Had I the wings of a bird, I would fly to my mother."], ["Why", "'Had' = possessed: second conditional, would + V1."]),
      ex(["(c)", "Walk fast lest you should miss the train."], ["Why", "'Lest' takes 'should' — not 'might', and never 'not'."]),
      ex(["(d)", "He disturbed me while I was working."], ["Why", "'While' + Past Continuous for the longer action."]),
      ex(["(e)", "It is high time we stopped corruption."], ["Why", "'It is high time' + subject + V2."]),
      h("Jashore Board 2025 — Truthfulness"),
      para("(a) Those who always speak the truth ——— (b) One cannot command the respect of others unless ——— (c) Nowadays people lie as if ——— (d) Though a liar sometimes speaks the truth, ——— (e) So, it is a wise decision ———"),
      ex(["(a)", "Those who always speak the truth are respected by all."], ["Why", "'Those who …' is a plural subject and needs a plural main verb."]),
      ex(["(b)", "One cannot command the respect of others unless one is honest."], ["Why", "'One' is repeated as the subject; the 'unless' clause stays affirmative."]),
      ex(["(c)", "Nowadays people lie as if it were the easiest thing in the world."], ["Why", "'As if' + unreal idea: 'were' for every person."]),
      ex(["(d)", "Though a liar sometimes speaks the truth, people hardly believe him."], ["Why", "Contrasting main clause after 'though', with no 'but'."]),
      ex(["(e)", "So, it is a wise decision to stick to the truth always."], ["Why", "'It is' + noun + infinitive: the infinitive states what the decision is."]),
      h("Barishal Board 2025 — Learning English"),
      para("(a) It is English which ——— (b) But most of our students don't know how ——— (c) If a student wants to do well in English, ——— (d) Unless the students practise it, ——— (e) It is high time ———"),
      ex(["(a)", "It is English which is used as an international language."], ["Why", "'It is … which' stresses 'English'; the verb agrees with it."]),
      ex(["(b)", "But most of our students don't know how to speak English fluently."], ["Why", "'Know how' + infinitive."]),
      ex(["(c)", "If a student wants to do well in English, he must practise it every day."], ["Why", "First conditional: present in the 'if' clause, a modal + V1 in the main clause."]),
      ex(["(d)", "Unless the students practise it, they will not improve their English."], ["Why", "'Unless' = if … not; the main clause is future."]),
      ex(["(e)", "It is high time the students started practising English regularly."], ["Why", "'It is high time' + subject + V2."]),
      h("Cumilla Board 2025 — Illiteracy"),
      para("(a) Everyone knows that ——— (b) We should try our level best ——— (c) In order to eradicate illiteracy, ——— (d) Conscious people should come forward with a view to ——— (e) Our country would be developed if ———"),
      ex(["(a)", "Everyone knows that illiteracy is a curse."], ["Why", "A 'that' clause gives what is known; a general truth stays present."]),
      ex(["(b)", "We should try our level best to remove illiteracy from our country."], ["Why", "'Try' + infinitive."]),
      ex(["(c)", "In order to eradicate illiteracy, the government should take effective steps."], ["Why", "'In order to' gives the purpose; the main clause gives the action."]),
      ex(["(d)", "Conscious people should come forward with a view to helping the illiterate."], ["Why", "'With a view to' + V-ing, since 'to' is a preposition."]),
      ex(["(e)", "Our country would be developed if all the people were educated."], ["Why", "'Would' in the main clause asks for a second conditional: if + V2 / were."]),
    ],
  },
  {
    id: "completing-sentences-board-earlier",
    title: "Board Questions 2015–2023",
    prompt: PROMPT,
    body: [
      para("Questions from earlier SSC examinations. The same structures and the same topics keep coming back, so these are worth working through in full."),
      h("Dhaka Board 2020"),
      para("(a) No sooner had we reached the school ——— (b) Unless you study attentively ——— (c) Scarcely had the party begun ——— (d) If I had known his mobile number ——— (e) Work hard provided that ———"),
      ex(["(a)", "No sooner had we reached the school than the bell rang."], ["Why", "'No sooner had' + V3 … 'than' + V2 ('rang', not 'rung')."]),
      ex(["(b)", "Unless you study attentively, you will fail in the examination."], ["Why", "'Unless' clause affirmative, main clause future."]),
      ex(["(c)", "Scarcely had the party begun when it started raining."], ["Why", "'Scarcely had' + V3 takes 'when' + V2."]),
      ex(["(d)", "If I had known his mobile number, I would have called him."], ["Why", "Third conditional: had + V3 … would have + V3."]),
      ex(["(e)", "Work hard provided that you want to succeed in life."], ["Why", "'Provided that' = only if; the clause is in the present, not 'will'."]),
      h("Chattogram Board 2020"),
      para("(a) He asked me whether ——— (b) Had I the wings of a dove ——— (c) He could help you provided that ——— (d) Hardly had the bell rung ——— (e) We must look before we leap lest ———"),
      ex(["(a)", "He asked me whether I had ever been to London."], ["Why", "After the past 'asked', the reported question moves back to the Past Perfect; 'been to', not 'seen to'."]),
      ex(["(b)", "Had I the wings of a dove, I would fly in the sky."], ["Why", "'Had' = possessed: second conditional, would + V1."]),
      ex(["(c)", "He could help you provided that you work hard."], ["Why", "No 'will' after 'provided that'."]),
      ex(["(d)", "Hardly had the bell rung when the class started."], ["Why", "'Hardly had' + V3 … 'when' + V2."]),
      ex(["(e)", "We must look before we leap lest we should repent later."], ["Why", "The 'lest' clause states what we fear, with 'should'."]),
      h("Chattogram Board 2023 — The Happy Cobbler"),
      para("(a) A cobbler was happy ——— (b) He had a neighbour who ——— (c) The neighbour wanted to help him ——— (d) Getting the huge amount of money, ——— (e) But if he had not taken the money from his neighbour, ———"),
      ex(["(a)", "A cobbler was happy though he was poor."], ["Why", "A contrast clause keeps to the story and the past tense."]),
      ex(["(b)", "He had a neighbour who was very rich."], ["Why", "'Who' refers to 'a neighbour'; past tense to match 'had'."]),
      ex(["(c)", "The neighbour wanted to help him by giving him some money."], ["Why", "'By' + V-ing gives the means."]),
      ex(["(d)", "Getting the huge amount of money, the cobbler lost his peace of mind."], ["Why", "The participle needs 'the cobbler' as the subject of the main clause."]),
      ex(["(e)", "But if he had not taken the money from his neighbour, he would have led a happy life."], ["Why", "Third conditional: would have + V3."]),
      h("Dhaka Board 2017 — Value of Time"),
      para("(a) There goes a proverb that ——— (b) Though lost wealth can be regained by hard work, ——— (c) Time is so valuable that ——— (d) Those who waste time ——— (e) ——— you must be successful."),
      ex(["(a)", "There goes a proverb that time and tide wait for none."], ["Why", "The proverb itself, in the present."]),
      ex(["(b)", "Though lost wealth can be regained by hard work, lost time can never be regained."], ["Why", "The contrast: wealth can come back, time cannot."]),
      ex(["(c)", "Time is so valuable that once it is lost, it is lost for ever."], ["Why", "'So' + adjective + 'that' + result."]),
      ex(["(d)", "Those who waste time cannot shine in life."], ["Why", "Plural subject 'Those who …' with a main verb."]),
      ex(["(e)", "If you make proper use of time, you must be successful."], ["Why", "The gap is at the start: a condition that leads to the given result."]),
      h("Dhaka Board 2016 — Smoking"),
      para("(a) Smoking is a habit which ——— (b) Many people go on smoking though ——— (c) If we smoke, ——— (d) People can't give up smoking easily because ——— (e) So, attempts must be taken ———"),
      ex(["(a)", "Smoking is a habit which is harmful to our health."], ["Why", "'Which' refers to 'a habit' and needs its own verb, 'is'."]),
      ex(["(b)", "Many people go on smoking though they know its harmful effects."], ["Why", "A contrast clause with a subject and a verb."]),
      ex(["(c)", "If we smoke, we shall suffer from many diseases."], ["Why", "First conditional: present … shall / will + V1."]),
      ex(["(d)", "People can't give up smoking easily because they become addicted to it."], ["Why", "'Because' + the reason as a full clause."]),
      ex(["(e)", "So, attempts must be taken to make people aware of its harmful effects."], ["Why", "An infinitive of purpose completes the passive 'must be taken'."]),
      h("Dhaka Board 2015 — Trees"),
      para("(a) Many people cut trees indiscriminately but ——— (b) Trees cause rainfall which ——— (c) If we cut trees at random, ——— (d) Trees supply oxygen which ——— (e) Since trees help us in many ways, ———"),
      ex(["(a)", "Many people cut trees indiscriminately but do not plant new ones."], ["Why", "'But' joins a contrasting action by the same subject."]),
      ex(["(b)", "Trees cause rainfall which is essential for agriculture."], ["Why", "'Which' refers to 'rainfall' (singular): 'is'."]),
      ex(["(c)", "If we cut trees at random, the country will lose its ecological balance."], ["Why", "First conditional."]),
      ex(["(d)", "Trees supply oxygen which is essential for our life."], ["Why", "'Which' refers to 'oxygen'."]),
      ex(["(e)", "Since trees help us in many ways, we should plant more trees."], ["Why", "'Since' gives the reason; the main clause the conclusion."]),
      h("Cumilla Board 2017 — Our Country"),
      para("(a) This is Bangladesh ——— (b) The people of Bangladesh are friendly though ——— (c) When anyone falls in danger, others ——— (d) We love and help one another as ——— (e) We work seriously in order that Bangladesh ———"),
      ex(["(a)", "This is Bangladesh where I was born."], ["Why", "'Where' after a place; 'born' is always passive."]),
      ex(["(b)", "The people of Bangladesh are friendly though they are poor."], ["Why", "A contrast with 'friendly'."]),
      ex(["(c)", "When anyone falls in danger, others come forward to help him."], ["Why", "A general habit: Present Indefinite in both clauses."]),
      ex(["(d)", "We love and help one another as if we were members of the same family."], ["Why", "'As if' + unreal idea: 'were'."]),
      ex(["(e)", "We work seriously in order that Bangladesh may prosper."], ["Why", "'In order that' in the present takes may / can + V1."]),
    ],
  },
];
