// components/prepositionData.ts
//
// Preposition, one piece per family of uses: time, place and direction, the
// other relations (agent, instrument, cause, material), the fixed word +
// preposition pairs the board calls "appropriate prepositions", and the words
// that change their preposition with their meaning. Each piece gives the
// rules in order and works each rule through examples, then board-style
// passages are solved gap by gap with the reason for each answer.

import type { Block, Piece } from "./englishData";

const h = (text: string): Block => ({ type: "heading", text });
const rule = (text: string, formula?: string): Block => ({
  type: "rule",
  text,
  formula,
});
const note = (text: string): Block => ({ type: "note", label: "Note", text });
// One example: each argument is a [label, sentence] pair.
const ex = (...lines: [string, string][]): Block => ({
  type: "example",
  lines: lines.map(([label, text]) => ({ label, text })),
});
// The gap as set, the preposition that fills it and why.
const q = (given: string, answer: string, why: string): Block =>
  ex(["Given", given], ["Answer", answer], ["Why", why]);
// One word and the preposition it always takes, shown in a sentence.
const pair = (phrase: string, sentence: string): Block =>
  ex([phrase, sentence]);
const para = (text: string): Block => ({ type: "para", text });

const PROMPT = "Fill in the blanks with appropriate prepositions.";

export const preposition: Piece[] = [
  /* ───────────────────────── Introduction ───────────────────────── */
  {
    id: "preposition-introduction",
    title: "Introduction",
    body: [
      para("A preposition is a word placed before a noun or a pronoun to show how that noun or pronoun is related to another word in the sentence. In 'The book is on the table', 'on' shows where the book is in relation to the table. Change the preposition and the relation changes: the book can be under, beside, near or off the table. The word 'preposition' itself means 'placed before' (pre + position)."),
      para("The noun or pronoun that comes after a preposition is called its object, and a pronoun there always takes the objective form: 'with him', 'between you and me', 'for them' — never 'with he' or 'between you and I'."),
      h("Kinds of prepositions"),
      ex(["Simple", "at · by · for · from · in · of · off · on · out · to · up · with"]),
      ex(["Compound", "about · above · across · along · among · before · behind · below · beside · between · beyond · inside · into · upon · within · without"]),
      ex(["Double", "into · onto · from behind · from under · out of · from among"], ["In a sentence", "A cat came out from under the bed."]),
      ex(["Phrase", "according to · because of · by dint of · by means of · in front of · in spite of · instead of · on account of · owing to · with a view to"], ["In a sentence", "He succeeded by dint of hard work."]),
      ex(["Participle", "concerning · considering · during · notwithstanding · pending · regarding"], ["In a sentence", "Considering his age, he did the work well."]),
      h("What can follow a preposition"),
      rule("A noun or a noun phrase.", "preposition + noun"),
      ex(["Example", "He went to school."], ["Example", "She lives in a small village."]),
      rule("A pronoun in the objective form: me, us, you, him, her, it, them, whom.", "preposition + object pronoun"),
      ex(["Wrong", "This is between you and I."], ["Right", "This is between you and me."]),
      rule("A verb only in the -ing form (a gerund), never the base form.", "preposition + V-ing"),
      ex(["Wrong", "He is fond of read books."], ["Right", "He is fond of reading books."]),
      ex(["Example", "She left without saying goodbye."], ["Example", "I am looking forward to meeting you."]),
      rule("Sometimes a whole clause beginning with what, where, how or whether.", "preposition + wh-clause"),
      ex(["Example", "Pay attention to what the teacher says."], ["Example", "It depends on whether he comes."]),
      h("Preposition or adverb?"),
      para("The same word can be a preposition or an adverb. It is a preposition only when it has an object after it. In 'He climbed up the tree', 'up' has the object 'the tree', so it is a preposition. In 'He stood up', 'up' has no object, so it is an adverb."),
      ex(["Preposition", "The boy ran across the road."], ["Adverb", "The boy ran across."]),
      ex(["Preposition", "Stay in the room."], ["Adverb", "Please come in."]),
      h("How to solve the question"),
      para("1. Read the whole passage once before filling any gap, so you know what it is about and which tense it is in."),
      para("2. Look at the word just before the gap. Many verbs, adjectives and nouns always take one fixed preposition: afraid of, interested in, depend on, fond of. If the word before the gap is one of these, the answer is already decided."),
      para("3. If there is no fixed pair, look at the word after the gap. Is it a time (at 10 o'clock, on Friday, in 1971), a place (at the station, in Dhaka, on the table), a person who does the action (by him), a tool (with a knife) or a cause (of cholera)?"),
      para("4. Check the meaning: 'into' for movement inside, 'between' for two and 'among' for more than two, 'since' for a point of time and 'for' for a length of time."),
      para("5. Read the finished sentence aloud in your head. The right preposition almost always sounds right."),
      note("Some verbs take no preposition at all: enter, reach, discuss, resemble, marry, attack, order, answer, obey. A gap after one of these is usually a trap — see the piece 'No Preposition & Common Errors'."),
    ],
  },

  /* ──────────────────────────── Time ──────────────────────────── */
  {
    id: "preposition-time",
    title: "Prepositions of Time",
    body: [
      para("Time prepositions are the ones the board sets most often, because each of them is tied to a particular kind of time word. Learn which kind goes with which and most gaps fill themselves."),
      h("At, on and in"),
      rule("'At' is used for an exact point of time: a clock time, and the fixed points noon, midnight, night, dawn, sunrise, sunset, and the festivals taken as a whole.", "at + clock time · noon · night · dawn · sunset · Eid"),
      ex(["Example", "The train leaves at 10 o'clock."], ["Example", "We had lunch at noon."]),
      ex(["Example", "The moon shines at night."], ["Example", "The farmers go to the field at dawn."]),
      ex(["Example", "We visit our grandparents at Eid."], ["Example", "He came at the end of the meeting."]),
      rule("'On' is used for a day or a date, and for a part of a named day.", "on + day · date · a named day's morning / evening"),
      ex(["Example", "We have no class on Friday."], ["Example", "Victory Day is observed on 16 December."]),
      ex(["Example", "He was born on 17 March 1920."], ["Example", "She came on the morning of 21 February."]),
      ex(["Example", "They met on Independence Day."], ["Example", "The shop is closed on holidays."]),
      rule("'In' is used for a longer period: a part of the day, a month, a season, a year, a decade or a century.", "in + the morning / evening · month · season · year · century"),
      ex(["Example", "I get up early in the morning."], ["Example", "Bangladesh became independent in 1971."]),
      ex(["Example", "It rains heavily in the rainy season."], ["Example", "Mangoes ripen in June."]),
      ex(["Example", "He lived in the nineteenth century."], ["Example", "She was born in the spring of 2008."]),
      note("'In the morning', but 'on the morning of 26 March': once the morning belongs to a particular day, the preposition of the day takes over. 'At night', but 'in the night' when you mean during one particular night: 'I woke up in the night.'"),
      note("No preposition before this, that, next, last, every, each, today, tomorrow, yesterday or tonight: 'I met him last Monday', 'She will come next week', 'We play every day'."),

      h("Since and for"),
      rule("'Since' is used for a point of time from which an action has gone on up to now. It goes with the perfect tenses.", "Present Perfect / Present Perfect Continuous + since + point of time"),
      ex(["Example", "He has been ill since Monday."], ["Example", "I have known her since 2015."]),
      ex(["Example", "It has been raining since morning."], ["Example", "They have lived here since their childhood."]),
      rule("'For' is used for a length of time: how long, not from when.", "for + length of time"),
      ex(["Example", "He has been ill for three days."], ["Example", "I waited for two hours."]),
      ex(["Example", "The war lasted for nine months."], ["Example", "She has been teaching for ten years."]),
      note("Test: if you can ask 'from when?', use since; if you can ask 'how long?', use for. 'Since two hours' is always wrong."),

      h("From … to, and from … till"),
      rule("'From' marks the beginning of a period, and 'to', 'till' or 'until' its end.", "from + start … to / till + end"),
      ex(["Example", "The shop is open from 9 a.m. to 8 p.m."], ["Example", "We study from morning till evening."]),
      ex(["Example", "The fair will continue from 1 to 28 February."]),

      h("By, till and until"),
      rule("'By' means 'not later than': the action will be over at or before that time.", "by + deadline"),
      ex(["Example", "You must finish the work by Friday."], ["Example", "I shall be back by 5 o'clock."]),
      ex(["Example", "By the time we arrived, the train had left."]),
      rule("'Till' and 'until' mean 'up to that time': the action goes on and stops then.", "till / until + the time it stops"),
      ex(["Example", "Wait here till I come back."], ["Example", "He worked until midnight."]),
      ex(["Example", "The shop remains open till 10 p.m."]),

      h("In, within, after and during"),
      rule("'In' with a period of future time means 'at the end of' that period.", "in + period = at the end of it"),
      ex(["Example", "I shall come back in an hour."], ["Example", "The building will be finished in two years."]),
      rule("'Within' means 'before the end of' that period, not beyond it.", "within + period = before it ends"),
      ex(["Example", "You must return the book within a week."], ["Example", "He finished the test within thirty minutes."]),
      rule("'After' shows that one thing follows another in time; 'before' shows it comes earlier.", "after / before + time or event"),
      ex(["Example", "We went out after lunch."], ["Example", "Wash your hands before eating."]),
      ex(["Example", "He came back after a long time."], ["Example", "She reached school before the bell rang."]),
      rule("'During' means 'all through' or 'at some time in' a period or an event. It is followed by a noun, never by a clause.", "during + noun"),
      ex(["Example", "Do not talk during the class."], ["Example", "We went to Cox's Bazar during the winter vacation."]),
      ex(["Wrong", "During I was reading, the light went out."], ["Right", "While I was reading, the light went out. / During my reading, the light went out."]),

      h("Other time prepositions"),
      rule("'About' or 'around' for an approximate time; 'past' and 'to' in telling the time; 'per' or 'a' for every.", "about · around · past · to"),
      ex(["Example", "He came at about 7 o'clock."], ["Example", "It is ten past nine."]),
      ex(["Example", "It is a quarter to eight."], ["Example", "The shop remains open throughout the year."]),
    ],
  },

  /* ─────────────────── Place & Direction ─────────────────── */
  {
    id: "preposition-place-direction",
    title: "Place & Direction",
    body: [
      para("A preposition of place tells where something is; a preposition of direction tells where something is going. Most mistakes come from using a word of place where the sentence shows movement: 'He jumped in the river' means he was already in it and jumped about; 'He jumped into the river' means he went from outside to inside."),
      h("At, in and on"),
      rule("'At' is used for a point: a small place, an address, a particular building seen as a meeting point, or a place where an event happens.", "at + small place · address · point"),
      ex(["Example", "He lives at Mirpur."], ["Example", "Wait for me at the bus stop."]),
      ex(["Example", "She is at school now."], ["Example", "We met at a wedding."]),
      ex(["Example", "Someone is at the door."], ["Example", "He lives at 25, Green Road."]),
      rule("'In' is used for a large place (a city, a country) and for the inside of anything enclosed.", "in + city · country · inside a space"),
      ex(["Example", "He lives in Dhaka."], ["Example", "Bangladesh is in South Asia."]),
      ex(["Example", "The boys are playing in the field."], ["Example", "There is some water in the glass."]),
      ex(["Example", "Keep the money in your pocket."], ["Example", "I read the news in the newspaper."]),
      note("Both together: a small place takes 'at' and the bigger place round it takes 'in': 'He lives at Mirpur in Dhaka.' 'Kazi Nazrul Islam was born at Churulia in Burdwan.'"),
      rule("'On' is used for a surface, and for a line such as a road, a river or a coast.", "on + surface · road · river · floor · wall"),
      ex(["Example", "The book is on the table."], ["Example", "There is a picture on the wall."]),
      ex(["Example", "Dhaka stands on the Buriganga."], ["Example", "Don't walk on the grass."]),
      ex(["Example", "His house is on the main road."], ["Example", "She is sitting on a chair."]),

      h("In and into, on and onto"),
      rule("'In' shows rest inside a place; 'into' shows movement from outside to inside.", "rest → in · motion inward → into"),
      ex(["Rest", "The fish are swimming in the pond."], ["Motion", "The boy jumped into the pond."]),
      ex(["Rest", "He is in his room."], ["Motion", "He went into his room."]),
      ex(["Change", "Water turns into ice when it freezes."], ["Change", "Translate the passage into Bangla."]),
      rule("'On' shows rest on a surface; 'onto' or 'upon' shows movement on to it.", "rest → on · motion onto a surface → onto / upon"),
      ex(["Rest", "The cat is sitting on the wall."], ["Motion", "The cat jumped onto the wall."]),
      ex(["Example", "The tiger sprang upon the deer."]),

      h("Between and among"),
      rule("'Between' is used for two persons or things; 'among' for more than two.", "between + two · among + three or more"),
      ex(["Example", "Divide the mangoes between the two brothers."], ["Example", "Divide the mangoes among the five brothers."]),
      ex(["Example", "There is a river between the two villages."], ["Example", "He is popular among his classmates."]),
      ex(["Example", "Keep it between you and me."], ["Example", "Bangladesh lies between India and Myanmar."]),

      h("Above, over, below and under"),
      rule("'Above' means higher than, not touching; 'over' means directly above, often covering or touching, or from one side to the other.", "above = higher · over = right above / covering / across"),
      ex(["Above", "The sun is above the horizon."], ["Over", "There is a bridge over the river."]),
      ex(["Above", "The plane flew above the clouds."], ["Over", "She put a blanket over the sleeping child."]),
      rule("'Below' means lower than; 'under' means directly below, often covered by the thing above.", "below = lower · under = right beneath / covered"),
      ex(["Below", "The temperature fell below zero."], ["Under", "The cat is under the table."]),
      ex(["Below", "Write your name below the line."], ["Under", "We sat under a banyan tree."]),
      note("'Over' and 'above' also mean 'more than', and 'under' and 'below' 'less than': 'over fifty people', 'children under five', 'above average', 'below average'."),

      h("Beside, besides, by and near"),
      rule("'Beside' means by the side of; 'besides' means in addition to.", "beside = by the side of · besides = in addition to"),
      ex(["Beside", "Come and sit beside me."], ["Besides", "Besides English, he knows French."]),
      ex(["Beside", "Our school stands beside the river."], ["Besides", "Besides being a poet, he was a musician."]),
      rule("'By' means very close to, at the side of; 'near' means not far from.", "by = right at the side · near = not far"),
      ex(["By", "He was sitting by the window."], ["Near", "Our house is near the station."]),

      h("Direction: to, towards, for, from"),
      rule("'To' shows the destination reached; 'towards' shows only the direction, the destination may not be reached.", "to = up to the place · towards = in its direction"),
      ex(["To", "He went to Chattogram."], ["Towards", "He was walking towards the station."]),
      ex(["To", "She returned to her village."], ["Towards", "The ship sailed towards the east."]),
      rule("'For' shows a destination after leave, start, set out, sail and depart; 'from' shows the starting point.", "leave / start / set out + for + destination · from + starting point"),
      ex(["Example", "He left for Dhaka yesterday."], ["Example", "We started for school at 9 o'clock."]),
      ex(["Example", "She came from Sylhet."], ["Example", "The ship set sail for Singapore."]),
      note("'Go to Dhaka' but 'leave for Dhaka'. 'Leave Dhaka' (no preposition) means go away from Dhaka."),

      h("Across, through, along, round"),
      rule("'Across' means from one side of a surface to the other; 'through' means from one end to the other of something with sides or a covering.", "across = over a surface · through = inside something"),
      ex(["Across", "He swam across the river."], ["Through", "The train passed through a tunnel."]),
      ex(["Across", "Look before you walk across the road."], ["Through", "We walked through the forest."]),
      ex(["Through", "Light comes in through the window."]),
      rule("'Along' means following the length of a line; 'round' or 'around' means in a circle or on every side.", "along = lengthwise · round = in a circle"),
      ex(["Along", "We walked along the bank of the river."], ["Round", "The earth moves round the sun."]),
      ex(["Around", "They sat around the fire."]),

      h("Up, down, off and out of"),
      rule("'Up' and 'down' show movement to a higher or lower place; 'off' shows separation from a surface; 'out of' shows movement from inside to outside.", "up · down · off = away from · out of = from inside"),
      ex(["Up", "The monkey climbed up the tree."], ["Down", "He came down the stairs."]),
      ex(["Off", "He fell off the roof."], ["Off", "Keep off the grass."]),
      ex(["Out of", "He came out of the room."], ["Out of", "Take the book out of the bag."]),

      h("In front of, behind, opposite, against, beyond"),
      ex(["In front of", "There is a garden in front of our house."], ["Behind", "The sun hid behind the clouds."]),
      ex(["Opposite", "The bank is opposite the post office."], ["Against", "He leaned the ladder against the wall."]),
      ex(["Beyond", "Our village lies beyond the hills."], ["Within", "The shop is within walking distance."]),
    ],
  },

  /* ───────────────────── Other Relations ───────────────────── */
  {
    id: "preposition-other-relations",
    title: "Agent, Instrument, Cause & More",
    body: [
      para("Apart from time and place, a preposition can show who did an action, with what, how, why, what a thing is made of, whom it belongs to, and so on. These relations are fixed: each one has its own preposition."),
      h("By and with"),
      rule("'By' shows the doer (the agent) of an action, especially in the passive voice.", "passive + by + doer"),
      ex(["Example", "The letter was written by Rahim."], ["Example", "'Gitanjali' was written by Rabindranath Tagore."]),
      rule("'With' shows the tool or instrument used to do an action.", "with + tool"),
      ex(["Example", "He cut the mango with a knife."], ["Example", "We write with a pen."]),
      ex(["Both", "The snake was killed by the farmer with a stick."]),
      rule("'By' shows the means of travel or communication; but 'on foot' and 'in / on' with a particular vehicle.", "by bus / train / air / post · on foot · in a car · on a bus"),
      ex(["Example", "He goes to school by bus."], ["Example", "She sent the letter by post."]),
      ex(["Example", "They came on foot."], ["Example", "He came in his own car."]),
      ex(["Example", "I met him on the train."]),
      rule("'With' also shows company, and something a person has.", "with = together with · having"),
      ex(["Example", "She went to the fair with her brother."], ["Example", "He is a man with a kind heart."]),
      ex(["Example", "A girl with blue eyes came in."]),
      h("Of and from: material and origin"),
      rule("'Made of' when the material can still be seen in the thing; 'made from' when it has been changed completely.", "made of = material unchanged · made from = material changed"),
      ex(["Of", "This table is made of wood."], ["From", "Paper is made from bamboo."]),
      ex(["Of", "The ring is made of gold."], ["From", "Butter is made from milk."]),
      rule("'From' shows the place or source something comes from.", "from + source"),
      ex(["Example", "He comes from a poor family."], ["Example", "We get wool from sheep."]),
      h("Of: possession and part"),
      rule("'Of' shows possession, a part of a whole, or a quantity.", "of = belonging to · part of · amount of"),
      ex(["Example", "The capital of Bangladesh is Dhaka."], ["Example", "The legs of the table are broken."]),
      ex(["Example", "One of my friends is a doctor."], ["Example", "Give me a glass of water."]),
      h("Cause and reason"),
      rule("'Die of' a disease; 'die from' a cause such as a wound or overwork; 'die for' a cause you give your life to; 'die in' an accident or a battle.", "die of · die from · die for · die in"),
      ex(["Of", "He died of cholera."], ["From", "He died from overwork."]),
      ex(["For", "The martyrs died for their mother tongue."], ["In", "Many people died in the road accident."]),
      rule("'For', 'because of', 'owing to', 'due to' and 'on account of' show a reason.", "for · because of · owing to · on account of + noun"),
      ex(["Example", "He was punished for his rudeness."], ["Example", "The match was postponed because of rain."]),
      ex(["Example", "He could not come owing to illness."], ["Example", "The school was closed on account of the flood."]),
      ex(["Example", "Mother wept for joy."], ["Example", "He is famous for his honesty."]),
      h("Purpose"),
      rule("'For' + noun shows a purpose; 'with a view to' and 'for the purpose of' are followed by V-ing.", "for + noun · with a view to + V-ing"),
      ex(["Example", "We went out for a walk."], ["Example", "He went to Dhaka for treatment."]),
      ex(["Example", "He came here with a view to meeting you."]),
      h("Contrast, exception and addition"),
      rule("'In spite of' and 'despite' show a contrast. 'Despite' takes no 'of'.", "in spite of + noun · despite + noun"),
      ex(["Example", "In spite of his poverty, he is honest."], ["Example", "Despite the rain, the match went on."]),
      rule("'Except' and 'but' mean 'leaving out'; 'besides' means 'in addition to'.", "except / but = leaving out · besides = as well as"),
      ex(["Except", "Everyone came except Karim."], ["But", "None but the brave deserve the fair."]),
      ex(["Besides", "Besides Karim, three others came."]),
      h("About, on, like, against, without"),
      rule("'About' shows the subject of talk or thought; 'on' is used for a serious or formal topic.", "about = concerning · on = on the subject of"),
      ex(["About", "Tell me about your school."], ["On", "He gave a speech on the Liberation War."]),
      ex(["On", "Write a paragraph on your village."]),
      ex(["Like", "She sings like a nightingale."], ["Against", "The people fought against injustice."]),
      ex(["Without", "We cannot live without water."], ["As", "He works as a teacher."]),
    ],
  },

  /* ─────────────────── Appropriate Prepositions ─────────────────── */
  {
    id: "preposition-appropriate",
    title: "Appropriate Prepositions A–Z",
    body: [
      para("Many verbs, adjectives and nouns are always followed by one particular preposition. These pairs are not decided by any rule — they have to be learnt, and they are exactly what the board means by 'appropriate prepositions'. The list below is arranged from A to Z; each pair is shown in a sentence so you learn how it sounds."),
      note("When you revise, cover the sentence and say the pair aloud: 'afraid — of', 'depend — on', 'interested — in'. Twenty minutes a day on this list will fill most of the gaps in the exam."),
      h("A"),
      pair("abide by", "We must abide by the rules of the road."),
      pair("absent from", "He was absent from school yesterday."),
      pair("absorbed in", "She was absorbed in her studies."),
      pair("abstain from", "We should abstain from smoking."),
      pair("accede to", "The authority acceded to our request."),
      pair("according to", "According to the forecast, it will rain today."),
      pair("accuse of", "He was accused of theft."),
      pair("accustomed to", "I am accustomed to getting up early."),
      pair("acquainted with", "I am well acquainted with him."),
      pair("addicted to", "Many young people are addicted to drugs."),
      pair("afraid of", "The child is afraid of the dark."),
      pair("aim at", "The hunter aimed at the bird."),
      pair("alive to", "He is fully alive to the danger."),
      pair("amazed at", "We were amazed at his courage."),
      pair("anxious about / for", "Mother is anxious about my health. · He is anxious for success."),
      pair("apologize to … for", "He apologized to the teacher for his rudeness."),
      pair("apply to … for", "He applied to the headmaster for leave."),
      pair("arrive at / in", "We arrived at the station. · They arrived in Dhaka."),
      pair("ashamed of", "He is ashamed of his conduct."),
      pair("aware of", "We should be aware of our rights."),
      h("B"),
      pair("believe in", "I believe in God."),
      pair("belong to", "This book belongs to me."),
      pair("beneficial to", "Exercise is beneficial to health."),
      pair("blind to", "A mother is blind to her child's faults."),
      pair("boast of", "He boasts of his wealth."),
      pair("born of / in / into", "He was born of poor parents. · She was born in 1990. · He was born into a rich family."),
      pair("bound for", "The ship is bound for Singapore."),
      pair("busy with", "She is busy with her work."),
      h("C"),
      pair("capable of", "He is capable of doing the job."),
      pair("care for", "He does not care for money."),
      pair("careful of / about", "Be careful of your health."),
      pair("charge with", "He was charged with murder."),
      pair("comment on", "He refused to comment on the matter."),
      pair("compensate for", "Nothing can compensate for the loss of health."),
      pair("complain to … about / of", "He complained to the police about the theft. · She complained of a headache."),
      pair("confident of", "I am confident of success."),
      pair("confidence in", "We have full confidence in our teacher."),
      pair("congratulate on", "I congratulate you on your success."),
      pair("conscious of", "Everyone should be conscious of the danger."),
      pair("consist of", "The committee consists of seven members."),
      pair("contrary to", "Contrary to our hopes, he failed."),
      pair("crowded with", "The street was crowded with people."),
      pair("cure of", "The doctor cured him of fever."),
      h("D"),
      pair("deal with", "The book deals with the Liberation War."),
      pair("depend on / upon", "Success depends on hard work."),
      pair("deprive of", "The poor are deprived of education."),
      pair("desirous of", "He is desirous of fame."),
      pair("devoid of", "He is devoid of common sense."),
      pair("devoted to", "He is devoted to his studies."),
      pair("different from", "My opinion is different from yours."),
      pair("disgusted with / at", "I am disgusted with his behaviour."),
      pair("dispose of", "He disposed of his old car."),
      pair("due to", "The delay was due to heavy traffic."),
      pair("dull of", "He is dull of hearing."),
      h("E"),
      pair("eager for / to", "He is eager for success."),
      pair("eligible for", "He is eligible for the post."),
      pair("engaged in / to", "He is engaged in writing a novel. · She is engaged to a doctor."),
      pair("entitled to", "Every citizen is entitled to vote."),
      pair("envious of", "Do not be envious of others' success."),
      pair("equal to", "Your share is equal to mine."),
      pair("escape from", "The prisoner escaped from jail."),
      pair("exempt from", "He was exempted from the fine."),
      pair("expert in / at", "She is expert in cooking."),
      h("F"),
      pair("faithful to", "A dog is faithful to its master."),
      pair("familiar with / to", "I am familiar with the road. · The road is familiar to me."),
      pair("famous for", "Sylhet is famous for tea."),
      pair("fit for", "He is not fit for the job."),
      pair("fond of", "My brother is fond of reading."),
      pair("free from / of", "He is free from anxiety. · The service is free of charge."),
      pair("full of", "The glass is full of water."),
      h("G – I"),
      pair("good at", "She is good at mathematics."),
      pair("grateful to … for", "I am grateful to you for your help."),
      pair("guilty of", "He is guilty of murder."),
      pair("harmful to", "Smoking is harmful to health."),
      pair("hope for", "We hope for the best."),
      pair("ignorant of", "He is ignorant of the fact."),
      pair("independent of", "He is independent of his parents."),
      pair("indifferent to", "He is indifferent to his studies."),
      pair("indispensable to / for", "Water is indispensable to life."),
      pair("injurious to", "Smoking is injurious to health."),
      pair("insist on", "He insisted on going there."),
      pair("interested in", "She is interested in music."),
      h("J – N"),
      pair("jealous of", "He is jealous of my success."),
      pair("junior to", "He is two years junior to me."),
      pair("kind to", "Be kind to animals."),
      pair("laugh at", "Do not laugh at the poor."),
      pair("listen to", "Listen to what I say."),
      pair("long for", "The prisoner longed for freedom."),
      pair("loyal to", "He is loyal to his country."),
      pair("married to", "She is married to a teacher."),
      pair("necessary for", "Exercise is necessary for good health."),
      pair("negligent of / in", "He is negligent of his duties."),
      pair("noted for", "Chattogram is noted for its hills."),
      h("O – P"),
      pair("obedient to", "A good student is obedient to his teachers."),
      pair("object to", "I object to your proposal."),
      pair("owing to", "He was absent owing to illness."),
      pair("part from / with", "He parted from his friend. · He parted with his property."),
      pair("persist in", "He persisted in his demand."),
      pair("pleased with / at", "The teacher is pleased with me. · He was pleased at the news."),
      pair("polite to", "Be polite to everyone."),
      pair("popular with", "He is popular with his students."),
      pair("pray to … for", "We pray to God for peace."),
      pair("prefer … to", "I prefer tea to coffee."),
      pair("prevent from", "Rain prevented us from going out."),
      pair("proficient in", "He is proficient in English."),
      pair("proud of", "We are proud of our heroes."),
      pair("provide with / for", "The school provided us with books. · He provides for his family."),
      h("Q – R"),
      pair("quarrel with … about / over", "Do not quarrel with anybody over trifles."),
      pair("recover from", "He has recovered from his illness."),
      pair("refrain from", "Refrain from bad company."),
      pair("rely on / upon", "You can rely on him."),
      pair("remind of", "The picture reminds me of my childhood."),
      pair("responsible to … for", "The manager is responsible to the owner for the loss."),
      pair("rich in", "Bangladesh is rich in natural resources."),
      pair("rob of", "They robbed him of his money."),
      h("S"),
      pair("satisfied with", "He is satisfied with his result."),
      pair("search for", "The police are searching for the thief."),
      pair("senior to", "He is senior to me in service."),
      pair("similar to", "My dress is similar to yours."),
      pair("sorry for / about", "I am sorry for my mistake."),
      pair("succeed in", "He succeeded in the examination."),
      pair("suffer from", "She is suffering from fever."),
      pair("superior to", "This cloth is superior to that."),
      pair("sure of", "I am sure of his honesty."),
      pair("surprised at", "I was surprised at the news."),
      pair("sympathy for / with", "We have sympathy for the poor."),
      h("T – Z"),
      pair("thankful to … for", "I am thankful to you for your kindness."),
      pair("tired of / from", "I am tired of his lies. · She was tired from the long walk."),
      pair("true to", "He is true to his word."),
      pair("useful to / for", "A cow is useful to us."),
      pair("vain of", "She is vain of her beauty."),
      pair("wait for", "Time and tide wait for none."),
      pair("weak in", "He is weak in English."),
      pair("worthy of", "He is worthy of praise."),
      pair("zeal for", "He has great zeal for work."),
    ],
  },

  /* ──────────── Same Word, Different Prepositions ──────────── */
  {
    id: "preposition-same-word-different",
    title: "Same Word, Different Prepositions",
    body: [
      para("Some words take one preposition with a person and another with a thing, or change their meaning with the preposition. The board is fond of these because a student who knows only one of the pairs will get the gap wrong."),
      rule("'Angry with' a person; 'angry at' or 'about' a thing or an action.", "angry with + person · angry at + thing"),
      ex(["Person", "The teacher was angry with me."], ["Thing", "He was angry at my rude remark."]),
      rule("'Agree with' a person or an opinion; 'agree to' a proposal; 'agree on' a point to be decided.", "agree with + person · to + proposal · on + point"),
      ex(["With", "I agree with you."], ["To", "He agreed to my proposal."], ["On", "They agreed on the date of the picnic."]),
      rule("'Differ from' = be unlike; 'differ with' a person = disagree with him.", "differ from · differ with"),
      ex(["From", "Man differs from beast in reason."], ["With", "I differ with you on this point."]),
      rule("'Part from' a person; 'part with' a thing.", "part from + person · part with + thing"),
      ex(["From", "She parted from her friends with tears."], ["With", "He will not part with his old books."]),
      rule("'Die of' a disease, 'from' a cause, 'for' an ideal, 'in' an accident or a battle, 'by' violence.", "die of · from · for · in · by"),
      ex(["Of", "He died of malaria."], ["From", "He died from a wound."], ["For", "They died for the country."], ["In", "He died in a road accident."], ["By", "The criminal died by the sword."]),
      rule("'Look at' = see; 'look for' = search; 'look after' = take care of; 'look into' = examine; 'look up to' = respect; 'look down upon' = despise; 'look forward to' = wait eagerly for.", "look at · for · after · into · up to · down upon · forward to"),
      ex(["At", "Look at the blackboard."], ["For", "I am looking for my pen."], ["After", "She looks after her old parents."]),
      ex(["Into", "The police are looking into the matter."], ["Up to", "Students look up to their teachers."], ["Down upon", "Never look down upon the poor."], ["Forward to", "I am looking forward to meeting you."]),
      rule("'Compare with' to show likeness and difference between similar things; 'compare to' to liken one thing to a different kind of thing.", "compare with = weigh side by side · compare to = liken"),
      ex(["With", "Compare his handwriting with yours."], ["To", "Poets compare life to a dream."]),
      rule("'Engaged in' an activity; 'engaged to' a person (to be married); 'engaged with' a person in talk or business.", "engaged in · to · with"),
      ex(["In", "He is engaged in social work."], ["To", "She is engaged to an engineer."], ["With", "The manager is engaged with a client."]),
      rule("'Pleased with' a person; 'pleased at' or 'about' a thing that happens.", "pleased with + person · at + event"),
      ex(["With", "The teacher is pleased with the boy."], ["At", "We were pleased at the news of his success."]),
      rule("'Disappointed with' or 'in' a person; 'disappointed at' or 'with' a thing.", "disappointed with / in + person · at + thing"),
      ex(["Person", "Father was disappointed with me."], ["Thing", "He was disappointed at the result."]),
      rule("'Tired of' = bored with; 'tired from' or 'with' = exhausted by.", "tired of = bored · tired from = weary"),
      ex(["Of", "I am tired of eating the same food every day."], ["From", "He was tired from the long journey."]),
      rule("'Anxious about' a person or thing we worry over; 'anxious for' something we desire.", "anxious about = worried · anxious for = eager"),
      ex(["About", "Mother is anxious about my safety."], ["For", "He is anxious for a good job."]),
      rule("'Arrive at' a small place or a building; 'arrive in' a country or a large city.", "arrive at + small place · arrive in + large place"),
      ex(["At", "We arrived at the airport at noon."], ["In", "They arrived in London last week."]),
      rule("'Free from' a trouble; 'free of' cost or charge.", "free from · free of"),
      ex(["From", "May your life be free from worry."], ["Of", "Books are given free of cost."]),
      rule("'Complain to' a person; 'complain about' a matter; 'complain of' a pain or illness.", "complain to · about · of"),
      ex(["To / about", "He complained to the manager about the service."], ["Of", "The old man complained of pain in his chest."]),
      rule("'Familiar with' — the person knows the thing; 'familiar to' — the thing is known to the person.", "person + familiar with · thing + familiar to"),
      ex(["With", "I am familiar with this song."], ["To", "This song is familiar to me."]),
      rule("'Responsible to' a person; 'responsible for' a thing or an action.", "responsible to + person · for + thing"),
      ex(["Both", "A minister is responsible to the parliament for his work."]),
      rule("'In time' = early enough, before it is too late; 'on time' = at exactly the fixed time, punctually.", "in time · on time"),
      ex(["In time", "We reached the station in time to catch the train."], ["On time", "The train left on time."]),
      rule("'At the end' = at the last point; 'in the end' = finally, after all.", "at the end · in the end"),
      ex(["At the end", "The office is at the end of the road."], ["In the end", "In the end, truth prevails."]),
      rule("'Give up' = stop; 'give in' = surrender; 'give away' = give free; 'give out' = distribute or run out.", "give up · in · away · out"),
      ex(["Up", "He has given up smoking."], ["In", "The enemy gave in at last."], ["Away", "He gave away all his money to the poor."]),
      rule("'Take after' = look like a parent; 'take off' = remove / rise; 'take care of' = look after.", "take after · off · care of"),
      ex(["After", "The boy takes after his father."], ["Off", "The plane took off at 10 a.m."], ["Care of", "Take care of your health."]),
      rule("'Put off' = postpone; 'put on' = wear; 'put out' = extinguish; 'put up with' = tolerate.", "put off · on · out · up with"),
      ex(["Off", "The meeting was put off till Monday."], ["On", "Put on your shirt."], ["Out", "The firemen put out the fire."], ["Up with", "I cannot put up with his rudeness."]),
    ],
  },

  /* ─────────── No Preposition & Common Errors ─────────── */
  {
    id: "preposition-errors",
    title: "No Preposition & Common Errors",
    body: [
      para("A gap is sometimes set where no preposition is needed at all, or a student writes one out of habit because the Bangla sentence seems to need it. These are the errors the examiner sees most often."),
      h("Verbs that take no preposition"),
      rule("'Enter' a place, 'reach' a place, 'discuss' a matter, 'resemble' a person, 'marry' a person, 'attack' an enemy, 'order' a thing, 'answer' a question, 'obey' an order, 'request' a person, 'ask' a person — all take a direct object.", "enter · reach · discuss · resemble · marry · attack · order · answer · obey + object"),
      ex(["Wrong", "He entered into the room."], ["Right", "He entered the room."]),
      ex(["Wrong", "We reached at the station."], ["Right", "We reached the station."]),
      ex(["Wrong", "Let us discuss about the matter."], ["Right", "Let us discuss the matter."]),
      ex(["Wrong", "He resembles like his father."], ["Right", "He resembles his father."]),
      ex(["Wrong", "She married with a doctor."], ["Right", "She married a doctor. / She was married to a doctor."]),
      ex(["Wrong", "The enemy attacked on the town."], ["Right", "The enemy attacked the town."]),
      ex(["Wrong", "He ordered for a cup of tea."], ["Right", "He ordered a cup of tea."]),
      ex(["Wrong", "Answer to the question."], ["Right", "Answer the question."]),
      ex(["Wrong", "I requested to him to help me."], ["Right", "I requested him to help me."]),
      note("The noun form often does take a preposition: 'entry into', 'an answer to', 'a discussion about', 'an attack on', 'an order for', 'a request for'."),
      rule("No preposition before 'home' after a verb of motion, and none before this, that, next, last, every, today, tomorrow or yesterday.", "go home · come home · last week · next year"),
      ex(["Wrong", "He went to home."], ["Right", "He went home."]),
      ex(["Wrong", "I met him on last Sunday."], ["Right", "I met him last Sunday."]),
      h("A preposition that must not be left out"),
      ex(["Wrong", "Listen me."], ["Right", "Listen to me."]),
      ex(["Wrong", "He explained me the matter."], ["Right", "He explained the matter to me."]),
      ex(["Wrong", "Wait me here."], ["Right", "Wait for me here."]),
      ex(["Wrong", "She is married with a teacher."], ["Right", "She is married to a teacher."]),
      ex(["Wrong", "He is senior than me."], ["Right", "He is senior to me."]),
      ex(["Wrong", "I prefer tea than coffee."], ["Right", "I prefer tea to coffee."]),
      h("The wrong preposition"),
      ex(["Wrong", "He has been ill from Monday."], ["Right", "He has been ill since Monday."]),
      ex(["Wrong", "I have been waiting since two hours."], ["Right", "I have been waiting for two hours."]),
      ex(["Wrong", "He died by cholera."], ["Right", "He died of cholera."]),
      ex(["Wrong", "She is good in English."], ["Right", "She is good at English."]),
      ex(["Wrong", "He is afraid from dogs."], ["Right", "He is afraid of dogs."]),
      ex(["Wrong", "He congratulated me for my success."], ["Right", "He congratulated me on my success."]),
      ex(["Wrong", "The table is made from wood."], ["Right", "The table is made of wood."]),
      ex(["Wrong", "Divide the cake between the four boys."], ["Right", "Divide the cake among the four boys."]),
      ex(["Wrong", "He jumped in the river from the bridge."], ["Right", "He jumped into the river from the bridge."]),
      ex(["Wrong", "He goes to school on bus."], ["Right", "He goes to school by bus."]),
      ex(["Wrong", "I shall come back within an hour. (meaning 'after one hour')"], ["Right", "I shall come back in an hour."]),
      ex(["Wrong", "He is angry on me."], ["Right", "He is angry with me."]),
      ex(["Wrong", "I am confident on success."], ["Right", "I am confident of success."]),
      ex(["Wrong", "He was accused for theft."], ["Right", "He was accused of theft."]),
      ex(["Wrong", "He was charged of murder."], ["Right", "He was charged with murder."]),
      h("A preposition at the end of a sentence"),
      para("In questions and relative clauses the preposition is often carried to the end of the sentence. It must not be dropped there."),
      ex(["Example", "Who are you talking to?"], ["Example", "This is the house I live in."]),
      ex(["Example", "What are you looking for?"], ["Example", "He has no friend to play with."]),
      ex(["Formal", "To whom were you talking?"], ["Formal", "This is the house in which I live."]),
    ],
  },

  /* ───────────────────────── Mixed Practice ───────────────────────── */
  {
    id: "preposition-mixed-practice",
    title: "Mixed Practice",
    prompt: PROMPT,
    body: [
      para("Sentences of the kind the board sets, drawn from every piece. Cover the answer, decide on the preposition, then check it against the reason."),
      q("He was born ——— 1995.", "in", "A year takes 'in'."),
      q("We will meet ——— Friday.", "on", "A day of the week takes 'on'."),
      q("The train will arrive ——— 6 p.m.", "at", "An exact clock time takes 'at'."),
      q("He has been absent ——— Sunday.", "since", "A point of time with the Present Perfect takes 'since'."),
      q("She has been learning English ——— five years.", "for", "A length of time takes 'for'."),
      q("You must submit the assignment ——— Monday.", "by", "A deadline, 'not later than', takes 'by'."),
      q("Wait here ——— I return.", "till / until", "The action goes on up to that time."),
      q("The boy fell ——— the tree.", "from / off", "Separation from a place or surface."),
      q("The frog jumped ——— the well.", "into", "Movement from outside to inside."),
      q("There are fish ——— the pond.", "in", "Rest inside a place."),
      q("Divide the sweets ——— the two sisters.", "between", "Two persons take 'between'."),
      q("There was a quarrel ——— the members of the club.", "among", "More than two take 'among'."),
      q("The earth moves ——— the sun.", "round", "Movement in a circle."),
      q("He swam ——— the river.", "across", "From one side of a surface to the other."),
      q("The letter was written ——— my sister.", "by", "The doer in a passive sentence."),
      q("He killed the snake ——— a stick.", "with", "The instrument."),
      q("She goes to school ——— foot.", "on", "'On foot' is fixed."),
      q("The old man died ——— cancer.", "of", "Death from a disease: 'die of'."),
      q("Our heroes died ——— the country.", "for", "Giving one's life for a cause: 'die for'."),
      q("This chair is made ——— wood.", "of", "The wood can still be seen: 'made of'."),
      q("Sugar is made ——— sugarcane.", "from", "The material is changed: 'made from'."),
      q("He is fond ——— music.", "of", "'Fond of' is a fixed pair."),
      q("She is good ——— English.", "at", "'Good at' is a fixed pair."),
      q("I am interested ——— painting.", "in", "'Interested in' is a fixed pair."),
      q("Success depends ——— hard work.", "on / upon", "'Depend on' is a fixed pair."),
      q("He is suffering ——— fever.", "from", "'Suffer from' is a fixed pair."),
      q("I congratulate you ——— your success.", "on", "'Congratulate on' is a fixed pair."),
      q("Smoking is injurious ——— health.", "to", "'Injurious to' is a fixed pair."),
      q("I am angry ——— you.", "with", "'Angry with' a person."),
      q("He was angry ——— my conduct.", "at", "'Angry at' a thing or an action."),
      q("I agree ——— your proposal.", "to", "'Agree to' a proposal."),
      q("I agree ——— you.", "with", "'Agree with' a person."),
      q("She parted ——— her friends.", "from", "'Part from' a person."),
      q("He will not part ——— his books.", "with", "'Part with' a thing."),
      q("The poor are deprived ——— many facilities.", "of", "'Deprived of' is a fixed pair."),
      q("I prefer rice ——— bread.", "to", "'Prefer … to', never 'than'."),
      q("He is senior ——— me.", "to", "'Senior to', never 'than'."),
      q("He succeeded ——— dint of hard work.", "by", "'By dint of' is a phrase preposition."),
      q("He could not attend ——— account of illness.", "on", "'On account of' is a phrase preposition."),
      q("——— spite of his poverty, he is happy.", "In", "'In spite of' is a phrase preposition."),
      q("He left ——— Chattogram last night.", "for", "'Leave for' + destination."),
      q("I shall finish the work ——— an hour.", "in / within", "'In an hour' = at the end of it; 'within an hour' = before it ends."),
      q("Do not look down ——— the poor.", "upon", "'Look down upon' = despise."),
      q("She looks ——— her sick mother.", "after", "'Look after' = take care of."),
      q("The fire was put ——— by the firemen.", "out", "'Put out' = extinguish."),
      q("He entered ——— the room. (Is a preposition needed?)", "no preposition — He entered the room.", "'Enter' a place takes a direct object."),
      q("He is devoted ——— his studies.", "to", "'Devoted to' is a fixed pair."),
      q("We must abide ——— the law.", "by", "'Abide by' is a fixed pair."),
      q("Bangladesh is rich ——— natural beauty.", "in", "'Rich in' is a fixed pair."),
    ],
  },

  /* ─────────────────────── Solved passages ─────────────────────── */
  {
    id: "preposition-passage-liberation-war",
    title: "Solved Passage: Our Liberation War",
    prompt: PROMPT,
    body: [
      para("Bangladesh achieved her independence (a) ——— 1971. The Pakistani army attacked the unarmed people (b) ——— the night of 25 March. People (c) ——— all walks of life joined the war. They fought (d) ——— the enemy for nine months. Many freedom fighters laid down their lives (e) ——— the country. At last the Pakistani army surrendered (f) ——— the allied forces (g) ——— 16 December (h) ——— the Racecourse ground in Dhaka. The nation is ever grateful (i) ——— the martyrs. We should be proud (j) ——— our glorious history."),
      h("Answers"),
      ex(["(a) in", "A year takes 'in'."]),
      ex(["(b) on", "'Night' alone takes 'at', but 'the night of 25 March' belongs to a particular date, so 'on'."]),
      ex(["(c) from", "'People from all walks of life' — the source or background they come from."]),
      ex(["(d) against", "'Fight against' an enemy: opposition."]),
      ex(["(e) for", "'Lay down one's life for' a cause — the purpose they died for."]),
      ex(["(f) to", "'Surrender to' is a fixed pair."]),
      ex(["(g) on", "A date takes 'on'."]),
      ex(["(h) at", "A particular spot where an event took place takes 'at'; the larger city takes 'in'."]),
      ex(["(i) to", "'Grateful to' a person (and 'for' a thing)."]),
      ex(["(j) of", "'Proud of' is a fixed pair."]),
      h("The completed passage"),
      para("Bangladesh achieved her independence in 1971. The Pakistani army attacked the unarmed people on the night of 25 March. People from all walks of life joined the war. They fought against the enemy for nine months. Many freedom fighters laid down their lives for the country. At last the Pakistani army surrendered to the allied forces on 16 December at the Racecourse ground in Dhaka. The nation is ever grateful to the martyrs. We should be proud of our glorious history."),
    ],
  },
  {
    id: "preposition-passage-traffic-jam",
    title: "Solved Passage: Traffic Jam",
    prompt: PROMPT,
    body: [
      para("Traffic jam is a common problem (a) ——— the big cities of our country. It is most acute (b) ——— Dhaka. People often remain stuck (c) ——— the road (d) ——— hours. (e) ——— rush hours, students cannot reach their schools (f) ——— time. Sometimes patients die (g) ——— the way to hospital. There are many reasons (h) ——— this problem. Everyone should be aware (i) ——— the traffic rules and abide (j) ——— them."),
      h("Answers"),
      ex(["(a) in", "The inside of a large area: 'in the big cities'."]),
      ex(["(b) in", "A large city takes 'in'."]),
      ex(["(c) on", "A road is a line, so 'on the road'."]),
      ex(["(d) for", "A length of time: 'for hours'."]),
      ex(["(e) During", "'All through' a period, followed by a noun."]),
      ex(["(f) in", "'In time' = early enough, before it is too late."]),
      ex(["(g) on", "'On the way' is fixed."]),
      ex(["(h) for / behind", "'Reasons for' a thing; 'behind' is also used for the cause lying under it."]),
      ex(["(i) of", "'Aware of' is a fixed pair."]),
      ex(["(j) by", "'Abide by' is a fixed pair meaning obey."]),
      h("The completed passage"),
      para("Traffic jam is a common problem in the big cities of our country. It is most acute in Dhaka. People often remain stuck on the road for hours. During rush hours, students cannot reach their schools in time. Sometimes patients die on the way to hospital. There are many reasons for this problem. Everyone should be aware of the traffic rules and abide by them."),
    ],
  },
  {
    id: "preposition-passage-trees",
    title: "Solved Passage: Trees, Our Friends",
    prompt: PROMPT,
    body: [
      para("Trees are our best friends. They provide us (a) ——— food, shelter and medicine. They protect us (b) ——— natural disasters. We cannot live (c) ——— trees. Birds build their nests (d) ——— the branches (e) ——— trees. Trees also add (f) ——— the beauty of nature. But people are cutting down trees (g) ——— random. As a result, our land is turning (h) ——— a desert. Everyone should be conscious (i) ——— this danger. We should plant more trees and take care (j) ——— them."),
      h("Answers"),
      ex(["(a) with", "'Provide someone with something' is fixed."]),
      ex(["(b) from", "'Protect from' is a fixed pair."]),
      ex(["(c) without", "The sense is 'in the absence of' trees."]),
      ex(["(d) in", "A nest sits inside the fork of the branches: 'in'."]),
      ex(["(e) of", "A part of a whole: 'the branches of trees'."]),
      ex(["(f) to", "'Add to' = increase."]),
      ex(["(g) at", "'At random' is fixed: without any plan."]),
      ex(["(h) into", "Change from one state into another: 'turn into'."]),
      ex(["(i) of", "'Conscious of' is a fixed pair."]),
      ex(["(j) of", "'Take care of' is fixed."]),
      h("The completed passage"),
      para("Trees are our best friends. They provide us with food, shelter and medicine. They protect us from natural disasters. We cannot live without trees. Birds build their nests in the branches of trees. Trees also add to the beauty of nature. But people are cutting down trees at random. As a result, our land is turning into a desert. Everyone should be conscious of this danger. We should plant more trees and take care of them."),
    ],
  },
  {
    id: "preposition-passage-begum-rokeya",
    title: "Solved Passage: Begum Rokeya",
    prompt: PROMPT,
    body: [
      para("Begum Rokeya was born (a) ——— 1880 (b) ——— Pairaband (c) ——— Rangpur. She was born (d) ——— a conservative Muslim family. (e) ——— those days, women were deprived (f) ——— education. She learnt Bangla and English (g) ——— the help (h) ——— her elder brother. She was married (i) ——— Syed Sakhawat Hossain. She dedicated her whole life (j) ——— the cause of women's education."),
      h("Answers"),
      ex(["(a) in", "A year takes 'in'."]),
      ex(["(b) at", "A village, a small place, takes 'at'."]),
      ex(["(c) in", "The larger district round it takes 'in'."]),
      ex(["(d) into", "'Born into a family' — entering it at birth. 'Born of' is used with parents."]),
      ex(["(e) In", "'In those days' — a period of time."]),
      ex(["(f) of", "'Deprived of' is a fixed pair."]),
      ex(["(g) with", "'With the help of' is fixed."]),
      ex(["(h) of", "Part of the same phrase: 'with the help of'."]),
      ex(["(i) to", "'Married to' a person, never 'married with'."]),
      ex(["(j) to", "'Dedicate to' is a fixed pair."]),
      h("The completed passage"),
      para("Begum Rokeya was born in 1880 at Pairaband in Rangpur. She was born into a conservative Muslim family. In those days, women were deprived of education. She learnt Bangla and English with the help of her elder brother. She was married to Syed Sakhawat Hossain. She dedicated her whole life to the cause of women's education."),
    ],
  },
  {
    id: "preposition-passage-value-of-time",
    title: "Solved Passage: The Value of Time",
    prompt: PROMPT,
    body: [
      para("Time is very precious (a) ——— us. Time and tide wait (b) ——— none. So we should make proper use (c) ——— time. Every moment (d) ——— our life is valuable. We should not waste time (e) ——— idle gossip. A student should get up early (f) ——— the morning and sit (g) ——— the reading table. Success in life depends (h) ——— the proper use of time. Idlers are always looked down (i) ——— by others. So we should be punctual (j) ——— all our work."),
      h("Answers"),
      ex(["(a) to", "'Precious to' a person."]),
      ex(["(b) for", "'Wait for' is a fixed pair."]),
      ex(["(c) of", "'Make use of' is fixed."]),
      ex(["(d) of", "A part of a whole: 'every moment of our life'."]),
      ex(["(e) in", "'Waste time in' + an activity."]),
      ex(["(f) in", "A part of the day takes 'in'."]),
      ex(["(g) at", "'At the table' — a point where one sits to work."]),
      ex(["(h) on / upon", "'Depend on' is a fixed pair."]),
      ex(["(i) upon", "'Look down upon' = despise; here in the passive."]),
      ex(["(j) in", "'Punctual in' one's work or duties."]),
      h("The completed passage"),
      para("Time is very precious to us. Time and tide wait for none. So we should make proper use of time. Every moment of our life is valuable. We should not waste time in idle gossip. A student should get up early in the morning and sit at the reading table. Success in life depends on the proper use of time. Idlers are always looked down upon by others. So we should be punctual in all our work."),
    ],
  },
  {
    id: "preposition-passage-health",
    title: "Solved Passage: Health Is Wealth",
    prompt: PROMPT,
    body: [
      para("Health is the root (a) ——— all happiness. A sick man cannot enjoy life even if he rolls (b) ——— wealth. Good health depends (c) ——— some simple rules. We should take a walk (d) ——— the morning. We should take our meals (e) ——— regular times. We must keep away (f) ——— bad habits like smoking. Smoking is injurious (g) ——— health. We should go (h) ——— bed early and get up (i) ——— dawn. It is truly said that a sound mind lives (j) ——— a sound body."),
      h("Answers"),
      ex(["(a) of", "'The root of' — the source of something."]),
      ex(["(b) in", "'Roll in wealth' is fixed: be very rich."]),
      ex(["(c) on / upon", "'Depend on' is a fixed pair."]),
      ex(["(d) in", "A part of the day takes 'in'."]),
      ex(["(e) at", "An exact or fixed time takes 'at'."]),
      ex(["(f) from", "'Keep away from' = avoid."]),
      ex(["(g) to", "'Injurious to' is a fixed pair."]),
      ex(["(h) to", "'Go to bed' is fixed."]),
      ex(["(i) at", "'Dawn' is a fixed point of time: 'at dawn'."]),
      ex(["(j) in", "The inside of something: 'in a sound body'."]),
      h("The completed passage"),
      para("Health is the root of all happiness. A sick man cannot enjoy life even if he rolls in wealth. Good health depends on some simple rules. We should take a walk in the morning. We should take our meals at regular times. We must keep away from bad habits like smoking. Smoking is injurious to health. We should go to bed early and get up at dawn. It is truly said that a sound mind lives in a sound body."),
    ],
  },
  {
    id: "preposition-passage-books",
    title: "Solved Passage: Books, Our Best Companions",
    prompt: PROMPT,
    body: [
      para("Books are our best companions. They are a great source (a) ——— knowledge and pleasure. We can learn (b) ——— the past and the present (c) ——— books. The taste for reading differs (d) ——— person to person. Some people are fond (e) ——— novels, while others are interested (f) ——— science. A good book never leaves us (g) ——— times (h) ——— trouble. It gives us company (i) ——— our lonely hours. Indeed, a room (j) ——— books is like a body without a soul."),
      h("Answers"),
      ex(["(a) of", "'A source of' is fixed."]),
      ex(["(b) about", "'Learn about' a subject."]),
      ex(["(c) from", "The source of the learning: 'from books'."]),
      ex(["(d) from", "'From person to person' is fixed."]),
      ex(["(e) of", "'Fond of' is a fixed pair."]),
      ex(["(f) in", "'Interested in' is a fixed pair."]),
      ex(["(g) in", "'In times of' is fixed."]),
      ex(["(h) of", "Part of the same phrase: 'in times of trouble'."]),
      ex(["(i) in / during", "Through a period: 'in' or 'during our lonely hours'."]),
      ex(["(j) without", "The comparison 'like a body without a soul' shows the sense: having no books."]),
      h("The completed passage"),
      para("Books are our best companions. They are a great source of knowledge and pleasure. We can learn about the past and the present from books. The taste for reading differs from person to person. Some people are fond of novels, while others are interested in science. A good book never leaves us in times of trouble. It gives us company in our lonely hours. Indeed, a room without books is like a body without a soul."),
    ],
  },
  {
    id: "preposition-passage-digital-bangladesh",
    title: "Solved Passage: Information Technology",
    prompt: PROMPT,
    body: [
      para("We are living (a) ——— the age of information technology. Computers and the internet have brought a revolution (b) ——— every sphere of life. Now we can communicate (c) ——— people all over the world (d) ——— a moment. Students can get information (e) ——— any subject (f) ——— the help of the internet. Many young people earn money (g) ——— outsourcing. But some are addicted (h) ——— social media and waste time. We should make proper use of technology and keep away (i) ——— its misuse. Only then can we make our country rich (j) ——— every respect."),
      h("Answers"),
      ex(["(a) in", "A period of history: 'in the age of'."]),
      ex(["(b) in", "'A revolution in' a field or sphere."]),
      ex(["(c) with", "'Communicate with' a person."]),
      ex(["(d) in", "'In a moment' = at the end of a very short time."]),
      ex(["(e) on / about", "'Information on' or 'about' a subject."]),
      ex(["(f) with", "'With the help of' is fixed."]),
      ex(["(g) by / through", "The means of earning: 'by outsourcing'."]),
      ex(["(h) to", "'Addicted to' is a fixed pair."]),
      ex(["(i) from", "'Keep away from' = avoid."]),
      ex(["(j) in", "'In every respect' is fixed."]),
      h("The completed passage"),
      para("We are living in the age of information technology. Computers and the internet have brought a revolution in every sphere of life. Now we can communicate with people all over the world in a moment. Students can get information on any subject with the help of the internet. Many young people earn money by outsourcing. But some are addicted to social media and waste time. We should make proper use of technology and keep away from its misuse. Only then can we make our country rich in every respect."),
    ],
  },
];
