// components/rightFormOfVerbsData.ts
//
// Right Form of Verbs, one piece per family of rules: tense, agreement, the
// fixed structures the board loves, gerund and infinitive, and the passive.
// Each piece gives the rules in order and works each rule through examples,
// the verb in brackets on one line and the right form on the next, then
// board-style passages are solved gap by gap with the reason for each answer.

import type { Block, Piece } from "./englishData";

const h = (text: string): Block => ({ type: "heading", text });
const rule = (text: string, formula?: string): Block => ({
  type: "rule",
  text,
  formula,
});
const note = (text: string): Block => ({ type: "note", label: "Note", text });
// One example: each argument is a [label, sentence] pair.
const ex = (...lines: [string, string][]): Block => ({
  type: "example",
  lines: lines.map(([label, text]) => ({ label, text })),
});
// The usual pair: the sentence as set, then with the verb in its right form.
const q = (given: string, answer: string): Block =>
  ex(["Given", given], ["Answer", answer]);
const para = (text: string): Block => ({ type: "para", text });

const PROMPT = "Fill in the gaps with the right forms of verbs in brackets.";

export const rightFormOfVerbs: Piece[] = [
  /* ───────────────────────── Introduction ───────────────────────── */
  {
    id: "verbs-introduction",
    title: "Introduction",
    body: [
      para("In this question a passage or a set of sentences is given with some verbs left in brackets in their base form. You have to write each verb in the form the sentence needs: the right tense, the right number and person, or the right non-finite form (to + verb, verb-ing or past participle). To do it well you must first look at the whole sentence — the subject, the time words, the other verbs and any fixed structure around the gap — and only then decide."),
      h("The five forms of a verb"),
      ex(["V1 (base)", "go · write · eat · play"], ["V2 (past)", "went · wrote · ate · played"], ["V3 (past participle)", "gone · written · eaten · played"], ["V-ing", "going · writing · eating · playing"], ["V + s / es", "goes · writes · eats · plays"]),
      h("The twelve tenses at a glance"),
      ex(["Present Indefinite", "S + V1 / V1 + s, es — He writes a letter."], ["Present Continuous", "S + am / is / are + V-ing — He is writing a letter."], ["Present Perfect", "S + have / has + V3 — He has written a letter."], ["Present Perf. Cont.", "S + have / has been + V-ing — He has been writing a letter for an hour."]),
      ex(["Past Indefinite", "S + V2 — He wrote a letter."], ["Past Continuous", "S + was / were + V-ing — He was writing a letter."], ["Past Perfect", "S + had + V3 — He had written a letter."], ["Past Perf. Cont.", "S + had been + V-ing — He had been writing a letter for an hour."]),
      ex(["Future Indefinite", "S + shall / will + V1 — He will write a letter."], ["Future Continuous", "S + shall / will be + V-ing — He will be writing a letter."], ["Future Perfect", "S + shall / will have + V3 — He will have written a letter."], ["Future Perf. Cont.", "S + shall / will have been + V-ing — He will have been writing a letter for an hour."]),
      h("How to find the right form"),
      para("1. Find the subject of the gap and see whether it is singular or plural, and in which person."),
      para("2. Look for a time word: always, now, yesterday, ago, since, tomorrow, already, just and so on."),
      para("3. Look at the other verbs in the sentence and in the passage; the tense usually runs on unchanged."),
      para("4. Look for a fixed structure before the gap: a modal, 'to', a preposition, 'it is time', 'as if', 'would rather', 'let', 'make' and the like."),
      para("5. Decide whether the subject does the action or receives it. If it receives it, the verb is passive: be + V3."),
      h("Common irregular verbs"),
      ex(["be", "was / were · been"], ["begin", "began · begun"], ["break", "broke · broken"], ["bring", "brought · brought"], ["build", "built · built"], ["buy", "bought · bought"], ["catch", "caught · caught"], ["choose", "chose · chosen"], ["come", "came · come"], ["do", "did · done"], ["draw", "drew · drawn"], ["drink", "drank · drunk"], ["drive", "drove · driven"], ["eat", "ate · eaten"], ["fall", "fell · fallen"], ["feel", "felt · felt"], ["fight", "fought · fought"], ["find", "found · found"], ["fly", "flew · flown"], ["forget", "forgot · forgotten"], ["get", "got · got / gotten"], ["give", "gave · given"], ["go", "went · gone"], ["grow", "grew · grown"], ["hide", "hid · hidden"], ["keep", "kept · kept"], ["know", "knew · known"]),
      ex(["lay (put down)", "laid · laid"], ["lie (rest)", "lay · lain"], ["lie (tell a lie)", "lied · lied"], ["lead", "led · led"], ["leave", "left · left"], ["lose", "lost · lost"], ["make", "made · made"], ["meet", "met · met"], ["put", "put · put"], ["read", "read · read"], ["ride", "rode · ridden"], ["ring", "rang · rung"], ["rise", "rose · risen"], ["run", "ran · run"], ["see", "saw · seen"], ["seek", "sought · sought"], ["sell", "sold · sold"], ["shake", "shook · shaken"], ["sing", "sang · sung"], ["sink", "sank · sunk"], ["sit", "sat · sat"], ["speak", "spoke · spoken"], ["spend", "spent · spent"], ["steal", "stole · stolen"], ["swim", "swam · swum"], ["take", "took · taken"], ["teach", "taught · taught"], ["tear", "tore · torn"], ["tell", "told · told"], ["think", "thought · thought"], ["throw", "threw · thrown"], ["wake", "woke · woken"], ["wear", "wore · worn"], ["win", "won · won"], ["write", "wrote · written"]),
      h("Spelling rules for adding -s, -ed and -ing"),
      rule("A verb ending in s, ss, sh, ch, x, z or o takes -es in the third person singular.", "go → goes · watch → watches · wash → washes · fix → fixes"),
      rule("A verb ending in a consonant + y changes y into i before -es and -ed; a vowel + y stays.", "study → studies, studied · play → plays, played"),
      rule("A verb ending in a silent e drops the e before -ing and adds only -d for the past.", "write → writing · come → coming · love → loved"),
      rule("A one-syllable verb ending in one vowel + one consonant doubles the consonant before -ing and -ed. So does a longer verb stressed on the last syllable.", "run → running · stop → stopped · admit → admitted · begin → beginning"),
      rule("A verb ending in -ie changes it into y before -ing.", "die → dying · lie → lying · tie → tying"),
    ],
  },

  /* ─────────────────────────── Tense ─────────────────────────── */
  {
    id: "verbs-tense",
    title: "Rules of Tense",
    body: [
      para("Most gaps are decided by tense. The time words in the sentence, and the tense of the verbs around the gap, tell you which form to use."),

      h("Present Indefinite"),
      rule("A habit, a daily routine or a repeated action takes the Present Indefinite. Look for always, often, usually, sometimes, generally, regularly, every day, daily, never, seldom.", "S + V1 (+ s / es with a third person singular subject)"),
      q("He always (tell) the truth.", "He always tells the truth."),
      q("We (go) to school every day.", "We go to school every day."),
      q("My mother usually (get) up early.", "My mother usually gets up early."),
      q("She seldom (visit) us.", "She seldom visits us."),
      q("Traffic jam (be) a common affair in Dhaka city.", "Traffic jam is a common affair in Dhaka city."),
      q("He often (come) late to school.", "He often comes late to school."),
      q("Farmers generally (work) from dawn to dusk.", "Farmers generally work from dawn to dusk."),
      q("My father (not smoke).", "My father does not smoke."),
      q("(Do) she (go) to school regularly?", "Does she go to school regularly?"),

      rule("A universal truth, a scientific fact or a proverb is always in the Present Indefinite, even in a past-tense sentence.", "universal truth → Present Indefinite"),
      q("The sun (rise) in the east.", "The sun rises in the east."),
      q("Water (boil) at 100°C.", "Water boils at 100°C."),
      q("The teacher said that the earth (move) round the sun.", "The teacher said that the earth moves round the sun."),
      q("Honesty (be) the best policy.", "Honesty is the best policy."),
      q("Man (be) mortal.", "Man is mortal."),
      q("The moon (move) round the earth.", "The moon moves round the earth."),
      q("Two and two (make) four.", "Two and two make four."),
      q("Time and tide (wait) for none.", "Time and tide wait for none."),
      q("Our teacher told us that light (travel) faster than sound.", "Our teacher told us that light travels faster than sound."),

      rule("In a clause of time or condition (when, before, after, until, till, as soon as, if, unless) that refers to the future, use the Present Indefinite, not 'will'.", "when / if / unless … + Present Indefinite, S + will + V1"),
      q("I shall wait until he (come).", "I shall wait until he comes."),
      q("If it (rain), we shall not go out.", "If it rains, we shall not go out."),
      q("Call me as soon as you (reach) Dhaka.", "Call me as soon as you reach Dhaka."),
      q("Unless you (work) hard, you will fail.", "Unless you work hard, you will fail."),
      q("He will not come unless you (call) him.", "He will not come unless you call him."),
      q("Wait here till I (return).", "Wait here till I return."),
      q("When the exam (be) over, we shall go to Sylhet.", "When the exam is over, we shall go to Sylhet."),
      q("Before the sun (set), we shall reach home.", "Before the sun sets, we shall reach home."),

      h("Present Continuous"),
      rule("An action going on now takes the Present Continuous. Look for now, at present, at this moment, look, listen, still.", "S + am / is / are + V-ing"),
      q("Look, the baby (sleep).", "Look, the baby is sleeping."),
      q("They (play) football now.", "They are playing football now."),
      q("Listen! Someone (knock) at the door.", "Listen! Someone is knocking at the door."),
      q("At present he (live) in Khulna.", "At present he is living in Khulna."),
      q("We (face) the problem of unemployment at present.", "We are facing the problem of unemployment at present."),
      q("Please be quiet. The baby (sleep).", "Please be quiet. The baby is sleeping."),
      q("Prices of goods (rise) day by day.", "Prices of goods are rising day by day."),
      q("The number of vehicles (increase) every year.", "The number of vehicles is increasing every year."),
      note("Verbs of feeling, thinking and possessing — see, hear, smell, taste, know, believe, understand, like, love, hate, want, own, have (possess), seem — are not usually used in the continuous form. 'I know him' (not 'I am knowing him'); 'Do you hear the noise?' (not 'Are you hearing')."),

      h("Present Perfect"),
      rule("An action just completed, or a past action whose result is still present, takes the Present Perfect. Look for just, already, yet, ever, never, lately, recently, so far, this week / year.", "S + have / has + V3"),
      q("He has just (finish) his work.", "He has just finished his work."),
      q("I (not see) him yet.", "I have not seen him yet."),
      q("Have you ever (be) to Cox's Bazar?", "Have you ever been to Cox's Bazar?"),
      q("She already (leave) the house.", "She has already left the house."),
      q("Bangladesh (make) great progress in the field of education.", "Bangladesh has made great progress in the field of education."),
      q("The government (take) many steps to reduce poverty.", "The government has taken many steps to reduce poverty."),
      q("I (not finish) my homework yet.", "I have not finished my homework yet."),
      note("Never use the Present Perfect with a definite past time. 'I saw him yesterday' — not 'I have seen him yesterday'."),

      h("Present Perfect Continuous"),
      rule("An action that began in the past and is still going on takes the Present Perfect Continuous, usually with 'since' (a point of time) or 'for' (a length of time).", "S + have / has been + V-ing + since / for"),
      q("He (read) since morning.", "He has been reading since morning."),
      q("It (rain) for two hours.", "It has been raining for two hours."),
      q("We (live) in this town since 2015.", "We have been living in this town since 2015."),
      q("She (suffer) from fever for a week.", "She has been suffering from fever for a week."),
      q("They (wait) for you since morning.", "They have been waiting for you since morning."),
      q("Rahim (teach) in this school for ten years.", "Rahim has been teaching in this school for ten years."),

      h("Past Indefinite"),
      rule("An action finished at a definite past time takes the Past Indefinite. Look for yesterday, ago, last night / week / year, in 1971, once, the other day.", "S + V2"),
      q("I (meet) him yesterday.", "I met him yesterday."),
      q("He (go) to Dhaka two days ago.", "He went to Dhaka two days ago."),
      q("Bangladesh (become) independent in 1971.", "Bangladesh became independent in 1971."),
      q("The other day I (see) a snake.", "The other day I saw a snake."),
      q("Kazi Nazrul Islam (die) in 1976.", "Kazi Nazrul Islam died in 1976."),
      q("The Second World War (break) out in 1939.", "The Second World War broke out in 1939."),
      q("I (buy) a new bicycle last week.", "I bought a new bicycle last week."),
      q("Once upon a time there (live) a king.", "Once upon a time there lived a king."),
      q("He (not go) to school yesterday.", "He did not go to school yesterday."),

      h("Past Continuous"),
      rule("A longer action going on at a past moment takes the Past Continuous; the short action that broke into it takes the Past Indefinite.", "while + Past Continuous, … + Past Indefinite"),
      q("While I (read), the light went out.", "While I was reading, the light went out."),
      q("When I reached the station, the train (leave).", "When I reached the station, the train was leaving."),
      q("He (sleep) when the thief entered the room.", "He was sleeping when the thief entered the room."),
      q("While she (cook), she burnt her hand.", "While she was cooking, she burnt her hand."),
      q("It (rain) when I went out.", "It was raining when I went out."),
      q("The students (make) a noise when the teacher entered the class.", "The students were making a noise when the teacher entered the class."),

      h("Past Perfect"),
      rule("Of two past actions, the one that happened first takes the Past Perfect and the later one the Past Indefinite. 'Before' and 'after' show the order.", "S + had + V3 + before + S + V2 · after + S + had + V3, S + V2"),
      q("The patient had died before the doctor (come).", "The patient had died before the doctor came."),
      q("The train (leave) before we reached the station.", "The train had left before we reached the station."),
      q("After he (finish) the work, he went home.", "After he had finished the work, he went home."),
      q("I found that someone (steal) my purse.", "I found that someone had stolen my purse."),
      q("The doctor came after the patient (die).", "The doctor came after the patient had died."),
      q("He told me that he (lose) his pen.", "He told me that he had lost his pen."),
      q("We had reached the school before the bell (ring).", "We had reached the school before the bell rang."),
      q("I (never see) such a big river before I went to Chandpur.", "I had never seen such a big river before I went to Chandpur."),

      rule("After 'No sooner had', 'Hardly had' and 'Scarcely had' the verb is V3, and the second clause is in the Past Indefinite.", "No sooner had + S + V3 + than + S + V2 · Hardly / Scarcely had + S + V3 + when + S + V2"),
      q("No sooner had he (see) the police than he ran away.", "No sooner had he seen the police than he ran away."),
      q("Hardly had we reached the station when the train (start).", "Hardly had we reached the station when the train started."),
      q("Scarcely had he (reach) the station when the train left.", "Scarcely had he reached the station when the train left."),
      q("No sooner had the teacher entered the class than the students (stand) up.", "No sooner had the teacher entered the class than the students stood up."),

      h("Past Perfect Continuous"),
      rule("An action that had been going on for some time before another past action takes the Past Perfect Continuous.", "S + had been + V-ing + for / since"),
      q("He (work) for three hours when I met him.", "He had been working for three hours when I met him."),
      q("It (rain) since morning before we went out.", "It had been raining since morning before we went out."),

      h("Future"),
      rule("An action in the future takes shall / will + V1. Look for tomorrow, next day / week / year, soon, in future, in 2030.", "S + shall / will + V1"),
      q("He (come) tomorrow.", "He will come tomorrow."),
      q("We (visit) Sylhet next month.", "We shall visit Sylhet next month."),
      q("By this time tomorrow I (reach) Chattogram.", "By this time tomorrow I shall have reached Chattogram."),
      q("This time next week they (sit) for the exam.", "This time next week they will be sitting for the exam."),
      q("Our school (reopen) next Sunday.", "Our school will reopen next Sunday."),
      q("I think it (rain) today.", "I think it will rain today."),
      q("By the end of this year we (complete) the syllabus.", "By the end of this year we shall have completed the syllabus."),
      note("'By + a future time' asks for the Future Perfect (will have + V3); 'this time tomorrow / next week' asks for the Future Continuous (will be + V-ing)."),

      h("Since and for"),
      rule("A clause with 'since' in a Present Perfect sentence takes the Past Indefinite, because 'since' points to a moment in the past.", "S + have / has + V3 + since + S + V2"),
      q("Many years have passed since he (die).", "Many years have passed since he died."),
      q("It is ten years since I (see) him.", "It is ten years since I saw him."),
      q("Two years have gone by since we (come) here.", "Two years have gone by since we came here."),
      q("Five years have passed since my grandfather (die).", "Five years have passed since my grandfather died."),
      q("It is many days since I (visit) my village.", "It is many days since I visited my village."),

      h("Sequence of tense"),
      rule("If the principal clause is in the past, the subordinate clause is also in a past tense: is → was, will → would, can → could, may → might, has → had.", "Past principal clause + past subordinate clause"),
      q("He said that he (be) ill.", "He said that he was ill."),
      q("I thought that she (will) come.", "I thought that she would come."),
      q("He worked hard so that he (can) pass.", "He worked hard so that he could pass."),
      q("She told me that she (finish) the work.", "She told me that she had finished the work."),
      q("He asked me where I (live).", "He asked me where I lived."),
      q("The teacher said that we (must) work hard.", "The teacher said that we must work hard."),
      q("I knew that he (may) come.", "I knew that he might come."),
      note("A universal truth or a habitual fact keeps the present even after a past principal clause (see the rule on universal truths). A comparison with 'than' may take any tense the sense needs: 'He loved me more than he loves you.'"),
    ],
  },

  /* ───────────────────── Subject–verb agreement ───────────────────── */
  {
    id: "verbs-agreement",
    title: "Subject–Verb Agreement",
    body: [
      para("The verb must agree with its subject in number and person. A singular subject takes a singular verb (is, was, has, goes) and a plural subject a plural verb (are, were, have, go). The hard part is to find the real subject."),

      rule("Two subjects joined by 'and' take a plural verb.", "A + and + B → plural verb"),
      q("Rahim and Karim (be) friends.", "Rahim and Karim are friends."),
      q("He and I (have) done the work.", "He and I have done the work."),
      q("Karim and his brother (go) to school together.", "Karim and his brother go to school together."),
      q("Honesty and diligence (be) the keys to success.", "Honesty and diligence are the keys to success."),

      rule("But if the two nouns joined by 'and' mean one person or one idea, or 'each' or 'every' comes before them, the verb is singular.", "one idea / each / every + A and B → singular verb"),
      q("Bread and butter (be) his favourite food.", "Bread and butter is his favourite food."),
      q("The poet and philosopher (be) dead.", "The poet and philosopher is dead."),
      q("Slow and steady (win) the race.", "Slow and steady wins the race."),
      q("Every boy and girl (be) present.", "Every boy and girl is present."),
      q("Rice and curry (be) our staple food.", "Rice and curry is our staple food."),
      q("Each man and woman (have) a right to vote.", "Each man and woman has a right to vote."),
      note("One article means one person: 'The poet and philosopher is dead.' Two articles mean two people: 'The poet and the philosopher are dead.'"),

      rule("With 'either … or', 'neither … nor', 'not only … but also' and 'or', the verb agrees with the nearer subject.", "either / neither / not only A … B + verb agreeing with B"),
      q("Either you or he (be) guilty.", "Either you or he is guilty."),
      q("Neither he nor his friends (be) present.", "Neither he nor his friends were present."),
      q("Not only the students but also the teacher (be) happy.", "Not only the students but also the teacher was happy."),
      q("Neither Rina nor Mina (have) done the work.", "Neither Rina nor Mina has done the work."),
      q("Either the teacher or the students (be) responsible.", "Either the teacher or the students are responsible."),

      rule("With 'as well as', 'with', 'along with', 'together with', 'besides', 'in addition to' and 'rather than', the verb agrees with the first subject.", "A + as well as / with + B + verb agreeing with A"),
      q("The captain as well as the players (be) happy.", "The captain as well as the players was happy."),
      q("The teacher with his students (be) going on a picnic.", "The teacher with his students is going on a picnic."),
      q("He, along with his friends, (have) come.", "He, along with his friends, has come."),
      q("The mother as well as her children (be) sleeping.", "The mother as well as her children was sleeping."),
      q("The house with all its furniture (be) sold.", "The house with all its furniture was sold."),

      rule("Each, every, either, neither, everyone, everybody, someone, somebody, anyone, nobody, no one, nothing and many a take a singular verb.", "each / every / everybody / many a + singular noun → singular verb"),
      q("Each of the boys (get) a prize.", "Each of the boys gets a prize."),
      q("Everybody (like) him.", "Everybody likes him."),
      q("Many a man (have) died in the war.", "Many a man has died in the war."),
      q("Neither of the two answers (be) correct.", "Neither of the two answers is correct."),
      q("Every student (want) to do well in the exam.", "Every student wants to do well in the exam."),
      q("Nobody (know) the answer.", "Nobody knows the answer."),
      q("Every one of us (be) responsible for keeping the environment clean.", "Every one of us is responsible for keeping the environment clean."),

      rule("'One of' + a plural noun takes a singular verb, because the subject is 'one'.", "one of + plural noun → singular verb"),
      q("One of my friends (live) in London.", "One of my friends lives in London."),
      q("One of the boys (be) absent today.", "One of the boys is absent today."),
      q("One of the main causes of traffic jam (be) the lack of planning.", "One of the main causes of traffic jam is the lack of planning."),
      q("Kazi Nazrul Islam is one of the greatest poets who (have) ever lived.", "Kazi Nazrul Islam is one of the greatest poets who have ever lived."),

      rule("'A number of' (many) takes a plural verb; 'the number of' (the count) takes a singular verb.", "a number of → plural · the number of → singular"),
      q("A number of students (be) absent.", "A number of students were absent."),
      q("The number of students (be) increasing.", "The number of students is increasing."),
      q("A number of people (die) in road accidents every year.", "A number of people die in road accidents every year."),
      q("The number of unemployed youths (be) very high.", "The number of unemployed youths is very high."),

      rule("A collective noun thought of as one unit takes a singular verb; thought of as separate members, a plural verb.", "unit → singular · members → plural"),
      q("The jury (give) its verdict.", "The jury gave its verdict."),
      q("The jury (be) divided in their opinions.", "The jury were divided in their opinions."),
      q("Our class (consist) of forty students.", "Our class consists of forty students."),
      q("The committee (have) taken a decision.", "The committee has taken a decision."),
      q("The family (be) quarrelling among themselves.", "The family are quarrelling among themselves."),

      rule("A sum of money, a distance, a period of time or a weight thought of as one amount takes a singular verb.", "amount / distance / time → singular verb"),
      q("Fifty thousand taka (be) a large sum.", "Fifty thousand taka is a large sum."),
      q("Ten kilometres (be) a long way to walk.", "Ten kilometres is a long way to walk."),
      q("Two years (be) a long time.", "Two years is a long time."),

      rule("Some nouns look plural but are singular: news, mathematics, physics, economics, politics (as a subject), innings, the United States.", "news / mathematics / physics → singular verb"),
      q("The news (be) true.", "The news is true."),
      q("Mathematics (be) my favourite subject.", "Mathematics is my favourite subject."),
      q("Physics (be) a difficult subject.", "Physics is a difficult subject."),
      q("No news (be) good news.", "No news is good news."),

      rule("Some nouns are always plural: people, police, cattle, trousers, scissors, spectacles, goods, riches, thanks.", "people / police / cattle / scissors → plural verb"),
      q("The police (have) arrested the thief.", "The police have arrested the thief."),
      q("People (say) so.", "People say so."),
      q("The cattle (be) grazing in the field.", "The cattle are grazing in the field."),
      q("My trousers (be) torn.", "My trousers are torn."),
      q("The scissors (be) very sharp.", "The scissors are very sharp."),

      rule("'The' + an adjective means the whole class of people and takes a plural verb.", "the + adjective → plural verb"),
      q("The rich (be) not always happy.", "The rich are not always happy."),
      q("The poor (live) from hand to mouth.", "The poor live from hand to mouth."),
      q("The honest (be) respected everywhere.", "The honest are respected everywhere."),
      q("The educated (have) a great role in society.", "The educated have a great role in society."),

      rule("With 'none', 'all', 'some', 'half', 'most' and 'part of', the verb agrees with the noun that follows 'of'.", "all / some / most + of + noun → verb agrees with that noun"),
      q("Most of the mangoes (be) rotten.", "Most of the mangoes are rotten."),
      q("Most of the milk (be) spilt.", "Most of the milk was spilt."),
      q("Some of the rice (have) been eaten.", "Some of the rice has been eaten."),

      rule("A relative pronoun (who, which, that) takes the verb that agrees with its antecedent — the noun just before it.", "antecedent + who / which / that + verb agreeing with antecedent"),
      q("It is I who (be) to blame.", "It is I who am to blame."),
      q("He is one of the best boys who (have) ever studied here.", "He is one of the best boys who have ever studied here."),
      q("The book that you gave me (be) very interesting.", "The book that you gave me is very interesting."),
      q("A man who (work) hard must shine in life.", "A man who works hard must shine in life."),
      q("The students who (be) sincere always do well.", "The students who are sincere always do well."),
      q("I, who (be) your friend, will help you.", "I, who am your friend, will help you."),

      rule("After 'There' and 'Here' the verb agrees with the noun that follows it.", "There + be + noun → be agrees with the noun"),
      q("There (be) many trees in our garden.", "There are many trees in our garden."),
      q("There (be) a book on the table.", "There is a book on the table."),
      q("There (be) no chance of rain today.", "There is no chance of rain today."),
      q("Here (come) the bus.", "Here comes the bus."),

      rule("A gerund, an infinitive or a clause used as the subject takes a singular verb.", "V-ing / to + V1 / that-clause as subject → singular verb"),
      q("Walking (be) a good exercise.", "Walking is a good exercise."),
      q("To tell lies (be) a sin.", "To tell lies is a sin."),
      q("What he says (be) true.", "What he says is true."),
      q("Reading books (be) a good habit.", "Reading books is a good habit."),
      q("To err (be) human.", "To err is human."),
      q("Taking regular exercise (keep) us fit.", "Taking regular exercise keeps us fit."),
    ],
  },

  /* ─────────────────────── Special structures ─────────────────────── */
  {
    id: "verbs-special-structures",
    title: "Special Structures",
    body: [
      para("Some words and phrases fix the form of the verb that follows them, whatever the tense of the sentence. These are the rules the board sets most often, so learn each structure by heart."),

      h("Modals and 'let', 'make'"),
      rule("After a modal — can, could, may, might, shall, should, will, would, must, need, dare — the verb is in V1.", "modal + V1"),
      q("You should (obey) your parents.", "You should obey your parents."),
      q("He can (swim) well.", "He can swim well."),
      q("We must (help) the poor.", "We must help the poor."),
      q("We should (take) care of our health.", "We should take care of our health."),
      q("You must not (violate) traffic rules.", "You must not violate traffic rules."),
      q("Everybody should (respect) the teachers.", "Everybody should respect the teachers."),

      rule("After let, make, bid, see, hear, watch, feel and help (object + verb), the verb is in V1 without 'to'.", "let / make / see / hear + object + V1"),
      q("Let him (go).", "Let him go."),
      q("He made me (laugh).", "He made me laugh."),
      q("I saw him (cross) the road.", "I saw him cross the road."),
      q("I heard her (sing) a song.", "I heard her sing a song."),
      q("He helped me (do) the sum.", "He helped me do the sum."),
      q("Let us (go) out for a walk.", "Let us go out for a walk."),
      q("The teacher made the boy (stand) up.", "The teacher made the boy stand up."),
      note("In the passive, 'to' comes back: 'He was made to laugh', 'She was heard to sing a song.'"),

      rule("After had better, would rather, would sooner, rather than and cannot but, the verb is in V1.", "had better / would rather / cannot but + V1"),
      q("You had better (leave) now.", "You had better leave now."),
      q("I would rather (die) than (beg).", "I would rather die than beg."),
      q("I cannot but (laugh) at his joke.", "I cannot but laugh at his joke."),
      q("He would rather (walk) than (take) a rickshaw.", "He would rather walk than take a rickshaw."),
      q("You had better not (go) out in this rain.", "You had better not go out in this rain."),

      h("'It is time' and 'as if'"),
      rule("After 'It is time', 'It is high time' and 'It is about time' + a subject, the verb is in V2 (the past subjunctive). Without a subject use 'to' + V1.", "It is (high) time + S + V2 · It is time + to + V1"),
      q("It is high time we (change) our habits.", "It is high time we changed our habits."),
      q("It is time you (go) to bed.", "It is time you went to bed."),
      q("It is time (start) our work.", "It is time to start our work."),
      q("It is high time the government (take) steps to stop food adulteration.", "It is high time the government took steps to stop food adulteration."),
      q("It is time we (leave).", "It is time we left."),

      rule("After 'as if' and 'as though', use 'were' for 'be' with every subject in the present; any other verb goes into V2. In a past-tense sentence, use had + V3.", "as if + S + were / V2 · (past) as if + S + had + V3"),
      q("He talks as if he (be) a king.", "He talks as if he were a king."),
      q("She behaves as if she (know) everything.", "She behaves as if she knew everything."),
      q("He looked as if he (see) a ghost.", "He looked as if he had seen a ghost."),
      q("He spends money as if he (be) a millionaire.", "He spends money as if he were a millionaire."),
      q("He speaks as though he (know) everything.", "He speaks as though he knew everything."),

      rule("After 'wish' for a present wish use V2 ('were' for 'be'); for a past wish use had + V3; for a future wish use would / could + V1.", "wish + S + V2 / were · wish + S + had + V3 · wish + S + would + V1"),
      q("I wish I (be) a bird.", "I wish I were a bird."),
      q("I wish I (know) the answer.", "I wish I knew the answer."),
      q("I wish I (attend) the meeting yesterday.", "I wish I had attended the meeting yesterday."),
      q("I wish you (stop) talking.", "I wish you would stop talking."),
      q("I wish I (can) fly.", "I wish I could fly."),
      q("She wishes she (be) a doctor.", "She wishes she were a doctor."),

      h("Conditional sentences"),
      rule("First conditional — a real or likely condition: 'if' + Present Indefinite, and shall / will + V1 in the main clause.", "If + S + V1 / V1 + s, S + shall / will + V1"),
      q("If you work hard, you (succeed).", "If you work hard, you will succeed."),
      q("If he (come), I shall go.", "If he comes, I shall go."),
      q("If you (not read) regularly, you will fail.", "If you do not read regularly, you will fail."),
      q("If it rains, the match (be) cancelled.", "If it rains, the match will be cancelled."),

      rule("Second conditional — an unreal or imagined present: 'if' + V2 ('were' for 'be'), and would / could / might + V1.", "If + S + V2 / were, S + would + V1"),
      q("If I were a king, I (help) the poor.", "If I were a king, I would help the poor."),
      q("If I (have) wings, I would fly.", "If I had wings, I would fly."),
      q("If he (be) rich, he would buy a car.", "If he were rich, he would buy a car."),
      q("If I (be) you, I would not do it.", "If I were you, I would not do it."),
      q("If he tried, he (succeed).", "If he tried, he would succeed."),

      rule("Third conditional — an unreal past: 'if' + had + V3, and would / could / might + have + V3.", "If + S + had + V3, S + would have + V3"),
      q("If he had worked hard, he (pass).", "If he had worked hard, he would have passed."),
      q("If you (come) earlier, you would have seen him.", "If you had come earlier, you would have seen him."),
      q("If I had known it, I (help) you.", "If I had known it, I would have helped you."),
      q("Had he (start) early, he would have caught the train.", "Had he started early, he would have caught the train."),
      note("'Had', 'were' and 'should' can begin the clause in place of 'if': 'Had I known it, I would have told you.' — 'Were I a bird, I would fly.' — 'Should he come, give him this letter.'"),

      h("'Lest', 'used to', 'be used to'"),
      rule("After 'lest' the verb is 'should' + V1 (or just V1).", "lest + S + should + V1"),
      q("Walk fast lest you (miss) the train.", "Walk fast lest you should miss the train."),
      q("Read attentively lest you (fail).", "Read attentively lest you should fail."),
      q("Obey traffic rules lest you (meet) an accident.", "Obey traffic rules lest you should meet an accident."),

      rule("'Used to' (a past habit) takes V1; 'be used to' and 'get used to' (be accustomed to) take V-ing.", "used to + V1 · be / get used to + V-ing"),
      q("He used to (swim) in the river.", "He used to swim in the river."),
      q("I am used to (walk) in the morning.", "I am used to walking in the morning."),
      q("She is getting used to (live) in the city.", "She is getting used to living in the city."),
      q("There used to (be) a big tree here.", "There used to be a big tree here."),

      h("'To' that is a preposition"),
      rule("After look forward to, with a view to, be accustomed to, object to, be devoted to, confess to and in addition to, 'to' is a preposition, so the verb is V-ing.", "look forward to / with a view to / object to + V-ing"),
      q("I am looking forward to (meet) you.", "I am looking forward to meeting you."),
      q("He went to Dhaka with a view to (see) the Liberation War Museum.", "He went to Dhaka with a view to seeing the Liberation War Museum."),
      q("She objected to (go) there alone.", "She objected to going there alone."),
      q("She is accustomed to (work) hard.", "She is accustomed to working hard."),
      q("He is devoted to (serve) the people.", "He is devoted to serving the people."),

      h("Other fixed structures"),
      rule("'Would you mind', 'I don't mind', 'could not help' and 'cannot help' are followed by V-ing.", "mind / cannot help + V-ing"),
      q("Would you mind (open) the window?", "Would you mind opening the window?"),
      q("I could not help (laugh).", "I could not help laughing."),
      q("I don't mind (wait) for you.", "I don't mind waiting for you."),

      rule("'Too … to' is followed by V1: too + adjective + to + V1.", "too + adjective + to + V1"),
      q("He is too weak (walk).", "He is too weak to walk."),
      q("The tea is too hot (drink).", "The tea is too hot to drink."),
      q("He is too poor (buy) a car.", "He is too poor to buy a car."),

      rule("After 'since' (meaning 'from the time when') a clause with a time in the past takes V2; after 'while' + a subject, the verb is continuous.", "since + S + V2 · while + S + be + V-ing"),
      q("I have known him since he (be) a child.", "I have known him since he was a child."),
      q("While he (walk) in the park, he met an old friend.", "While he was walking in the park, he met an old friend."),

      rule("Verbs that give an order, a demand or an advice in a 'that' clause (suggest, propose, demand, insist, order, recommend) take V1 or should + V1 whatever the subject.", "suggest / demand / insist + that + S + (should) + V1"),
      q("The doctor suggested that he (take) rest.", "The doctor suggested that he take rest."),
      q("I propose that the meeting (be) postponed.", "I propose that the meeting be postponed."),

      rule("An optative sentence with 'May' takes V1; a wish without 'may' also uses V1 with a third-person subject.", "May + S + V1 · S + V1 (wish)"),
      q("May Allah (bless) you.", "May Allah bless you."),
      q("Long (live) Bangladesh!", "Long live Bangladesh!"),
    ],
  },

  /* ─────────────── Gerund, infinitive and participle ─────────────── */
  {
    id: "verbs-non-finite",
    title: "Gerund, Infinitive & Participle",
    body: [
      para("A gap is often not a finite verb at all but a non-finite one: 'to' + V1 (infinitive), V-ing (gerund or present participle) or V3 (past participle). Check first whether the sentence already has a finite verb; if it has, the gap is non-finite."),

      h("Infinitive: to + V1"),
      rule("To show a purpose, use 'to' + V1.", "… + to + V1 (purpose)"),
      q("He went to the market (buy) some fish.", "He went to the market to buy some fish."),
      q("We eat (live).", "We eat to live."),
      q("People come to the city (find) jobs.", "People come to the city to find jobs."),
      q("He works hard (pass) the exam.", "He works hard to pass the exam."),
      q("We go to school (learn).", "We go to school to learn."),

      rule("After want, wish, hope, decide, agree, promise, plan, refuse, learn, expect, fail, try, pretend and seem, use 'to' + V1.", "want / decide / hope / refuse + to + V1"),
      q("He decided (go) abroad.", "He decided to go abroad."),
      q("She refused (help) me.", "She refused to help me."),
      q("They hope (win) the match.", "They hope to win the match."),
      q("I want (become) a doctor.", "I want to become a doctor."),
      q("He promised (help) me.", "He promised to help me."),
      q("She failed (understand) the question.", "She failed to understand the question."),

      rule("After an adjective like glad, sorry, happy, eager, easy, difficult, able, and after 'enough', use 'to' + V1.", "adjective / enough + to + V1"),
      q("I am glad (see) you.", "I am glad to see you."),
      q("He is old enough (understand) it.", "He is old enough to understand it."),
      q("The problem is difficult (solve).", "The problem is difficult to solve."),
      q("He was sorry (hear) the news.", "He was sorry to hear the news."),
      q("They are eager (join) the club.", "They are eager to join the club."),

      rule("After a question word (how, what, where, when, which, whether), use 'to' + V1.", "question word + to + V1"),
      q("I do not know how (swim).", "I do not know how to swim."),
      q("Tell me what (do).", "Tell me what to do."),

      rule("After a first, second, last or only noun ('the first man', 'the last person'), use 'to' + V1.", "the first / last / only + noun + to + V1"),
      q("He was the first man (reach) the spot.", "He was the first man to reach the spot."),
      q("She was the last (leave) the room.", "She was the last to leave the room."),

      h("Gerund: V-ing as a noun"),
      rule("A verb used as the subject or object of a sentence takes the V-ing form (a gerund).", "V-ing as subject / object"),
      q("(Swim) is a good exercise.", "Swimming is a good exercise."),
      q("He likes (read) story books.", "He likes reading story books."),

      rule("After every preposition (in, on, at, of, for, from, without, before, after, by, about, instead of, fond of, interested in, afraid of, tired of, capable of, good at) the verb is in V-ing.", "preposition + V-ing"),
      q("He is fond of (play) cricket.", "He is fond of playing cricket."),
      q("She left without (say) goodbye.", "She left without saying goodbye."),
      q("I am tired of (wait).", "I am tired of waiting."),
      q("He earns his living by (teach).", "He earns his living by teaching."),
      q("After (finish) his work, he went out.", "After finishing his work, he went out."),
      q("He is interested in (learn) English.", "He is interested in learning English."),
      q("Instead of (waste) time, do something useful.", "Instead of wasting time, do something useful."),
      q("She is good at (draw) pictures.", "She is good at drawing pictures."),
      q("He was punished for (tell) a lie.", "He was punished for telling a lie."),

      rule("After enjoy, avoid, finish, stop, mind, miss, practise, admit, deny, consider, keep, give up, go on, can't help and it is no use / it is worth, use V-ing.", "enjoy / avoid / finish / stop / give up + V-ing"),
      q("He gave up (smoke).", "He gave up smoking."),
      q("They enjoyed (swim) in the river.", "They enjoyed swimming in the river."),
      q("Avoid (make) noise.", "Avoid making noise."),
      q("It is no use (cry) over spilt milk.", "It is no use crying over spilt milk."),
      q("The book is worth (read).", "The book is worth reading."),
      q("Please stop (talk).", "Please stop talking."),
      q("He denied (take) the money.", "He denied taking the money."),
      q("She kept (cry) all night.", "She kept crying all night."),
      note("'Stop' changes the meaning with its form: 'He stopped smoking' (gave up the habit) — 'He stopped to smoke' (stopped something else so that he could smoke). 'Remember', 'forget' and 'try' change the same way: 'I remember posting the letter' (I did it) — 'Remember to post the letter' (do not forget to do it)."),

      h("Participles"),
      rule("A present participle (V-ing) describes a noun that does the action; a past participle (V3) describes a noun that receives it.", "doing → V-ing · done to → V3"),
      q("I saw a (fly) bird.", "I saw a flying bird."),
      q("Do not wake a (sleep) child.", "Do not wake a sleeping child."),
      q("A (burn) child dreads the fire.", "A burnt child dreads the fire."),
      q("The (break) glass is on the floor.", "The broken glass is on the floor."),
      q("A (roll) stone gathers no moss.", "A rolling stone gathers no moss."),
      q("The (injure) man was taken to hospital.", "The injured man was taken to hospital."),
      q("(Adulterate) food causes many diseases.", "Adulterated food causes many diseases."),

      rule("A participle can join two actions by the same subject. The first action takes V-ing, or 'having' + V3 if it was finished before the second.", "V-ing / Having + V3 …, S + main verb"),
      q("(Walk) along the road, I saw a snake.", "Walking along the road, I saw a snake."),
      q("(Finish) the work, he went home.", "Having finished the work, he went home."),
      q("(See) the police, the thief ran away.", "Seeing the police, the thief ran away."),
      q("(Hear) the news, she began to cry.", "Hearing the news, she began to cry."),
      q("(Complete) the task, he took a rest.", "Having completed the task, he took a rest."),

      rule("In an absolute phrase — a noun or pronoun with its own participle and no finite verb — use V-ing or V3 by the same test of doing or receiving.", "noun + V-ing / V3, S + main verb"),
      q("The sun (set), we went home.", "The sun having set, we went home."),
      q("The weather (be) fine, we went out.", "The weather being fine, we went out."),
      q("The work (do), they left.", "The work done, they left."),

      rule("After have / get + object, use V3 when someone else does the action for the subject (the causative).", "have / get + object + V3"),
      q("I had my hair (cut).", "I had my hair cut."),
      q("She got her watch (repair).", "She got her watch repaired."),
    ],
  },

  /* ─────────────────────────── Passive ─────────────────────────── */
  {
    id: "verbs-passive",
    title: "Passive Forms",
    body: [
      para("When the subject of the gap receives the action instead of doing it, the verb is passive: the right form of 'be' + V3. Ask yourself: 'Can this subject do this action?' A letter cannot write, rice cannot grow itself, a bridge cannot build — so the verb must be passive."),

      rule("Present and past passive: am / is / are / was / were + V3.", "S + be + V3"),
      q("Rice (grow) in Bangladesh.", "Rice is grown in Bangladesh."),
      q("The letter (write) by Rana yesterday.", "The letter was written by Rana yesterday."),
      q("English (speak) all over the world.", "English is spoken all over the world."),
      q("The Padma Bridge (open) to traffic in 2022.", "The Padma Bridge was opened to traffic in 2022."),
      q("Food (adulterate) by dishonest traders.", "Food is adulterated by dishonest traders."),
      q("Nazrul (know) as our rebel poet.", "Nazrul is known as our rebel poet."),
      q("The thief (catch) by the police last night.", "The thief was caught by the police last night."),

      rule("Continuous passive: am / is / are / was / were + being + V3.", "S + be + being + V3"),
      q("A new bridge (build) over the river now.", "A new bridge is being built over the river now."),
      q("The road (repair) when I passed by.", "The road was being repaired when I passed by."),
      q("Many trees (cut) down every day.", "Many trees are being cut down every day."),

      rule("Perfect passive: have / has / had + been + V3.", "S + have / has / had + been + V3"),
      q("The thief (catch) already.", "The thief has already been caught."),
      q("The work (finish) before he came.", "The work had been finished before he came."),
      q("Many steps (take) to improve the quality of education.", "Many steps have been taken to improve the quality of education."),

      rule("Passive after a modal: modal + be + V3.", "modal + be + V3"),
      q("The work must (do) at once.", "The work must be done at once."),
      q("Our trees should (protect).", "Our trees should be protected."),
      q("Nothing can (gain) without labour.", "Nothing can be gained without labour."),
      q("Traffic rules must (obey).", "Traffic rules must be obeyed."),
      q("Food adulteration should (stop) at any cost.", "Food adulteration should be stopped at any cost."),

      rule("Passive infinitive and gerund: to be + V3, being + V3.", "to be + V3 · being + V3"),
      q("There is no time (lose).", "There is no time to be lost."),
      q("He wants (give) a chance.", "He wants to be given a chance."),
      q("He hates (laugh) at.", "He hates being laughed at."),

      rule("Some verbs of feeling are passive in form and take a fixed preposition: be interested in, be surprised at, be pleased with, be satisfied with, be known to, be married to, be tired of, be filled with, be covered with.", "be + V3 + fixed preposition"),
      q("I am (surprise) at the news.", "I am surprised at the news."),
      q("He is (know) to everybody.", "He is known to everybody."),
      q("The sky is (cover) with clouds.", "The sky is covered with clouds."),
      q("She was (please) with my result.", "She was pleased with my result."),

      rule("'Born' is always passive: 'was / were born' for a past birth, 'is / are born' for a general fact.", "S + was / were + born"),
      q("Bangabandhu (bear) in 1920.", "Bangabandhu was born in 1920."),
      q("Kazi Nazrul Islam (bear) in Churulia.", "Kazi Nazrul Islam was born in Churulia."),

      h("Common mistakes"),
      note("Do not use a passive with an intransitive verb. 'The accident happened', 'He died', 'The sun rises' — never 'was happened', 'was died', 'is risen'."),
      note("Use V3, not V2, after 'be' and 'have': 'was written' (not 'was wrote'), 'has gone' (not 'has went'), 'was broken' (not 'was broke')."),
      note("Keep 'lie' (rest) and 'lay' (put down) apart: 'He lay on the bed' / 'He has lain there for hours' — 'She laid the book on the table.'"),
    ],
  },

  /* ─────────────────────── Mixed practice ─────────────────────── */
  {
    id: "verbs-mixed-practice",
    title: "Mixed Practice",
    body: [
      para("Sentences of the kind the board sets, drawn from every rule. Cover the answer, work out the verb, then check it against the reason."),
      ex(["Given", "Traffic jam (waste) our valuable time."], ["Answer", "wastes"], ["Why", "A general fact with a singular subject: V1 + s."]),
      ex(["Given", "The number of vehicles (increase) day by day."], ["Answer", "is increasing"], ["Why", "'Day by day' shows a change going on now; 'the number' is singular."]),
      ex(["Given", "Many people (not obey) traffic rules."], ["Answer", "do not obey"], ["Why", "A general fact in the negative with a plural subject: do not + V1."]),
      ex(["Given", "He has been (read) since morning."], ["Answer", "reading"], ["Why", "'Has been' + 'since' asks for V-ing."]),
      ex(["Given", "I (see) him yesterday."], ["Answer", "saw"], ["Why", "'Yesterday' is a definite past time."]),
      ex(["Given", "Nazrul (call) the rebel poet."], ["Answer", "is called"], ["Why", "He does not call; people call him — present passive."]),
      ex(["Given", "Walk fast lest you (miss) the bus."], ["Answer", "should miss"], ["Why", "'Lest' takes should + V1."]),
      ex(["Given", "It is high time we (stop) food adulteration."], ["Answer", "stopped"], ["Why", "'It is high time' + subject takes V2."]),
      ex(["Given", "He talks as if he (be) a leader."], ["Answer", "were"], ["Why", "'As if' takes 'were' with every subject."]),
      ex(["Given", "The patient had died before the doctor (come)."], ["Answer", "came"], ["Why", "The later of two past actions takes V2."]),
      ex(["Given", "If I (be) a bird, I would fly."], ["Answer", "were"], ["Why", "Second conditional: 'if' + were."]),
      ex(["Given", "If he had studied, he (pass)."], ["Answer", "would have passed"], ["Why", "Third conditional: would have + V3."]),
      ex(["Given", "She is looking forward to (see) you."], ["Answer", "seeing"], ["Why", "'To' after 'look forward' is a preposition: V-ing."]),
      ex(["Given", "He is fond of (read) books."], ["Answer", "reading"], ["Why", "A preposition is followed by V-ing."]),
      ex(["Given", "We eat (live)."], ["Answer", "to live"], ["Why", "Purpose: to + V1."]),
      ex(["Given", "You had better (consult) a doctor."], ["Answer", "consult"], ["Why", "'Had better' takes V1."]),
      ex(["Given", "Each of the students (be) present."], ["Answer", "is"], ["Why", "'Each' takes a singular verb."]),
      ex(["Given", "One of my friends (be) a doctor."], ["Answer", "is"], ["Why", "The subject is 'one': singular."]),
      ex(["Given", "Neither he nor his friends (be) there."], ["Answer", "were"], ["Why", "The verb agrees with the nearer subject, 'friends'."]),
      ex(["Given", "The teacher as well as the students (be) present."], ["Answer", "was"], ["Why", "The verb agrees with the first subject, 'the teacher'."]),
      ex(["Given", "The rich (be) not always happy."], ["Answer", "are"], ["Why", "'The' + adjective means a class of people: plural."]),
      ex(["Given", "Rice (grow) in Bangladesh."], ["Answer", "is grown"], ["Why", "Rice does not grow itself here — someone grows it: passive."]),
      ex(["Given", "Food adulteration must (stop)."], ["Answer", "be stopped"], ["Why", "Passive after a modal: modal + be + V3."]),
      ex(["Given", "(See) the police, the thief ran away."], ["Answer", "Seeing"], ["Why", "Two actions by the same subject: the first takes V-ing."]),
      ex(["Given", "He was the first man (come) to the meeting."], ["Answer", "to come"], ["Why", "After 'the first' + noun: to + V1."]),
      ex(["Given", "Two years have passed since he (leave) the village."], ["Answer", "left"], ["Why", "A 'since' clause in a Present Perfect sentence takes V2."]),
      ex(["Given", "He said that he (will) help me."], ["Answer", "would"], ["Why", "Sequence of tense: will → would after the past 'said'."]),
      ex(["Given", "The earth (move) round the sun."], ["Answer", "moves"], ["Why", "A universal truth is always in the present."]),
      ex(["Given", "I wish I (can) help you."], ["Answer", "could"], ["Why", "'Wish' for a present wish takes a past form: can → could."]),
      ex(["Given", "It is no use (cry) over spilt milk."], ["Answer", "crying"], ["Why", "'It is no use' is followed by V-ing."]),
    ],
  },

  /* ─────────────────────── Solved passages ─────────────────────── */
  {
    id: "verbs-passage-mother-language",
    title: "Solved Passage: Our Mother Language",
    prompt: PROMPT,
    body: [
      para("Bangla is our mother tongue. We (a) ——— (love) it more than our lives. In 1952 many brave sons of the soil (b) ——— (lay) down their lives for this language. Salam, Barkat, Rafiq and Jabbar (c) ——— (be) among them. Since then 21 February (d) ——— (observe) as Martyrs' Day. In 1999 UNESCO (e) ——— (declare) the day International Mother Language Day. Now the day (f) ——— (observe) all over the world. On this day people (g) ——— (go) barefoot to the Shaheed Minar to pay homage to the martyrs. It is high time we (h) ——— (use) Bangla at all levels of our national life. We should always remember that the martyrs (i) ——— (sacrifice) their lives so that we (j) ——— (can) speak in our mother tongue."),
      h("Answers"),
      ex(["(a) love", "A general, present feeling with the plural subject 'We': Present Indefinite."]),
      ex(["(b) laid", "'In 1952' is a definite past time: V2 of 'lay' (put down) — lay down their lives."]),
      ex(["(c) were", "A past event with a plural subject of four names joined by 'and'."]),
      ex(["(d) has been observed", "'Since then' asks for the Present Perfect, and a day cannot observe itself, so passive."]),
      ex(["(e) declared", "'In 1999' is a definite past time: Past Indefinite, active, since UNESCO did the declaring."]),
      ex(["(f) is observed", "'Now' and a general fact; the day receives the action, so present passive."]),
      ex(["(g) go", "A yearly custom — Present Indefinite with the plural subject 'people'."]),
      ex(["(h) used", "'It is high time' + subject takes V2."]),
      ex(["(i) sacrificed", "A finished past action: Past Indefinite."]),
      ex(["(j) could", "Sequence of tense: after the past 'sacrificed', 'so that … can' becomes 'could'."]),
      h("The completed passage"),
      para("Bangla is our mother tongue. We love it more than our lives. In 1952 many brave sons of the soil laid down their lives for this language. Salam, Barkat, Rafiq and Jabbar were among them. Since then 21 February has been observed as Martyrs' Day. In 1999 UNESCO declared the day International Mother Language Day. Now the day is observed all over the world. On this day people go barefoot to the Shaheed Minar to pay homage to the martyrs. It is high time we used Bangla at all levels of our national life. We should always remember that the martyrs sacrificed their lives so that we could speak in our mother tongue."),
    ],
  },
  {
    id: "verbs-passage-early-rising",
    title: "Solved Passage: Early Rising",
    prompt: PROMPT,
    body: [
      para("Early rising (a) ——— (be) a good habit. It (b) ——— (keep) our body and mind fresh. A man who (c) ——— (rise) early can do his work in time. He can (d) ——— (enjoy) the beauty of the morning. The birds (e) ——— (sing) and a cool breeze (f) ——— (blow) at dawn. (g) ——— (walk) in the open air in the morning is good for health. But many of us are not used to (h) ——— (get) up early. If we (i) ——— (form) this habit, we shall be healthy, wealthy and wise. So we should (j) ——— (make) it a rule of our life."),
      h("Answers"),
      ex(["(a) is", "A general truth with the gerund subject 'Early rising': singular, Present Indefinite."]),
      ex(["(b) keeps", "A general fact with the singular subject 'It': V1 + s."]),
      ex(["(c) rises", "The relative 'who' takes the number of its antecedent 'a man': singular."]),
      ex(["(d) enjoy", "After the modal 'can' the verb is V1."]),
      ex(["(e) sing", "A general fact with the plural subject 'The birds'."]),
      ex(["(f) blows", "A general fact with the singular subject 'a cool breeze'."]),
      ex(["(g) Walking", "A verb used as the subject of the sentence: gerund."]),
      ex(["(h) getting", "'Be used to' means 'be accustomed to', so the verb after it is V-ing."]),
      ex(["(i) form", "An 'if' clause about the future takes the Present Indefinite (first conditional)."]),
      ex(["(j) make", "After the modal 'should' the verb is V1."]),
      h("The completed passage"),
      para("Early rising is a good habit. It keeps our body and mind fresh. A man who rises early can do his work in time. He can enjoy the beauty of the morning. The birds sing and a cool breeze blows at dawn. Walking in the open air in the morning is good for health. But many of us are not used to getting up early. If we form this habit, we shall be healthy, wealthy and wise. So we should make it a rule of our life."),
    ],
  },
  {
    id: "verbs-passage-honest-woodcutter",
    title: "Solved Passage: The Honest Woodcutter",
    prompt: PROMPT,
    body: [
      para("Once there (a) ——— (live) a poor woodcutter by the side of a river. One day he (b) ——— (cut) wood from a tree on the bank of the river. Suddenly his axe (c) ——— (fall) into the water. He (d) ——— (not know) how to swim, so he sat down and began (e) ——— (weep). Hearing his cry, a fairy (f) ——— (appear) before him. She dived into the river and (g) ——— (bring) up a golden axe. But the woodcutter said that it (h) ——— (be) not his. At last the fairy brought up his own iron axe. She was so pleased with his honesty that she (i) ——— (give) him all three axes. The story teaches us that honesty (j) ——— (be) the best policy."),
      h("Answers"),
      ex(["(a) lived", "'Once' begins a story in the past: Past Indefinite."]),
      ex(["(b) was cutting", "A longer action going on when something else happened: Past Continuous."]),
      ex(["(c) fell", "The short action that broke into it: Past Indefinite (V2 of 'fall')."]),
      ex(["(d) did not know", "A past fact in the negative: did not + V1. ('Know' has no continuous form.)"]),
      ex(["(e) to weep", "After 'began', 'to' + V1 (or 'weeping')."]),
      ex(["(f) appeared", "A past action; 'Hearing his cry' already supplies the participle, so this is the finite verb."]),
      ex(["(g) brought", "Joined by 'and' to the past 'dived': V2 of 'bring'."]),
      ex(["(h) was", "Sequence of tense: after the past 'said', 'is' becomes 'was'."]),
      ex(["(i) gave", "'So … that' in a past sentence: the second clause also in the past."]),
      ex(["(j) is", "A proverb is a universal truth and stays in the present, even after the verb 'teaches'."]),
      h("The completed passage"),
      para("Once there lived a poor woodcutter by the side of a river. One day he was cutting wood from a tree on the bank of the river. Suddenly his axe fell into the water. He did not know how to swim, so he sat down and began to weep. Hearing his cry, a fairy appeared before him. She dived into the river and brought up a golden axe. But the woodcutter said that it was not his. At last the fairy brought up his own iron axe. She was so pleased with his honesty that she gave him all three axes. The story teaches us that honesty is the best policy."),
    ],
  },
  {
    id: "verbs-passage-traffic-jam",
    title: "Solved Passage: Traffic Jam",
    prompt: PROMPT,
    body: [
      para("Traffic jam (a) ——— (be) a common problem in the big cities of Bangladesh, especially in Dhaka. It (b) ——— (waste) our valuable time every day. There are many causes of it. The number of vehicles (c) ——— (increase) day by day, but the roads (d) ——— (not widen) accordingly. Many drivers do not care (e) ——— (obey) traffic rules. Unplanned (f) ——— (park) of cars on the roads also (g) ——— (cause) traffic jam. Office-goers and students often fail (h) ——— (reach) their destinations in time. The government (i) ——— (take) some steps already, but more should (j) ——— (do) to solve the problem."),
      h("Answers"),
      ex(["(a) is", "A general fact with the singular subject 'Traffic jam'."]),
      ex(["(b) wastes", "A daily happening ('every day'): V1 + s with the singular 'It'."]),
      ex(["(c) is increasing", "'Day by day' shows a change still going on; 'the number' is singular."]),
      ex(["(d) have not been widened", "Roads cannot widen themselves — passive — and the result is present: Present Perfect passive."]),
      ex(["(e) to obey", "After 'care' the verb takes to + V1."]),
      ex(["(f) parking", "After the adjective 'Unplanned' a noun is needed: the gerund."]),
      ex(["(g) causes", "The subject is the gerund 'parking' — singular."]),
      ex(["(h) to reach", "'Fail' is followed by to + V1."]),
      ex(["(i) has taken", "'Already' asks for the Present Perfect."]),
      ex(["(j) be done", "More steps cannot do themselves: modal + be + V3."]),
      h("The completed passage"),
      para("Traffic jam is a common problem in the big cities of Bangladesh, especially in Dhaka. It wastes our valuable time every day. There are many causes of it. The number of vehicles is increasing day by day, but the roads have not been widened accordingly. Many drivers do not care to obey traffic rules. Unplanned parking of cars on the roads also causes traffic jam. Office-goers and students often fail to reach their destinations in time. The government has taken some steps already, but more should be done to solve the problem."),
    ],
  },
  {
    id: "verbs-passage-nazrul",
    title: "Solved Passage: Kazi Nazrul Islam",
    prompt: PROMPT,
    body: [
      para("Kazi Nazrul Islam (a) ——— (be) our national poet. He (b) ——— (bear) at Churulia in the district of Burdwan in 1899. He lost his father when he (c) ——— (be) only nine. So he could not (d) ——— (continue) his studies properly. In his boyhood he worked in a bakery (e) ——— (earn) his living. Later he joined the army and (f) ——— (go) to Karachi. He wrote fearlessly against injustice and oppression, and so he (g) ——— (call) the rebel poet. His poems and songs (h) ——— (inspire) our freedom fighters in 1971. He (i) ——— (die) in Dhaka in 1976. His works (j) ——— (make) him immortal."),
      h("Answers"),
      ex(["(a) is", "A present fact: he is still our national poet."]),
      ex(["(b) was born", "'Born' is always passive; 1899 is a definite past time."]),
      ex(["(c) was", "A past fact with a singular subject."]),
      ex(["(d) continue", "After the modal 'could' the verb is V1."]),
      ex(["(e) to earn", "Purpose: to + V1."]),
      ex(["(f) went", "Joined by 'and' to the past 'joined': V2 of 'go'."]),
      ex(["(g) is called", "He does not call himself; people call him so even today — present passive."]),
      ex(["(h) inspired", "'In 1971' is a definite past time."]),
      ex(["(i) died", "'In 1976' is a definite past time."]),
      ex(["(j) have made", "His works still keep him alive, so the result is present: Present Perfect with the plural 'works'."]),
      h("The completed passage"),
      para("Kazi Nazrul Islam is our national poet. He was born at Churulia in the district of Burdwan in 1899. He lost his father when he was only nine. So he could not continue his studies properly. In his boyhood he worked in a bakery to earn his living. Later he joined the army and went to Karachi. He wrote fearlessly against injustice and oppression, and so he is called the rebel poet. His poems and songs inspired our freedom fighters in 1971. He died in Dhaka in 1976. His works have made him immortal."),
    ],
  },
  {
    id: "verbs-passage-food-adulteration",
    title: "Solved Passage: Food Adulteration",
    prompt: PROMPT,
    body: [
      para("Food adulteration (a) ——— (be) a heinous crime. Nowadays it (b) ——— (become) a common practice among some dishonest traders. They mix harmful chemicals with food (c) ——— (make) more profit. Fruits (d) ——— (preserve) with formalin, and fish and vegetables are no exception. (e) ——— (eat) adulterated food, people suffer from many fatal diseases like cancer and kidney failure. Children (f) ——— (affect) most. If this practice (g) ——— (continue), the nation will become sick. It is high time the authorities (h) ——— (take) strict action against the culprits. Mobile courts should (i) ——— (work) regularly. People should also (j) ——— (make) aware of the danger."),
      h("Answers"),
      ex(["(a) is", "A general truth with a singular subject."]),
      ex(["(b) has become", "'Nowadays' with a result that is present: Present Perfect."]),
      ex(["(c) to make", "Purpose: to + V1."]),
      ex(["(d) are preserved", "Fruits cannot preserve themselves: present passive with a plural subject."]),
      ex(["(e) Eating", "Two actions by the same subject 'people': the first takes V-ing."]),
      ex(["(f) are affected", "Children receive the harm: passive."]),
      ex(["(g) continues", "An 'if' clause about the future takes the Present Indefinite."]),
      ex(["(h) took", "'It is high time' + subject takes V2."]),
      ex(["(i) work", "After the modal 'should' the verb is V1."]),
      ex(["(j) be made", "People are made aware by others: modal + be + V3."]),
      h("The completed passage"),
      para("Food adulteration is a heinous crime. Nowadays it has become a common practice among some dishonest traders. They mix harmful chemicals with food to make more profit. Fruits are preserved with formalin, and fish and vegetables are no exception. Eating adulterated food, people suffer from many fatal diseases like cancer and kidney failure. Children are affected most. If this practice continues, the nation will become sick. It is high time the authorities took strict action against the culprits. Mobile courts should work regularly. People should also be made aware of the danger."),
    ],
  },
  {
    id: "verbs-passage-women-empowerment",
    title: "Solved Passage: Women Empowerment",
    prompt: PROMPT,
    body: [
      para("In the past women (a) ——— (confine) within the four walls of their homes. They (b) ——— (not allow) to go to school. But the situation (c) ——— (change) a lot now. Today women (d) ——— (work) side by side with men in every sphere of life. They (e) ——— (prove) that they are in no way inferior to men. Many of them (f) ——— (hold) important posts in the government. No nation can prosper by (g) ——— (keep) half of its population idle. So women should (h) ——— (give) equal opportunities. If they (i) ——— (educate), they will be able (j) ——— (contribute) more to the nation."),
      h("Answers"),
      ex(["(a) were confined", "'In the past' and the women received the action: past passive."]),
      ex(["(b) were not allowed", "Past passive in the negative."]),
      ex(["(c) has changed", "'Now' with a change whose result is present: Present Perfect."]),
      ex(["(d) are working", "'Today' with an action going on: Present Continuous."]),
      ex(["(e) have proved", "A past action with a present result: Present Perfect."]),
      ex(["(f) hold", "A present fact with the plural 'Many of them'."]),
      ex(["(g) keeping", "After the preposition 'by' the verb is V-ing."]),
      ex(["(h) be given", "Women receive the opportunities: modal + be + V3."]),
      ex(["(i) are educated", "A future 'if' clause, in the passive: are + V3."]),
      ex(["(j) to contribute", "'Be able' is followed by to + V1."]),
      h("The completed passage"),
      para("In the past women were confined within the four walls of their homes. They were not allowed to go to school. But the situation has changed a lot now. Today women are working side by side with men in every sphere of life. They have proved that they are in no way inferior to men. Many of them hold important posts in the government. No nation can prosper by keeping half of its population idle. So women should be given equal opportunities. If they are educated, they will be able to contribute more to the nation."),
    ],
  },
  {
    id: "verbs-passage-river-pollution",
    title: "Solved Passage: River Pollution",
    prompt: PROMPT,
    body: [
      para("Rivers (a) ——— (be) the lifeline of Bangladesh. But most of our rivers (b) ——— (pollute) now. Many mills and factories (c) ——— (build) on the banks of the rivers. They throw their waste into the water without (d) ——— (treat) it. People also (e) ——— (dump) household garbage into the rivers. As a result, the water (f) ——— (become) unfit for use and fish (g) ——— (die) in large numbers. The Buriganga, which once (h) ——— (flow) with clear water, is now black and stinking. We must (i) ——— (stop) this pollution before it (j) ——— (be) too late."),
      h("Answers"),
      ex(["(a) are", "A general fact with the plural subject 'Rivers'."]),
      ex(["(b) are being polluted", "'Now' and the rivers receive the action: present continuous passive."]),
      ex(["(c) have been built", "Factories cannot build themselves, and they stand there now: Present Perfect passive."]),
      ex(["(d) treating", "After the preposition 'without' the verb is V-ing."]),
      ex(["(e) dump", "A habitual action with the plural 'People'."]),
      ex(["(f) has become", "A change whose result is present: Present Perfect."]),
      ex(["(g) are dying", "An action going on now: Present Continuous."]),
      ex(["(h) flowed", "'Once' here means 'in the past': Past Indefinite."]),
      ex(["(i) stop", "After the modal 'must' the verb is V1."]),
      ex(["(j) is", "A 'before' clause about the future takes the Present Indefinite."]),
      h("The completed passage"),
      para("Rivers are the lifeline of Bangladesh. But most of our rivers are being polluted now. Many mills and factories have been built on the banks of the rivers. They throw their waste into the water without treating it. People also dump household garbage into the rivers. As a result, the water has become unfit for use and fish are dying in large numbers. The Buriganga, which once flowed with clear water, is now black and stinking. We must stop this pollution before it is too late."),
    ],
  },
  {
    id: "verbs-passage-value-of-time",
    title: "Solved Passage: The Value of Time",
    prompt: PROMPT,
    body: [
      para("Time (a) ——— (be) very valuable. Once it (b) ——— (pass), it never comes back. There is a proverb that time and tide (c) ——— (wait) for none. A man who (d) ——— (know) the value of time can succeed in life. Those who (e) ——— (waste) time have to repent later. A student (f) ——— (have) many duties to perform. If he (g) ——— (waste) his time in idle gossip, he will not be able (h) ——— (do) well in the examination. Great men became great by (i) ——— (make) the best use of their time. So we should (j) ——— (not waste) a single moment."),
      h("Answers"),
      ex(["(a) is", "A general truth with a singular subject."]),
      ex(["(b) passes", "'Once' here means 'as soon as' — a time clause about any time takes the Present Indefinite."]),
      ex(["(c) wait", "A proverb stays in the present; 'time and tide' is a plural subject."]),
      ex(["(d) knows", "'Who' takes the number of its antecedent 'a man': singular."]),
      ex(["(e) waste", "'Who' takes the number of its antecedent 'Those': plural."]),
      ex(["(f) has", "A general fact with a singular subject."]),
      ex(["(g) wastes", "An 'if' clause about the future takes the Present Indefinite."]),
      ex(["(h) to do", "'Be able' is followed by to + V1."]),
      ex(["(i) making", "After the preposition 'by' the verb is V-ing."]),
      ex(["(j) not waste", "After the modal 'should' the verb is V1; 'not' comes after the modal."]),
      h("The completed passage"),
      para("Time is very valuable. Once it passes, it never comes back. There is a proverb that time and tide wait for none. A man who knows the value of time can succeed in life. Those who waste time have to repent later. A student has many duties to perform. If he wastes his time in idle gossip, he will not be able to do well in the examination. Great men became great by making the best use of their time. So we should not waste a single moment."),
    ],
  },
];
